### ISSUE TITLE
Laravel 5.2 Request header field Content-Type is not allowed 

### ISSUE THREAD

**Issue by ohaiyou** [barryvdh/laravel-cors#100]
I tried to use this package with laravel 5.2 to update data (POST METHOD), but I always get the same error:
`XMLHttpRequest cannot load http://www.url.com/api No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'http://localhost' is therefore not allowed access. The response had HTTP status code 500.
`
GET request works fine, but POST return error.

```
<?php
  return [
      'supportsCredentials' => false,
      'allowedOrigins' => ['*'],
      'allowedHeaders' => ['Content-Type'],
      'allowedMethods' => ['GET', 'POST', 'PUT',  'DELETE'],
      'exposedHeaders' => [],
      'maxAge' => 0,
      'hosts' => [],
  ];

```

this is my code on Route.php

```
<?php


  Route::group(['prefix' => 'api/v1'], function () {

          Route::group(['middleware' => ['web', 'cors']], function () {

              Route::post('order/cart/add','OrderController@cart_add');

     });
  });

```

could you help me?
Thanks

**Comment by wendellpalazzo** [comment]
Hi @ohaiyou i have a problem too... in this moment... 
but like a server cache... ou browser cache.. 
but suddenly works... then I think the problem is the cache
