### ISSUE TITLE
Change the README, because CSRF works properly

### ISSUE THREAD

**Issue by sbk** [barryvdh/laravel-cors#102]
Hello Barry,

thank you for writing this useful plugin. I've just installed it and it works like expected.

At the first attempt I needed to disable the CSRF, but there is a better solution and you might mention it within the README, such that people do not have to search for it - like I did.

There are no problems with CSRF, when the AJAX call was setup properly. See this link:

http://stackoverflow.com/questions/32256969/laravel-5-ajax-post-500-internal-server-error

Kind regards,
Sebastian

**Comment by cjke** [comment]
It works, in certain situations. If you have a page that has access to the cross site token, do you even really need the cors library?
