### ISSUE TITLE
Addition of Authorization Headers Appears to Prevent CORs from Working Properly

### ISSUE THREAD

**Issue by mtpultz** [barryvdh/laravel-cors#104]
**Overview**

I'm using this package with Laravel 5.2 as an API for AngularJS 1.4.x that implement JWT-tokens for authentication, which is stored in local storage, and passed up in requests using an interceptor.  It seems that when I write the authentication header to the config of the interceptor CORs after successfully authenticating with the use of CORs it doesn't allow me access to the endpoint of any subsequent requests, as if the Authentication header isn't permitted though the config is set to accept everything:

**BarryVDH/CORS Config**

    'supportsCredentials' => false,
    'allowedOrigins'      => ['*'],
    'allowedHeaders'      => ['*'],
    'allowedMethods'      => ['*'],
    'exposedHeaders'      => [],
    'maxAge'              => 3600,
    'hosts'               => [],

**Symptoms**

If I login for the first time I get a JWT token, which is stored in local storage.  If I attempt to submit a request that has had the Authorization header added CORs fails with this error, but using that same token I can hit the endpoint using Postman.

    XMLHttpRequest cannot load http://app.dev/api/v1/auth/login. 
    No 'Access-Control-Allow-Origin' header is present on the 
    requested resource. Origin 'http://localhost:8100' is therefore 
    not allowed access. The response had HTTP status code 500.

If I manually remove the token from local storage using the resource tab in Chrome, and login again it will respond with another token, but any other outgoing requests fail once the authorization token is added to the request.

To prove CORs was in fact working I attempted the initial login with the provider commented out, and it wouldn't authenticate so I'm sure the package is working.

**Request Headers**

Request headers when attempting to login and no JWT token is stored in local storage so no authorization header is passed up to the server:

    Accept:*/*
    Accept-Encoding:gzip, deflate, sdch
    Accept-Language:en-US,en;q=0.8
    Access-Control-Request-Headers:accept, authorization, content-type
    Access-Control-Request-Method:POST
    Connection:keep-alive
    Host:app.dev
    Origin:http://localhost:8100
    Referer:http://localhost:8100/
    User-Agent:Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/48.0.2564.116 Safari/537.36

Subsequent outgoing requests with the authorization header added until the token is manually removed:

    Accept:application/json, text/plain, */*
    Accept-Encoding:gzip, deflate
    Accept-Language:en-US,en;q=0.8
    Authorization:Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJodHRwOi8vc2lyZW4uZGV2L2FwaS92MS9hdXRoL2xvZ2luIiwiaWF0IjoxNDU2Mjc2MTQzLCJleHAiOjE0NTYyNzk3NDMsIm5iZiI6MTQ1NjI3NjE0MywianRpIjoiMTA2OGRjY2U1ZGExN2MxOTNkNjAyZTA0OTIxM2M4NWEiLCJzdWIiOiJmNDczNjdiZi1iODQxLTQ1ZTMtOTdkMy1lY2ZmYWNkMGM1MWQifQ.-vZQz87HeTewFtWYBCqhnj1FsrV7lJX4alIRy3Z8XtY
    Connection:keep-alive
    Content-Length:42
    Content-Type:application/json;charset=UTF-8
    Host:app.dev
    Origin:http://localhost:8100
    Referer:http://localhost:8100/
    User-Agent:Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/48.0.2564.116 Safari/537.36

**AngularJS Interceptor**

    .factory('AuthRequestInterceptor', [
        '$q', '$log', 'AuthFactory',
        function ($q, $log, AuthFactory) {

            return {
                request: request
            };

            function request(config) {

                var token = AuthFactory.getToken();

                // Only alter the headers if the token exists
                if (angular.isDefined(token) && token !== null) {
                    config.headers = config.headers || {};
                    config.headers.Authorization = 'Bearer ' + token;
                }

                return config;
            };

I've tried adding `Authorization` to the allowedHeaders with and without '*', and a few other attempts where the allowedMethods were explicitly added.  I've followed BarryVdh's configuration as far as I can tell.

**Comment by mtpultz** [comment]
Looks like this is also logging an error to laravel.log.  This doesn't occur on the initial login, but occurs on subsequent requests that the interceptor passes up the Authentication header bearing the JWT token, see both the request headers in the initial post.

```
    [2016-02-24 07:57:53] local.ERROR: Symfony\Component\Debug\Exception\FatalThrowableError: Type error: Argument 1 passed to Barryvdh\Cors\Stack\CorsService::addActualRequestHeaders() must be an instance of Symfony\Component\HttpFoundation\Response, array given, called in /home/vagrant/app/vendor/barryvdh/laravel-cors/src/HandleCors.php on line 44 in /home/vagrant/app/vendor/barryvdh/laravel-cors/src/Stack/CorsService.php:69
    Stack trace:
    #0 /home/vagrant/app/vendor/barryvdh/laravel-cors/src/HandleCors.php(44): Barryvdh\Cors\Stack\CorsService->addActualRequestHeaders(Array, Object(Illuminate\Http\Request))
    #1 [internal function]: Barryvdh\Cors\HandleCors->handle(Object(Illuminate\Http\Request), Object(Closure))
    #2 /home/vagrant/app/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(124): call_user_func_array(Array, Array)
    #3 [internal function]: Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
    #4 /home/vagrant/app/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(32): call_user_func(Object(Closure), Object(Illuminate\Http\Request))
    #5 [internal function]: Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
    #6 /home/vagrant/app/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(102): call_user_func(Object(Closure), Object(Illuminate\Http\Request))
    #7 /home/vagrant/app/vendor/laravel/framework/src/Illuminate/Routing/Router.php(726): Illuminate\Pipeline\Pipeline->then(Object(Closure))
    #8 /home/vagrant/app/vendor/laravel/framework/src/Illuminate/Routing/Router.php(699): Illuminate\Routing\Router->runRouteWithinStack(Object(Illuminate\Routing\Route), Object(Illuminate\Http\Request))
    #9 /home/vagrant/app/vendor/laravel/framework/src/Illuminate/Routing/Router.php(675): Illuminate\Routing\Router->dispatchToRoute(Object(Illuminate\Http\Request))
    #10 /home/vagrant/app/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(246): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request))
    #11 [internal function]: Illuminate\Foundation\Http\Kernel->Illuminate\Foundation\Http\{closure}(Object(Illuminate\Http\Request))
    #12 /home/vagrant/app/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(52): call_user_func(Object(Closure), Object(Illuminate\Http\Request))
    #13 /home/vagrant/app/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/CheckForMaintenanceMode.php(44): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
    #14 [internal function]: Illuminate\Foundation\Http\Middleware\CheckForMaintenanceMode->handle(Object(Illuminate\Http\Request), Object(Closure))
    #15 /home/vagrant/app/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(124): call_user_func_array(Array, Array)
    #16 [internal function]: Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
    #17 /home/vagrant/app/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(32): call_user_func(Object(Closure), Object(Illuminate\Http\Request))
    #18 [internal function]: Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
    #19 /home/vagrant/app/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(102): call_user_func(Object(Closure), Object(Illuminate\Http\Request))
    #20 /home/vagrant/app/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(132): Illuminate\Pipeline\Pipeline->then(Object(Closure))
    #21 /home/vagrant/app/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(99): Illuminate\Foundation\Http\Kernel->sendRequestThroughRouter(Object(Illuminate\Http\Request))
    #22 /home/vagrant/app/public/index.php(53): Illuminate\Foundation\Http\Kernel->handle(Object(Illuminate\Http\Request))
    #23 {main} 
```

**Comment by ericadamski** [comment]
@mtpultz what was the solution here? I am having the same issue with JWT and the Authorization headers

**Comment by mtpultz** [comment]
I can't remember that was over a year ago.  Using Laravel 5.4 I didn't have to do anything on a recent project it all just worked.  Sorry man

**Comment by ericadamski** [comment]
No worries! Figured it out, just upgraded to `0.9.2`. Thanks for responding!
