### ISSUE TITLE
Not Allowed access - Laravel 5.2

### ISSUE THREAD

**Issue by donnygunawan93** [barryvdh/laravel-cors#105]
![untitled](https://cloud.githubusercontent.com/assets/10414213/13608286/adff4fd2-e586-11e5-9dd3-2eb434d82f93.png)

It works when I accessed from 192.168.0.101 **without** port 8100,
but how can make that work on port 8100?

I haven't any problem on L5.1, but now I use L5.2 and I got this problem T_T

**Comment by chris2cant** [comment]
Hi,

Change

`'Barryvdh\Cors\ServiceProvider'` to `Barryvdh\Cors\ServiceProvider::class` on `config/app.php`

**Comment by donnygunawan93** [comment]
already bro T_T

**Comment by 0plus1** [comment]
Same issue here on  lumen   "version": "v5.1.6", cors: "version": "v0.8.0",

Worked before.

**Comment by donnygunawan93** [comment]
I just missing cors middleware
