### ISSUE TITLE
the thing with the cors issue is getting tough

### ISSUE THREAD

**Issue by lulzimfazlija2** [barryvdh/laravel-cors#106]
I have Laravel 5.0.x and I have installed laravel-cors packgage 0.7.x but seems not working for me:

This is how my config/cors.php looks like:

```
return [
/*
 |--------------------------------------------------------------------------
 | Laravel CORS
 |--------------------------------------------------------------------------
 |

 | allowedOrigins, allowedHeaders and allowedMethods can be set to array('*')
 | to accept any value, the allowed methods however have to be explicitly listed.
 |
 */
'supportsCredentials' => false,
'allowedOrigins' => ['*'],
'allowedHeaders' => ['*'],
'allowedMethods' => ['GET', 'POST', 'PUT',  'DELETE'],
'exposedHeaders' => [],
'maxAge' => 0,
'hosts' => [],
];
```

And in Http/Kernel.php I have this:

```
protected $middleware = [
    'Illuminate\Foundation\Http\Middleware\CheckForMaintenanceMode',
    'Illuminate\Cookie\Middleware\EncryptCookies',
    'Illuminate\Cookie\Middleware\AddQueuedCookiesToResponse',
    'Illuminate\Session\Middleware\StartSession',
    'Illuminate\View\Middleware\ShareErrorsFromSession',
    //'App\Http\Middleware\VerifyCsrfToken', TODO:: Enable this for security
    'Barryvdh\Cors\HandleCors',
];
```

Anyone knows how to fix, I always get cors origin not allowed response even when there is a syntax error on code ?

Have been trying for the whole day was not succesfull...

Any help, tip, would appreciate.

**Comment by barryvdh** [comment]
Did you try this from the readme?
https://github.com/barryvdh/laravel-cors#debugging-errors

**Comment by lulzimfazlija2** [comment]
I did tried every possible technique, and still not working, I have a very simple question, does you package actually works with Laravel 5.0.35, which is my version.

Thanx

**Comment by lulzimfazlija2** [comment]
If I add that allow origin * on tom of public/index.php I get different error which is almost same as the first one.

this is the error when I add on top of index.php:
XMLHttpRequest cannot load http://localhost:81/venture-backend/public/authenticate. Response to preflight request doesn't pass access control check: The 'Access-Control-Allow-Origin' header contains multiple values '*, http://localhost:9000', but only one is allowed. Origin 'http://localhost:9000' is therefore not allowed access.

**Comment by lulzimfazlija2** [comment]
@barryvdh when you have some free time to explain more this issue why is not working for me, I would appreciate alot...

**Comment by rochapablo** [comment]
+1
