### ISSUE TITLE
Laravel 5.2.24 "Class cors does not exists"

### ISSUE THREAD

**Issue by dominikveils** [barryvdh/laravel-cors#109]
After updating my project to 5.2.24 I'm getting this error: "Class cors does not exists"

I've used the `'cors'` middleware in my `Kernel.php`

PS
After changing it to `\Barryvdh\Cors\HandleCors::class` the error is disappeared, so I think the problem with the `named` middleware: 'cors'.

**Comment by nerijunior** [comment]
I'm having the same problem. +1

**Comment by dominikveils** [comment]
@nerijunior as a temp solution you can change 'cors' to `\Barryvdh\Cors\HandleCors::class`, it will work.

**Comment by aios** [comment]
+1

**Comment by CrestApps** [comment]
I don't this this is a bug. It may be how you upgraded.

I had the same error. In my case, I had the line in my Kernel.php file
```
'cors' => \App\Http\Middleware\Cors::class,
```

However, the class  `App\Http\Middleware\Cors` did not exists.

After creating the following class everything worked.
```
<?php

namespace App\Http\Middleware;

use Closure;

class Cors
{
    /**
     * Handle an incoming request.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \Closure  $next
     * @return mixed
     */
    public function handle($request, Closure $next)
    {
        return $next($request)
            ->header('Access-Control-Allow-Origin', '*')
            ->header('Access-Control-Allow-Methods', 'GET, POST, PUT, DELETE, PATCH');
    }
}
```

**Comment by nerijunior** [comment]
@CrestApps the problem is the OPTIONS preflight request, this simple implementation of CORS middleware do not cover the preflight.

**Comment by tucq88** [comment]
I'm having the same problem with Laravel 5.3.30.

**Comment by JTallis** [comment]
I added the middleware to the global middleware stack which gave me issues when I attempted to use the middleware in my routes. I had to add `'cors' => \Barryvdh\Cors\HandleCors::class,` to `$routeMiddleware` and then I was able to use the middleware `cors` in my routes. I'm not sure if this is related to the issues people have been having or not.

**Comment by tucq88** [comment]
@JTallis So do I. It's quite strange because it's only me who need add `cors` to routeMiddleware while other colleagues don't (and it works on their side ntw).

**Comment by CrestApps** [comment]
@tucq88. I think this issue only happened if you add `->middlewear('cors')` to your route setup. If you don't then you won't get this issue.

**Comment by tucq88** [comment]
```
\Route::middleware(['cors', 'bindings'])
             ->namespace($this->namespace . '\Api')
             ->prefix('api/v1')
             ->group(base_path('routes/api.php'));
```
No, I added it in RouteProvider instead. Most strange part is everybody works ok. Only me :'(

**Comment by CrestApps** [comment]
Look in the kernel.php file for the value representing the cors key. Then, make sure that file exists in your app.

'cors' => \App\Http\Middleware\Cors::class,
