### ISSUE TITLE
Laravel 5.2.24. Class HandlePreflight does not work for OPTIONS request

### ISSUE THREAD

**Issue by dominikveils** [barryvdh/laravel-cors#110]
When sending the OPTIONS request no headers are sent back.
As I can see, the following code in HandlePreflight:

``` php
if ($this->cors->isPreflightRequest($request) && $this->hasMatchingCorsRoute($request)) {
    $preflight = $this->cors->handlePreflightRequest($request);
    $response->headers->add($preflight->headers->all());
}
```

doesn't work, and no headers are added to the response.

The solution I found is to add to `AppServiceProvider`'s boot method call for the HandlePreflightSimple class, and now its work!

``` php
    public function boot(Request $request, Kernel $kernel)
    {
        if ($request->isMethod('OPTIONS')) {
            $kernel->prependMiddleware(HandlePreflightSimple::class);
        }
    }
```

PS
The problem seems to be only when using CORS within the `$middlewareGroups`.
_Solution_: add `HandleCors` class to the global `$middleware` section.

**Comment by 0plus1** [comment]
Confirmind the issue.

Same issue here on lumen "version": "v5.1.6", cors: "version": "v0.8.0".

**Comment by Broutard** [comment]
I confirm :+1:

**Comment by namelivia** [comment]
I'm also experiencing this issue, has been easily fixed for my project by adding 'HandleCors' to '$middleware' as @dominikveils wrote.

**Comment by rdpascua** [comment]
I'm using laravel 5.2, putting `\Barryvdh\Cors\HandleCors::class` in global middle resolves the issue. What seems to be the problem?

**Comment by adamgoose** [comment]
Also experiencing the issue on Laravel v5.2.29. Adding it to the global middleware does solve the issue, but I'd much rather put it on a middleware group.

**Comment by brunofaraujo** [comment]
Using laravel 5.2.39 here and faced this same issue.
This fix saved my day, thanks @dominikveils 
Edit `App\Http\Kernel.php` and add `\Barryvdh\Cors\HandlePreflightSimple::class` to `$middleware` array.

**Comment by Redshift-Web-Design** [comment]
Hey guys. I am having a similar sort of issue however it is only an issue when making requests from my localhost to the live server. I have Production server serving data to an Ionic app. When running the ionic app in the simulator or using Ionic View the CORS works fine. But when testing the app with ionic serve in my browser from local host I get the error below.
`Response for preflight has invalid HTTP status code 405`
Any idea why this would be happening for localhost only?

Laraval v5.2

Thanks in advance.

**Comment by Redshift-Web-Design** [comment]
Ignore my comment above. For anyone else having similar issues the issue turned out to be some strange deny's that somehow crept into the htaccess file. I replaced the .htaccess with the one from the laravel git repo and all is working :-)

**Comment by rdpascua** [comment]
is this resolved already?

**Comment by alexjose** [comment]
Anything happening on this issue?
