### ISSUE TITLE
Access-Control-Allow-Headers in OPTIONS not sending

### ISSUE THREAD

**Issue by IAmJulianAcosta** [barryvdh/laravel-cors#112]
Hi! I'm getting this error:

`XMLHttpRequest cannot load http://fileupload.dev/. Request header field Cache-Control is not allowed by Access-Control-Allow-Headers in preflight response.`

The headers sent by laravel are:

```
Access-Control-Allow-Origin →chrome-extension://fhbjgbiflinjbdggehcddcbncdddomop
Cache-Control →no-cache
Connection →Keep-Alive
Content-Length →0
Content-Type →text/html; charset=UTF-8
Date →Tue, 12 Apr 2016 03:15:06 GMT
Keep-Alive →timeout=5, max=100
Server →Apache
Vary →Origin
X-Powered-By →PHP/7.0.0`
```

My `routes.php`: 

``` php
    Route::group(
        array ( 'middleware' => 'cors' ), function ( $router ) {
        $router->options ('', function () {});
```

`cors.php`:

``` php
        'supportsCredentials' => false,
        'allowedOrigins' => array ( '*' ),
        'allowedHeaders' => array ( '*' ),
        'allowedMethods' => array ( 'GET', 'POST', 'PUT',  'DELETE' ),
        'exposedHeaders' => [ ],
        'maxAge' => 0,
        'hosts' => [],
```

~~Am I missing something? I'm using `0.8.0`~~

Works if I don't use `'allowedOrigins' => array ( '*' )`, if I specify the specific domain, it works.

**Comment by mikkokut** [comment]
Same here!

**Comment by vvinhas** [comment]
Same

```
Response to preflight request doesn't pass access control check: No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'http://lvh.me:8080' is therefore not allowed access.
```

**Comment by rochapablo** [comment]
+1

**Comment by 0plus1** [comment]
I actually dug into the code for this one.
Just add this line in your middleware:

Barryvdh\Cors\HandlePreflightSimple::class

The preflight has another Middleware which is separated from the standard CORS. I would love to know why this was not documented anywhere...

**Comment by barryvdh** [comment]
That was meant for Lumen, which is added here: https://github.com/barryvdh/laravel-cors/blob/e0e1db7271582ce4a4023ea77de5a8235cc2721f/src/LumenServiceProvider.php#L48

If that works, it probably means the middleware/route isn't detected here: https://github.com/barryvdh/laravel-cors/blob/e0e1db7271582ce4a4023ea77de5a8235cc2721f/src/HandlePreflight.php#L45

**Comment by NightravenJames** [comment]
Doesn't work for me

**Comment by barryvdh** [comment]
Can you try again with https://github.com/barryvdh/laravel-cors/releases/tag/v0.10.1 ?

Please re-open this issue when the problem still persists.
