### ISSUE TITLE
No CORS-Headers sent in Lumen 5.2

### ISSUE THREAD

**Issue by bernhardw** [barryvdh/laravel-cors#113]
Using Lumen 5.2.6 and laravel-cors 0.8.0.

After copying cors.php to /config and updating my /bootstrap/app.php with 

```
// [...]

$app->middleware([
    Barryvdh\Cors\HandleCors::class
]);

$app->register(Barryvdh\Cors\LumenServiceProvider::class);

$app->configure('cors');

// [...]
```

no CORS headers are being sent and no errors are shown. 
The /config/cors.php is being picked up though.

Adding `header("Access-Control-Allow-Origin: *");` to /public/index.php shows the header.

Is there anything missing, or do I still need to specify the cors middleware in my routes/controllers?

**Comment by Jordy-A** [comment]
Any update on this? Still the same issue with Lumen 5.2.

**Comment by lepczynski-s** [comment]
@bernhardw @Jordy-A 

Did you somehow managed to solve this issue? I'm having the same one - i've tried about 5 or 6 different cors libraries and none of them works in lumen.

Also, i would add that on php 5.6.x i get `200 for OPTIONS (cors working)` and then `200 for POST (cors header not present)`, but: when i switch to php 7.0.x then i get `200 for OPTIONS (cors working)` and then... `404 for post`.

**Comment by bernhardw** [comment]
Honestly, I just kept the `Access-Control-Allow-Origin` headers hard-coded in my index.php for that project and was using Laravel since.

**Comment by Jordy-A** [comment]
Yes, same for me. I created my own middleware and that seems to work.

**Comment by lepczynski-s** [comment]
@bernhardw @Jordy-A Thank's for quick response!

Envy you guys: I have preflight requests (as far as i understand because of `Authorization: Bearer: <jwt-token>` header) and those workarounds probably won't work for me, as i'd end up defining an `OPTIONS` for every possible route then.

**Comment by lepczynski-s** [comment]
@bernhardw @Jordy-A I've found something. It seems that everything works fine, just as expected, but only when i have xdebug enabled in php.ini. Anyway after enabling it, two (laravel-cors and some other i've tested) of them works fine without any hacks. After disabling xdebug they stop working. An so on.

Do you maybe happen to code with xdebug disabled and / or on windows wamp (this were i have the issue)?

Anyway it seems like it's absolutely not laravel-cors related.

**Comment by Jordy-A** [comment]
It could be related to Wamp as I'm using that too, yes. I'll take a look at it later!
