### ISSUE TITLE
Route::controller() and $this->middleware('cors')

### ISSUE THREAD

**Issue by ashgibson** [barryvdh/laravel-cors#118]
Using a combination of Route::controller() and $this->middleware('cors') in the controllers constructor doesn't seem to work. The HandlePreFlight class hasMatchingCorsRoute function only seem to check for middleware specified in Route::'s but not in controller.

**Comment by barryvdh** [comment]
Can you try again with https://github.com/barryvdh/laravel-cors/releases/tag/v0.10.1 ?

Please re-open this issue when the problem still persists.
