### ISSUE TITLE
 No 'Access-Control-Allow-Origin' header is present on the requested resource.

### ISSUE THREAD

**Issue by vijay94** [barryvdh/laravel-cors#125]
I am using ember for front end and laravel for api back end. The problem i am facing is i have two api say "a" and "b". I solved the problem " No 'Access-Control-Allow-Origin' header is present on the requested resource." with my api "a" by adding cors to my project and adding the cors middleware to my route. But my another api "b" is also having the same issue eventhough i added the cors middleware.

**Comment by AbdurRehman26** [comment]
Is this issue fixed ?

**Comment by vijay94** [comment]
Yeah i fixed this issue

**Comment by AbdurRehman26** [comment]
how did you do it  ??? my get requests are working fine but cant seem to post anything

**Comment by vijay94** [comment]
Are u in facebook?

My name is vijay sundarapandiyan

With dragon ball super goku dp

Text me there and explain what is the issue.

**Comment by AbdurRehman26** [comment]
do u have skype ? I am at the office and we are not allowed to use facebook

**Comment by vijay94** [comment]
Use my mailid to search.

Vijaycenation14@gmail.com

**Comment by AbdurRehman26** [comment]
added u on skype

**Comment by vijay94** [comment]
Text me in that.

**Comment by AbdurRehman26** [comment]
Accept my request.. cant message you without that

**Comment by wouterNL** [comment]
Can't you post the solution here? I would like to know as well.

**Comment by vijay94** [comment]
I created a Custom CORS middleware and applied it to the routes.  I will share the code here tomorrow.

**Comment by vijay94** [comment]
<?php namespace App\Http\Middleware;

use Closure;

class CORS {

    /**
     * Handle an incoming request.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \Closure  $next
     * @return mixed
     */
    public function handle($request, Closure $next)
    {

        header("Access-Control-Allow-Origin: *");

        // ALLOW OPTIONS METHOD
        $headers = [
            'Access-Control-Allow-Methods'=> 'POST, GET, OPTIONS, PUT, DELETE',
            'Access-Control-Allow-Headers'=> 'Content-Type, X-Auth-Token, Origin'
        ];
        if($request->getMethod() == "OPTIONS") {
            // The client-side application can set only headers allowed in Access-Control-Allow-Headers
            return Response::make('OK', 200, $headers);
        }

        $response = $next($request);
        foreach($headers as $key => $value)
            $response->header($key, $value);
        return $response;
    }

}

This is my middleware. Instead of * in header("Access-Control-Allow-Origin: *"); you can use you frontend host:port

**Comment by vijay94** [comment]
<?php namespace App\Http\Middleware;<br>
<br>
use Closure;
<br>
class CORS {<br>
<br>
    /**<br>
     * Handle an incoming request.<br>
     *<br>
     * @param  \Illuminate\Http\Request  $request<br>
     * @param  \Closure  $next<br>
     * @return mixed<br>
     */<br>
    public function handle($request, Closure $next)<br>
    {<br>
<br>
        header("Access-Control-Allow-Origin: *");<br>
<br>
        // ALLOW OPTIONS METHOD<br>
        $headers = [<br>
            'Access-Control-Allow-Methods'=> 'POST, GET, OPTIONS, PUT, DELETE',<br>
            'Access-Control-Allow-Headers'=> 'Content-Type, X-Auth-Token, Origin'<br>
        ];<br>
        if($request->getMethod() == "OPTIONS") {<br>
            // The client-side application can set only headers allowed in Access-Control-Allow-Headers<br>
            return Response::make('OK', 200, $headers);<br>
        }<br>
<br>
        $response = $next($request);<br>
        foreach($headers as $key => $value)<br>
            $response->header($key, $value);<br>
        return $response;<br>
    }<br>
<br>
}<br>
<br>

**Comment by barryvdh** [comment]
Can you try with v0.10.1? Please re-open if the issue this persists.
