### ISSUE TITLE
403 for POSTS with Postman

### ISSUE THREAD

**Issue by beedubsss** [barryvdh/laravel-cors#126]
Having a weird issue where my Postman Post requests are returning 403. Using a curl post request works fine but usually for debugging I use postman for tests. I only currently have allowed one origin which is a local website. Using the latest version of the module.

**Comment by mzahidriaz** [comment]
Having same issue with Postman on Chrome and on Chrome also I am getting 403. 
Also for me this happens with the https requests, simple http requests are working fine
But works fine on FF and IE Edge

**Comment by barryvdh** [comment]
Closing this as part of an issue-cleanup. Please re-open if this is still an issue on the latest version.
