### ISSUE TITLE
Error (No 'Access-Control-Allow-Origin' header is present on the requested resource.)

### ISSUE THREAD

**Issue by vitalibr** [barryvdh/laravel-cors#127]
Hi all and @barryvdh,

I created an application in AngularJS and I'm trying to make calls to the Laravel API: 
- MyApp (AngularJS): **http://localhost:8080/**
- API (Laravel Boilerplate): **http://localhost:8000/**

I use Laravel [API Boilerplate (JWT Edition)](https://github.com/francescomalatesta/laravel-api-boilerplate-jwt) to API.

But I get this error in the browser console:

> XMLHttpRequest cannot load http://localhost:8000/api/auth/login. No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'http://localhost:8080' is therefore not allowed access.

I tried to apply the cors middleware (barryvdh/laravel-cors) in api_routes.php but the error remains.

api_routes.php:

```
<?php

$api = app('Dingo\Api\Routing\Router');

$api->version('v1', ['middleware' => 'cors'], function ($api) {

    $api->post('auth/login', 'App\Api\V1\Controllers\AuthController@login');
    $api->post('auth/signup', 'App\Api\V1\Controllers\AuthController@signup');
    $api->post('auth/recovery', 'App\Api\V1\Controllers\AuthController@recovery');
    $api->post('auth/reset', 'App\Api\V1\Controllers\AuthController@reset');

    // example of protected route
    $api->get('protected', ['middleware' => ['api.auth'], function () {     
        return \App\User::all();
    }]);

    // example of free route
    $api->get('free', function() {
        return \App\User::all();
    });

});
```

My config/cors.php:

```
return [
    'supportsCredentials' => false,
    'allowedOrigins' => ['*'],
    'allowedHeaders' => ['*'],
    'allowedMethods' => ['*'],
    'exposedHeaders' => [],
    'maxAge' => 0,
    'hosts' => [],
];
```

Error:
![Error](https://s31.postimg.org/synyo4vrf/error.png)
![Error](https://s31.postimg.org/4w74t9f4b/error2.jpg)

**Comment by victor-ponamariov** [comment]
Same here

**Comment by vitalibr** [comment]
@victor-ponamariov I've tried n ways and nothing solves this problem.
Can anyone help us?

**Comment by minowu** [comment]
Same problem. @victor-ponamariov

**Comment by minowu** [comment]
@victor-ponamariov My App working! Because PHP ini bug: 
```
PHP Deprecated:  Automatically populating $HTTP_RAW_POST_DATA is deprecated and will be removed in a future version. To avoid this warning set 'always_populate_raw_post_data' to '-1' in php.ini and use the php://input stream instead. in Unknown on line 0
```
Change php.ini to reslove this problem. This is not laravel-cors bug.

**Comment by renielDev** [comment]
@vitalibr 
We are also having the same issue. We are also using the angularjs and laravel. Hope to get some help for this. thanks.

**Comment by naderst** [comment]
Don't use Wamp I fixed this issue using Xampp instead. Hope this help

**Comment by simplenotezy** [comment]
I managed to fix this issue.

I noticed my composer was using `dev-master`, and I am using `Laravel 5.2`. The most recent release adds support for laravel 5.3 so I figured this might be lacking backwards compatibility with 5.2.

Updating my `composer.json` to require `0.8.1` fixed the issue on Laravel v `5.2.*`.

**Solution:**

Update composer.json to:

    "barryvdh/laravel-cors": "0.8.1",

**Comment by eagle-r** [comment]
I use `Laravel 5.1` and tried updating to the latest version of `laravel-cors` but no luck for me. Anyone else have another suggestion?

**Comment by sandervanhooft** [comment]
Same here. I am able to GET/POST to normal routes though, but no luck with file upload (POST).

**Comment by minhlong** [comment]
Same here, but this error only appear when i try to use ng-resource

**Comment by sandervanhooft** [comment]
My issue was solved by moving all (instead the laravel api only) servers to
https. I don't know what was going on though, if this was the real issue
the error message seems unrelated.

**Comment by sandervanhooft** [comment]
@barryvdh  et al,

Ok, so I found out my issue was not really solved... Any clue on this one?

I've updated to `0.8.2` as this should include a fix for loading the middleware on route groups, but the issue persists if the controller should return an error (i.e. no status code 20*, but a 500 instead).

This use case regards a POST request using whatwg-fetch. The controller should invalidate the included file if it's not an image.

Symptoms:

- In case of a correct file, the controller processes the image ok and returns a 201 response with some data. This works fine.

- In case of a `basic` or `cors` request, the dreaded `No 'Access-Control-Allow-Origin' header is present on the requested resource.` is thrown in the browser console, suggesting I should try a `no-cors` request. I don't get a (500) response.

- In case of a `no-cors` request, I get an opaque response which is unusable. I can see in the network logs it bears the error message, but there's (by design, as I understand) no way to retrieve it.

**Comment by goeroeku** [comment]
I have same problem using laravel 5.2, php 5.6 on windows x64.
I try to disable always_populate_raw_post_data on php.ini (ref: [http://php.net/manual/en/ini.core.php#ini.always-populate-raw-post-data](url)), and **Solved** my problem ;)

**Comment by sandervanhooft** [comment]
@goeroeku Did you set it to `-1`? I am going to try this.

**Comment by sandervanhooft** [comment]
Did not solve the issue. I've tried adding this on top of `public/index.php` (deployed with Laravel Forge):

- `ini_set('always_populate_raw_post_data', 0);`
- `ini_set('always_populate_raw_post_data', "0");`
- `ini_set('always_populate_raw_post_data', -1);`
- `ini_set('always_populate_raw_post_data', "-1");`

Any clue?

**Comment by goeroeku** [comment]
@sandervanhooft variable always_populate_raw_post_data can't set with ini_set, you must set it on php.ini
[ref](http://php.net/manual/en/ini.list.php).

![image](https://cloud.githubusercontent.com/assets/11331745/18387326/389c2806-76c6-11e6-90c3-eb33dcededb3.png)


add phpinfo() on `public/index.php` to ensure the configuration is correct

**Comment by sandervanhooft** [comment]
@goeroeku Just tried it (thanks!), but it seems deprecated in the PHP version I use (PHP7.0). So it does not pop up in the `phpinfo()`. The issue persists.

What PHP version are you using? Any other thoughts?

**Comment by tabirkeland** [comment]
All,

Running `Laravel Framework version Lumen (5.2.9) (Laravel Components 5.2.*)` and `PHP 5.5.9`.

I initially installed `v0.8.2` and then read @simplenotezy 's comment.  

Downgraded and problem solved.

**Comment by barryvdh** [comment]
So 0.8.2 is broken, 0.8.1 works?

**Comment by tabirkeland** [comment]
@barryvdh I did not test `0.8.2` on Laravel/Lumen `5.3`

**Comment by rohan-deshpande** [comment]
Am on Laravel 5.3, just updated and yeah, not working for me either.  I'm on `0.8.2`

**Comment by pnkz19** [comment]
Using with `Laravel 5.3` + `Laravel Passport` and `laravel-cors v0.8.2` on `PHP 5.6.13`

If try adding `cors` to any middleware group its seem preflight options doesn't added the `Access-Control-Allow-Origin` to the headers.

So, I've tried adding `\Barryvdh\Cors\HandleCors::class` to the global middleware and everything works fine.

**Comment by RaphaelBadia** [comment]
Using ```Laravel 5.3``` + ```laravel-cors v0.8.2``` on ```PHP 7.0.8```

I get the error message: 
```
XMLHttpRequest cannot load http://mmorts.dev/api/v1/login. Response to preflight request doesn't pass access control check: The 'Access-Control-Allow-Origin' header contains multiple values '*, http://client.dev', but only one is allowed. Origin 'http://client.dev' is therefore not allowed access.
```

It works on PHP 5.6, though. **There is something wrong with PHP7**, I can't find out what.

**Comment by lsxiao** [comment]
Same problem. Lumen5.3 + laravel-cors v0.8.2

**Comment by lsxiao** [comment]
i solved it.my lumen api cause a  error.but there is no any error show in response.

**Comment by andreluizmorita** [comment]
Same problem. :/

**Comment by mycarrysun** [comment]
Getting the same error, Laravel 5.3.26 Laravel-cors 0.8.2
Also tried v0.8.1 but got the same error.
Anyone make any progress on this yet?

**Comment by spopov** [comment]
If someone override HandleCors class, you have to override Barryvdh\Cors\HandlePreflight also, because if you don't use HandleCors it skips OPTION request in HandlePreflight and returns nothing it why I got Access-Control-Allow-Origin as null

**Comment by ProgrammedMikey** [comment]
I get the same error, it works on localhost but not when i deploy it to production. Getting 
```
Response to preflight request doesn't pass access control check: No 'Access-Control-Allow-Origin' header is present on the requested resource
```

**Comment by spopov** [comment]
If you don't override HandleCors class, need to check any errors and also don't forget if you add cors headers if exaction happens in an exception handler.

**Comment by ProgrammedMikey** [comment]
yea its fixed, i just switched server to nginx on heroku, thanks working great

**Comment by TheGeekdu74** [comment]
I got this problem, and I tried everything that you said execpts overriding HandleCors (Dunno how to do it) and it doesn't works. Anybody have a concrete solution ?

**Comment by roman-klauser** [comment]
Not the best solution, especially NOT for production, but after few days of searching just happy that it works and I can move on.

put into index.php
header("Access-Control-Allow-Origin: {$_SERVER['HTTP_ORIGIN']}");
header('Access-Control-Allow-Headers: content-type');

PHP 7.0/Laravel 5.4

**Comment by cheanizer** [comment]
@sandervanhooft are your issue really solve. same here. if the response status are 2xx everything worked. but when it become 500,422 (laravel boilerplate send 422 for validation error). got cors error. I need catch the 422 data message when validation rejected from api. but now, it show null and when I see in the network tab (from inspect element), it show the message. 
using angular 1.5.9, laravel 5.2, cors 0.7.1. php 7

**Comment by sandervanhooft** [comment]
I don't know, I found the issue too confusing and moved to another stack

**Comment by axis80** [comment]
I was able to get this working under PHP 7.  In the end, my main problem was that the CSRF middleware was blocking the incoming requests since there was no CSRF token included with them.  I had to edit App/Http/Middleware/VerifyCsrfToken.php and add my URI endpoint to the list of routes that are excepted from CSRF verification.

**Comment by barryvdh** [comment]
Closing this as part of an issue-cleanup. Please re-open if this is still an issue on the latest version.

**Comment by varuntaliyan** [comment]
I am struggling with this error from last 2 days. 
I am using Laravel 5 (backend) with "barryvdh/laravel-cors": "0.7.x" and angularjs 1.4 (frontend).
Error message exactly same as @vitalibr . 
If anyone is able to resolve it, Please help

**Comment by varuntaliyan** [comment]
@minhlong : Can you please share how you manage to resolve this ?

**Comment by barryvdh** [comment]
Try the latest version

**Comment by varuntaliyan** [comment]
I tired installing the latest version but its not supported with laravel 5.1 and I cann't update the version of laravel

**Comment by barryvdh** [comment]
Yes it is. Otherwise please create a seperate issue.

**Comment by jcduenasr** [comment]
Laravel v5.4.15, cors v0.9.2.  php 5.6.25. It Doesn't Work...

**Comment by varuntaliyan** [comment]
I was using laravel 5.1, cors 0.7.x with angularjs 1.4 while getting this issue. But in the end it turns out that problem was due to completely different reasons. 
So, my advice to everyone getting the issue is to check laravel logs. Do NOT trust the error msgs on client side, those error messages can be misleading.

**Comment by jcduenasr** [comment]
In the laravel logs there aren't error msgs. Laravel v5.4.15, cors v0.9.2. php 5.6.25. It Doesn't Work.  : (

**Comment by barryvdh** [comment]
Please create a new issue with you exact configuration and steps you followed. And make sure you registered the Service Provider AND the middleware.
Try to debug if the middleware is hit and if so, why it's not returning the correct code, for example by adding logger() statements.

**Comment by ikyandhi** [comment]
I try to debug HandleCors, notice those OPTIONS / Pre-flight request doesn't hit the middleware.

**Comment by Rajukumar468** [comment]
I had same problem with PHP 7 /laravel 5.4
i solved using @roman-klauser  comments.

put into index.php
header("Access-Control-Allow-Origin: {$_SERVER['HTTP_ORIGIN']}");
header('Access-Control-Allow-Headers: content-type');

**Comment by gettosin4me** [comment]
I had the same problem

but solved it by 

set the cors in your api middleware like this

```
'api' => [
            'throttle:60,1',
            'bindings',
            'cors' =>[
                \Barryvdh\Cors\HandleCors::class,
            ]
        ],
```
Hope this solved the problem

And also, make sure all your endpoint are grouped with middleware. Unsecure endpoint can have an empty array as middleware, I was able to solve the problem that way

```
Route::group(['middleware' => []], function () {
     Route::post('/users', [
         'uses' => 'Controller@method'
    ])
});
```
Hope it help someone

**Comment by ghprod** [comment]
@gettosin4me not working for me, gave me this error

```
ErrorException: Illegal offset type in isset or empty

/vendor/laravel/framework/src/Illuminate/Routing/Router.php:722

```

**Comment by gettosin4me** [comment]
@ghprod use the code below, group the middleware with api
```
Route::group(['middleware' => ['api']], function () {
     Route::post('/users', [
         'uses' => 'Controller@method'
    ])
});
```

hope it works for u??

**Comment by ghprod** [comment]
@gettosin4me nope, maybe its because i'm using together with Dingo API?

The only way to make it works only by using it as global middleware ..

**Comment by gettosin4me** [comment]
```
$api = app('Dingo\Api\Routing\Router');

$api->version('v1', function ($api) {
    $api->group(['middleware' => []], function ($api) {
        $api->group(['middleware' => ['user.api.key']], function ($api) {
            
        });

    });
});
```

**Comment by ghprod** [comment]
Thanks @gettosin4me for your respond, really appreciate :+1:

**Comment by envision** [comment]
Same here, @gettosin4me solution did not work. Am on 5.4.

**Comment by allen-hxn** [comment]
Same here.i am on laravel5.4 dingapi laravel-cors 0.9 php7.0
i add 
```
 protected $middlewareGroups = [
        'web' => [
            \App\Http\Middleware\EncryptCookies::class,
            \Illuminate\Cookie\Middleware\AddQueuedCookiesToResponse::class,
            \Illuminate\Session\Middleware\StartSession::class,
            // \Illuminate\Session\Middleware\AuthenticateSession::class,
            \Illuminate\View\Middleware\ShareErrorsFromSession::class,
            \App\Http\Middleware\VerifyCsrfToken::class,
            \Illuminate\Routing\Middleware\SubstituteBindings::class,
        ],

        'api' => [
            'throttle:60,1',
            'bindings',
            \Barryvdh\Cors\HandleCors::class,
        ],
    ];

```
api.php
```
$api = app('Dingo\Api\Routing\Router');

$api->version('v1', function ($api) {

    $api->group(['namespace'=>'App\Http\Controllers\Api'], function ($api) {

        $api->post('login', 'Auth\LoginController@login');
......
```
cors middleware don't work.
do you solve this issue? @vitalibr @envision

**Comment by mycarrysun** [comment]
@allen-hxn For some reason I think the order matters in the array. Try:
`'api' => [
  '\Barryvdh\Cors\HandleCors::class,
  'throttle:60,1',
  'bindings'
]`

**Comment by rwngallego** [comment]
I had the same problem reported here and the solution was to change the order in the array that @mycarrysun mentioned. So I think the documentation should be updated to reflect this. Otherwise a lot of people will be shouting here for the same problem.

Originally, the doc says:

```
If you want to allow CORS on a specific middleware group or route, add the HandleCors middleware to your group:
protected $middlewareGroups = [
    'web' => [
       // ...
    ],

    'api' => [
        // ...
        \Barryvdh\Cors\HandleCors::class,
    ],
];
```

It should be:

```
    'api' => [
        \Barryvdh\Cors\HandleCors::class,
        // ...
    ],
```

**Comment by sharadjaiswal1411** [comment]
Great tutorial on Handling cors in Laravel 5.5 
[http://www.laravelinterviewquestions.com/2017/12/cross-origin-request-blocked-error-laravel.html](http://www.laravelinterviewquestions.com/2017/12/cross-origin-request-blocked-error-laravel.html)

**Comment by AfzalH** [comment]
I was having the same error while uploading larger images. 

The error message on browser console was a bit misleading, it was showing `No 'Access-Control-Allow-Origin' header is present` with a status code 500. I was looking into the cors related things because of that error message but actually I had to look into the server error log (laravel.log was empty as well in my case).

After looking into nginx error log, I found out php was out of memory while processing the image using Intervention/Image

So if it's `No 'Access-Control-Allow-Origin` with 500 status code, take a look into your server's error log files (or laravel.log). Otherwise just putting the middleware in the correct position should work (as suggested by others)

**Comment by salipro4ever** [comment]
Can you try my solutions, they are working for me (laravel 5.5)

Solution 1. Init Cors middleware on global HTTP middleware in `Kernel.php`
Solution 2. Still init api group middleware `$middlewareGroups['api']`, must add more options request in route `routes/api.php`. (for me)
```php
Route::options('{any?}', function (){
    return response('',200);
})->where('any', '.*');
```
Guk luk!

**Comment by jsims9817** [comment]
I was still getting a 500 error when trying to configure laravel-cors on Laravel 5.6.  My solution...
run _composer require barryvdh/laravel-cors_
in /app/Kernel.php add _\Barryvdh\Cors\HandleCors::class,_ to **protected $middleware** 
Run _php artisan vendor:publish --provider="Barryvdh\Cors\ServiceProvider"_

Don't do anything else... Adding it to the **protected $middlewareGroups** section was giving me 500 errors.

**Comment by riteshjha** [comment]
thanks @goeroeku saved my day

**Comment by josepedrodiaz** [comment]
I was having a similar issue, but the cause was not this module, the cause was  api controller route was returning an error 500, after solved the issue on the controller (on my case a misconfiguration of database connection settings) CORS error disappear.
