### ISSUE TITLE
Works locally but not from other machines

### ISSUE THREAD

**Issue by scossgrove** [barryvdh/laravel-cors#131]
Hi,

I am getting the following response when trying to log into the site

OPTIONS http://work.com/api/v1/authenicate 
XMLHttpRequest cannot load http://work.com/api/v1/authenicate. Response to preflight request doesn't pass access control check: No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'http://192.168.1.3' is therefore not allowed access. The response had HTTP status code 501.

After doing a fair bit of trial and error via googling I really would like some advice/help with this.

Thanks in advance.

System:
I am running laravel 5.2 with laravel-cors 0.8.2 on  Ubuntu 16.04 with IP Address 192.168.1.3

Successful from 192.168.1.3 (Server):
http://work.com 
http://localhost

Unsuccessful from 192.168.1.5:
http://192.168.1.3

Headers:
- General
  Request URL:http://work.com/api/v1/authenicate
  Request Method:OPTIONS
  Status Code:501 Not Implemented
  Remote Address:xxx.xxx.xxx.xxx:80
  -Response Headers
  Accept-Ranges:none
  Connection:close
  Content-Type:text/html
  Date:Thu, 01 Sep 2016 12:55:32 GMT
  Last-Modified:Thu, 01 Sep 2016 12:55:32 GMT
  Server:UltraDNS Client Redirection Server
  -Request Headers
  Accept:_/_
  Accept-Encoding:gzip, deflate, sdch
  Accept-Language:en-GB,en-US;q=0.8,en;q=0.6
  Access-Control-Request-Headers:content-type
  Access-Control-Request-Method:POST
  Connection:keep-alive
  Host:work.com
  Origin:http://192.168.1.3
  Referer:http://192.168.1.3/
  User-Agent:Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/52.0.2743.116 Safari/537.36

app.php:
'providers' => [
  // standard laravel Framework Serivce Provides
  ....
  // CORS Provider
  Barryvdh\Cors\ServiceProvider::class
]

config/cors.php:
  return array(
     'defaults' => array(
       'suppoertsCredentials' => false,
        'allowedOrigins' => array(),
        'allowedHeaders' => array(),
        'allowedMethods' => array(),
        'exposedHeaders' => array(),
        'maxAge' => 3600,
        'hosts' => array()
     ),
     'paths' => array(
        '_' => array(
              'allowedOrigins' => array('_'),
              'allowedHeaders' => array('_'),
              'allowedMethods' => array('_'),
              'maxAge' => 3600  
        ),
    ),
  );
);

**Comment by barryvdh** [comment]
Closing this as part of an issue-cleanup. Please re-open if this is still an issue on the latest version.
