### ISSUE TITLE
Error Cors Laravel 5.3 y Angular 1.5.8

### ISSUE THREAD

**Issue by ARCHAMO** [barryvdh/laravel-cors#133]
Good morning , I made the implementation of your package properly but when performing the POST request response I get an 200 ok with message ( reason : missing CORS ' Access- Control- Allow- Origin ' header). And it does not show me the JSON 'replies to be sent by the server when I check in MySQL the record is saved correctly. I 'm using laravel 5.3 to 1.5.8 API and angular in the frontend . That may be happening . How can I solve that. Typically, the response is a JSON { " message": " Record saved successfully "}
![error](https://cloud.githubusercontent.com/assets/12633358/18513269/74ecaac6-7a52-11e6-9e6e-61b9ad45f9bd.JPG)

**Comment by prasadrajandran** [comment]
Are you using version 0.8.2? I'm on Laravel 5.1 and downgrading laravel-cors to v0.8.1 worked for me.

**Comment by andreluizmorita** [comment]
Same problem

**Comment by barryvdh** [comment]
Closing this as part of an issue-cleanup. Please re-open if this is still an issue on the latest version.
