### ISSUE TITLE
Allow CORS from users who have signed up

### ISSUE THREAD

**Issue by audunru** [barryvdh/laravel-cors#136]
Working on an app where users can sign up, add a domain to their account and then do CORS requests to my app from that domain. This is a work in progress, but would I be correct in doing something like this?

I've added the cors middleware to my controller, and my idea is to check in my store() method if the origin matches the site.

The controller:

```
FeedbackApiController extends Controller
{
    public function __construct()
    {
        $this->middleware('cors');
    }
    public function store(Site $site, Request $request)
    {
        // TODO: Check if request origin matches site domain here

        $feedback = new Feedback([
            'vote' => $request->fields['vote'],
            'comment' => $request->fields['comment'],
            'url' => $request->fields['url']
        ]);

        $site->feedbacks()->save($feedback);

    }
}
```

**Comment by barryvdh** [comment]
You should put it on the middleware list in your Kernel probably..  Please try with the latest.
