### ISSUE TITLE
laravel-cors includes the asm89 cors middleware when it shouldn't

### ISSUE THREAD

**Issue by aleciten** [barryvdh/laravel-cors#137]
This is happening on the 0.2.x branch (Laravel 4.2).

As long as the request contains the "Origin" header, the asm89/cors-stack middleware will be added to the app with unintended consequences if you only want to have it active for a specific path.
This seems to contradict the documentation where it's understood it will only apply to specific, configurable paths.

Would love to submit a PR to address this.

**Comment by aleciten** [comment]
#138

**Comment by barryvdh** [comment]
What are the consequences?

**Comment by aleciten** [comment]
The difference is that before this, for any requested route, even those that didn't match the "paths" config, would get the asm89 middleware added to the app chain.
With this, the application behaves as this plugin didn't exist if the request route doesn't match which is what one understand should happen reading the docs.

**Comment by aleciten** [comment]
Ah, I'm sorry, I misunderstood your question.

The unintended consequence for me was that, per the config defaults of absolute restriction, I was getting a "Forbidden" response for a request path that didn't match any of the paths configured for laravel-cors.

Let me try to clarify:

First, my laravel-cors config:
```
array(
    'defaults' => array(
        'supportsCredentials' => false,
        'allowedOrigins' => [],
        'allowedHeaders' => [],
        'allowedMethods' => [],
        'exposedHeaders' => [],
        'maxAge' => 0,
        'hosts' => [],
    ),
    'paths' => array(
        'api/*' => array(
            'allowedOrigins' => ['*'],
            'allowedHeaders' => ['x-api-key', 'x-user-token'],
            'allowedMethods' => ['GET', 'POST', 'PUT', 'DELETE'],
            'supportsCredentials' => true,
            'maxAge' => 3600
        )
    )
);
```

One would think that a URL such as www.server.com/auth/login would have it's response be untouched, working the same as if laravel-cors wasn't installed.

But what happens is that Chrome includes the Origin header on all requests. And that is the only requisite for laravel-cors to include the asm89 middleware in the chain with it's options set to those "blank" defaults.

That makes the response come out as forbidden, when before it was returning 200.

Without laravel-cors:
```
curl -v -XOPTIONS -H "Origin: www.test.local" https://www.test.local/auth/login

> OPTIONS /auth/login HTTP/1.1
> Host: www.test.local
> User-Agent: curl/7.43.0
> Accept: */*
> Origin: www.test.local
>
< HTTP/1.1 200 OK
```

With laravel-cors:
```
curl -v -XOPTIONS -H "Origin: www.test.local" https://www.test.local/auth/login

> OPTIONS /auth/login HTTP/1.1
> Host: www.test.local
> User-Agent: curl/7.43.0
> Accept: */*
> Origin: www.test.local
>
< HTTP/1.1 403 Forbidden
```

**Comment by aleciten** [comment]
As an extra test, changing the defaults to the following results in a 200 response:
```
    'defaults' => array(
        'supportsCredentials' => false,
        'allowedOrigins' => ['*'],
        'allowedHeaders' => [],
        'allowedMethods' => [],
        'exposedHeaders' => [],
        'maxAge' => 0,
        'hosts' => [],
    )
```

**Comment by barryvdh** [comment]
Closing this as part of an issue-cleanup. Please re-open if this is still an issue on the latest version.
