### ISSUE TITLE
allow a list of domains to use the api

### ISSUE THREAD

**Issue by karunkshrestha** [barryvdh/laravel-cors#14]
Hi,

I want to allow a list of trusted domains to use the api. My first thought was to use the 'hosts' config to list the domains in an array. This didn't work. I also tried putting it in the 'allowedOrigins' array , same result.

```
'paths' => array(
        'v1/*' => array(
            'allowedOrigins' => array('*'),
            'allowedHeaders' => array('authorization','x-requested-with','apiKey','Content-Type'),
            'allowedMethods' => array('POST', 'PUT', 'GET', 'DELETE'),
            'maxAge' => 3600,
            'hosts' => array('abc.com','mytrustedweb.org'),
        ),

    ),
```

Is this possible with the new config file?

**Comment by eullercristian** [comment]
@barryvdh  how the rigth way for configure the parameter 'allowedOrigins' => ['*'], for allowed domain and subdomains? I tried 'allowedOrigins' => ['*.domain.com.br'] but its dont works. Thanks
