### ISSUE TITLE
 No 'Access-Control-Allow-Origin' header - laravel 4.2 

### ISSUE THREAD

**Issue by m2025** [barryvdh/laravel-cors#140]
Hi! I am trying to get and post data from a website for another website with angular 1 ! but that not working on another website with http request! plz help me! thanks my code is as follows:

> all:
>function(page){
>return $http.get('http://www.example.com/api/v1/blogs/?page=' + page);
>},

 

and in route :
>Route::group(['prefix' => 'api/v1/'], function()
>{
>Route::get('/blogs', 'BlogsController@index');
>.....
>}
i want a website have access to another website data with api my laravel version is 4.2
error:
> XMLHttpRequest cannot load http://www.example.com/api/v1/blogs/?page=1&perPage=7. No >'Access-Control-Allow-Origin' header is present on the requested resource. Origin >'http://www.website2.com' is therefore not allowed access.`

i install CORS from this link with this config :

<?php

return array(

   /*
    |--------------------------------------------------------------------------
    | Laravel CORS Defaults
    |--------------------------------------------------------------------------
    |
    | The defaults are the default values applied to all the paths that match,
    | unless overridden in a specific URL configuration.
    | If you want them to apply to everything, you must define a path with *.
    |
    | allowedOrigins, allowedHeaders and allowedMethods can be set to array('*') 
    | to accept any value, the allowed methods however have to be explicitly listed.
    |
    */
   'defaults' => array(
       'supportsCredentials' => true,
        'allowedOrigins' => array('*'),
        'allowedHeaders' => array('*'),
       'allowedMethods' => array('*'),
        'exposedHeaders' => array('*'),
       'maxAge' => 3600,
       'hosts' => array('*'),
   ),

   'paths' => array(
      'api/*' => array(
           'allowedOrigins' => array('*'),
          'allowedHeaders' => array('*'),
          'allowedMethods' => array('*'),
         'maxAge' => 3600,
      ),
     '*' => array(
        'allowedOrigins' => array('*'),
        'allowedHeaders' => array('Content-Type'),
        'allowedMethods' => array('POST', 'PUT', 'GET', 'DELETE'),
         'maxAge' => 3600,
        'hosts' => array('*'),
     ),
  ),

);

filtes.php
>App::before(function($request)
>{
>    header('Access-Control-Allow-Origin: *');
 >   header('Access-Control-Allow-Methods: GET, POST, OPTIONS');
 >   header('Access-Control-Allow-Headers: Origin, Content-Type, Accept, Authorization, 
>X-Request-With');
 >   header('Access-Control-Allow-Credentials: true');

>});

>App::after(function($request, $response)
>{
 >   $response->headers->set('Access-Control-Allow-Origin', '*');
>    $response->headers->set('Allow', 'GET, POST, OPTIONS');
>    $response->headers->set('Access-Control-Allow-Headers', 'Origin, Content-Type, Accept, >Authorization, X-Requested-With');
>    $response->headers->set('Access-Control-Allow-Credentials', 'true');
>    return $response;
>});

but that not working
plz help me

**Comment by barryvdh** [comment]
Try to allow all headers?

**Comment by m2025** [comment]
To allow all the headers What should I do?

**Comment by m2025** [comment]
plz help me

**Comment by m2025** [comment]
i found 2 error :

Font from origin 'http://www.example.com' has been blocked from loading by Cross-Origin Resource Sharing policy: No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'http://android' is therefore not allowed access.

(index):1 XMLHttpRequest cannot load http://www.example.com/api/v1/blogs/?page=1&perPage=20. No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'http://www.website2.com' is therefore not allowed access.
