### ISSUE TITLE
supportsCredentials issues

### ISSUE THREAD

**Issue by mitsest** [barryvdh/laravel-cors#144]
Hey there,
thanks for your plugin!

I 'm trying to use it, in order to allow CORS requests between a client(https://something.app) and an API(https://api1.something.com).
While GET and POST requests work, I 'm now trying to make Authentication work between the client and the API. I thought I was on a dead end when I read that there is no cookie sharing with CORS. But then I noticed supportsCredentials flag inside the cors config and thought I should try it.

Unfortunately I 'm getting the error 

> XMLHttpRequest cannot load https://api1.something.com/v0/customer/phone. A wildcard '*' cannot be used in the 'Access-Control-Allow-Origin' header when the credentials flag is true. Origin 'https://something.app' is therefore not allowed access. The credentials mode of an XMLHttpRequest is controlled by the withCredentials attribute.

But the thing is, I don't have a wildcard for allowedOrigins!

My config/cors.php is:
```php
    'supportsCredentials' => true,
    'allowedOrigins' => ["https://something.app", "https://www1.something.com"],
    'allowedHeaders' => ['*'],
    'allowedMethods' => ['GET', 'POST', 'PUT',  'DELETE'],
    'exposedHeaders' => [],
    'maxAge' => 0,
    'hosts' => []
```

I tried clearing caches and resubmitting the conf through the vendor:publish command, but no luck :/
Am I missing something?
Thanks for your time!

**Comment by mitsest** [comment]
My bad.
I guess I should always check apache configuration before opening a new issue.

Sorry!

**Comment by molerat619** [comment]
@mitsest  what was the problem with your apache configuration? I'm facing similar issues and can't track the problem down.

**Comment by mitsest** [comment]
@molerat619 can't remember, sorry.  Maybe, CORS was disabled on the apache side (Header set Access-Control-Allow-Origin "*")?
