### ISSUE TITLE
302 redirect when using Laravel's Form Request Validation

### ISSUE THREAD

**Issue by karlpatrickespiritu** [barryvdh/laravel-cors#148]
Whenever I typehint a request validation in controller function like so:

``` php
/**
 * Store a newly created resource in storage.
*
 * @param StoreStaffEventLog|Request $request
* @return \Illuminate\Http\Response
 */
public function store(StoreStaffEventLog $request)
{
    if (!$this->eventStaffRepository->find($request->staff_event_id)) return $this->respondBadRequest();

    $this->eventStaffLogRepository->create([
         'staff_event_id' => $request->staff_event_id,
         'type' => $request->type,
    ]);

     return $this->respondCreated();
}
```

I'll get a 302 response redirect. See JS response below:

```
XMLHttpRequest cannot load http://company-site.com/api/1.0/staff/logs. Redirect from
'http://company-site.com/api/1.0/staff/logs' to 'http://localhost:8100/' has been blocked 
by CORS policy: Request requires preflight, which is disallowed to follow cross-origin redirect.
```

But if I replace the `StoreStaffEventLog $request` to `Request $request`. My request works fine and returns me a `201 Created` status code.

**Comment by Tyldar** [comment]
I confirm, i've that issue too.

Using a custom request handler fail :

`public function login(Requests\UserLogin $request)`

But when using this it works : 

`public function login(Request $request)`

Please fix this @barryvdh

**Comment by ibnujakaria** [comment]
i have the same problem with laravel 5.2 when using form request validation

**Comment by Petronetto** [comment]
Put this code in your form request:
```php
    /**
     * Get the proper failed validation response for the request.
     *
     * @param  array  $errors
     * @return \Symfony\Component\HttpFoundation\Response
     */
    public function response(array $errors)
    {
        //This will always return JSON object error messages
        return new JsonResponse($errors, 422);
    }
```

**Comment by barryvdh** [comment]
Closing this as part of an issue-cleanup. Please re-open if this is still an issue on the latest version.

**Comment by NoelDavies** [comment]
I have the same issue, running 5.5.28

**Comment by simplyrupin** [comment]
Yes, agree with @NoelDavies the issue has returned when using Laravel 5.5.28

**Comment by yunmoxue** [comment]
laravel 5.5
i put the the header solve the problem.
`'X-Requested-With': 'XMLHttpRequest'`

laravel will return json when found this header.

actual, there are two method return json.
in file vendor/laravel/framework/src/Illuminate/Http/Concerns/InteractsWithContentTypes.php::42
`    public function expectsJson()
    {
        return ($this->ajax() && ! $this->pjax()) || $this->wantsJson();
    }
`
the `wantsJson` judges the request header whether exists `X-Requested-With` and equal `XMLHttpRequest`

**Comment by charj** [comment]
Same issue persists with me today, ` "laravel/framework": "5.8.*"`

@yunmoxue's suggestion to add a header resolved my issue

**Comment by lbrevity** [comment]
Hi
I have same issue .. I use form post not ajax call. so where i add X-Requested-With?

**Comment by amadoutidiane** [comment]
i need to know where put it @yunmoxue  or  @charj  'X-Requested-With': 'XMLHttpRequest'

**Comment by yunmoxue** [comment]
@lbrevity @amadoutidiane you can add request header when you use xhr.
there is api.
https://developer.mozilla.org/en-US/docs/Web/API/XMLHttpRequest/setRequestHeader

**Comment by amadoutidiane** [comment]
@yunmoxue  and @charj  i'am new ate dev and i need you write all the code of ajax request and tell who i exactly put 'X-Requested-With': 'XMLHttpRequest' in the code thx for help

**Comment by charj** [comment]
@amadoutidiane Email me. dev@charlie.fyi

**Comment by charj** [comment]
An example of adding the header to a jQuery Ajax for @amadoutidiane.

Thought I'd share the solution for others here 🙂

```
$.ajax({
  type: "POST",
  beforeSend: function(request) {
    request.setRequestHeader("X-Requested-With", "XMLHttpRequest");
  }
});
```

**Comment by jacobsmith** [comment]
At least in Laravel 6.0, setting a request header of `Accept: application/json` will also trigger a JSON response (without needing to set the `X-Requested-With` header).

**Comment by jnnbnflr** [comment]
This solves the problem for me:
   Insert       Accept: application/json in ajax header

  $.ajax({
                    url:'{{route('fetchMunCit')}}' +'/'+id,
                    type:'GET',
                    dataType:'json',
                    Accept: application/json
                        success:function(response)

**Comment by maxcotech** [comment]
Adding Accept: application/json did not solve it for me
