### ISSUE TITLE
No 'Access-Control-Allow-Origin' header is present on the requested resource

### ISSUE THREAD

**Issue by karunkshrestha** [barryvdh/laravel-cors#15]
after updating laravel-cors to 0.2 , I have started getting 
No 'Access-Control-Allow-Origin' header is present on the requested resource in chrome.
![image](https://cloud.githubusercontent.com/assets/5154097/3201464/0a372430-ed88-11e3-975e-8322bc5ac6df.png)

**Comment by johnrcui** [comment]
I'm having the same issue. I have a dev environment that's working well but when i clone or even just copy directly to another directory and use a different server name (ie. dev.domain.com and api.domain.com), only the dev environment works. Both installs are running on the same amazon linux machine with nginx web server and my config files for each is identical except for the root directory and server name.

After trying out whatever I can figure out and reading other people's comments here, I had a hunch it might have something to do with the domain name. So I changed my clone environment's server name to the same as the dev's and just changed the port number to distinguish it from each other and lo and behold everything now works on the clone.

I'm not sure if it's something cached on the browser (I didn't try clearing cache during the failures) or maybe related to cookies or maybe the middleware is storing something globally that's tied to the first installation's server name that's overriding the settings on the second installation, but putting the two environments under the same server name worked.

**Comment by rohan-deshpande** [comment]
Hi guys, I was getting this error constantly as well, then I disabled the CSRF middleware and it worked. The error I kept getting was a token mismatch exception, keep in mind that I was using the csrf-token meta tag with the `$.ajaxSetup` solution and all ajax calls were working fine before I went API based and split my app up into two domains. Not sure if this is the cause of everyone else's issues but it was definitely the cause of mine.

**Comment by FoxxMD** [comment]
:+1: This error only occurs for me when a client is making pre-flight requests. The response header for the OPTIONS request does not include `access-control-allow-origin`. Making requests without pre-flight works fine. Using the default config.

**Comment by eporral1** [comment]
Hi @barryvdh this is the issue I'm experiencing:

if my routes have an internal error, I receive:

XMLHttpRequest cannot load http://localhost:8000/signin. No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'http://localhost:8001' is therefore not allowed access. The response had HTTP status code 500.

For instance: If I turn off my MySql DB I receive that error, instead of  "invalid connection to db" or something like that, when I trying to login.

Im using version "0.4.x@dev" and my settings are:

 'defaults' => array(
        'supportsCredentials' => false,
        'allowedOrigins' => array('*'),// default ()
        'allowedHeaders' => array('*'),// default ()
        'allowedMethods' => array('*'),// default ()
        'exposedHeaders' => array('*'),// default ()
        'maxAge' => 0,
        'hosts' => array(),
    ),

Any Idea?
thankssss

**Comment by behzadsh** [comment]
I didn't read comments, but I had exact problem, and fix it by running `composer update`

**Comment by djoks** [comment]
I had the same issue and you know what was even stranger? It just happened like that all of a sudden, still have no idea what caused it and the even weirder thing was that it worked on some devices and didn't work on other devices, so i installed cors, but that didn't do anything, so i removed it and just addd the necessary code to my .htaccess file now it works just fine. :)

**Comment by mtpultz** [comment]
@eporral1 did you ever get this resolved?  I'm having the same issue for this config:

```
'supportsCredentials' => false,
'allowedOrigins' => ['*'],
'allowedHeaders' => ['*'],
'allowedMethods' => ['*'],
'exposedHeaders' => [],
'maxAge' => 0,
'hosts' => [],
```

On top of that I'm getting this in my log file:

```
[2016-02-24 07:57:53] local.ERROR: Symfony\Component\Debug\Exception\FatalThrowableError: Type error: Argument 1 passed to Barryvdh\Cors\Stack\CorsService::addActualRequestHeaders() must be an instance of Symfony\Component\HttpFoundation\Response, array given, called in /home/vagrant/app/vendor/barryvdh/laravel-cors/src/HandleCors.php on line 44 in /home/vagrant/app/vendor/barryvdh/laravel-cors/src/Stack/CorsService.php:69
Stack trace:
#0 /home/vagrant/app/vendor/barryvdh/laravel-cors/src/HandleCors.php(44): Barryvdh\Cors\Stack\CorsService->addActualRequestHeaders(Array, Object(Illuminate\Http\Request))
#1 [internal function]: Barryvdh\Cors\HandleCors->handle(Object(Illuminate\Http\Request), Object(Closure))
#2 /home/vagrant/app/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(124): call_user_func_array(Array, Array)
#3 [internal function]: Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#4 /home/vagrant/app/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(32): call_user_func(Object(Closure), Object(Illuminate\Http\Request))
#5 [internal function]: Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#6 /home/vagrant/app/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(102): call_user_func(Object(Closure), Object(Illuminate\Http\Request))
#7 /home/vagrant/app/vendor/laravel/framework/src/Illuminate/Routing/Router.php(726): Illuminate\Pipeline\Pipeline->then(Object(Closure))
#8 /home/vagrant/app/vendor/laravel/framework/src/Illuminate/Routing/Router.php(699): Illuminate\Routing\Router->runRouteWithinStack(Object(Illuminate\Routing\Route), Object(Illuminate\Http\Request))
#9 /home/vagrant/app/vendor/laravel/framework/src/Illuminate/Routing/Router.php(675): Illuminate\Routing\Router->dispatchToRoute(Object(Illuminate\Http\Request))
#10 /home/vagrant/app/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(246): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request))
#11 [internal function]: Illuminate\Foundation\Http\Kernel->Illuminate\Foundation\Http\{closure}(Object(Illuminate\Http\Request))
#12 /home/vagrant/app/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(52): call_user_func(Object(Closure), Object(Illuminate\Http\Request))
#13 /home/vagrant/app/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/CheckForMaintenanceMode.php(44): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#14 [internal function]: Illuminate\Foundation\Http\Middleware\CheckForMaintenanceMode->handle(Object(Illuminate\Http\Request), Object(Closure))
#15 /home/vagrant/app/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(124): call_user_func_array(Array, Array)
#16 [internal function]: Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#17 /home/vagrant/app/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(32): call_user_func(Object(Closure), Object(Illuminate\Http\Request))
#18 [internal function]: Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#19 /home/vagrant/app/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(102): call_user_func(Object(Closure), Object(Illuminate\Http\Request))
#20 /home/vagrant/app/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(132): Illuminate\Pipeline\Pipeline->then(Object(Closure))
#21 /home/vagrant/app/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(99): Illuminate\Foundation\Http\Kernel->sendRequestThroughRouter(Object(Illuminate\Http\Request))
#22 /home/vagrant/app/public/index.php(53): Illuminate\Foundation\Http\Kernel->handle(Object(Illuminate\Http\Request))
#23 {main}  
```

**Comment by shanecp** [comment]
If you're using this package in Chrome + localhost, it won't work. This is a bug/feature in Chrome - http://stackoverflow.com/questions/10883211/deadly-cors-when-http-localhost-is-the-origin

**Comment by rochapablo** [comment]
+1

**Comment by ganpat-tekhne** [comment]
@barryvdh  I am using laravel 5.3 with cors it was working good for me up till now but now i tried creating some more apis and those are not working and are giving cors error 
should not it be the case tht if the cors works for one should work for all if its set globally in the kernal file?

**Comment by dees040** [comment]
I upgraded from Laravel 5.4 to 5.5. In Postman all requests where working. But in my VueJS application all requests where failing with the error of this issue. But in Laravel 5.4 everything was working perfectly. I'm not sure if my issue had to do with L5.5 or that I might did something wrong with the upgrade, but moving the `HandleCors` from the `api` middleware group to the global middleware group fixed the issue.

**Comment by tangrianand** [comment]
Hi Guys,

I am facing  similar error. I am using Amazon AWS and route 53.  I changed my domain name from 'api.temphawk.com' to 'api.temphawk.com/core' and now every api works fine except one 'api.temphawk.com/core/alert/history'.
It gives the following error in chrome.
![image](https://user-images.githubusercontent.com/14893415/30579906-49cfe286-9d38-11e7-88c5-d9eea1ff3fa1.png)
 And this error in mozilla. 
![image](https://user-images.githubusercontent.com/14893415/30579940-74742d8a-9d38-11e7-9ab0-c37de66eb7fc.png)

Could anyone please help. This api works fine when I open it on Postman though.

**Comment by JaviLopezM** [comment]
I only put this line at the top of routes files

header('Access-Control-Allow-Origin: *');

and works.

**Comment by sharadjaiswal1411** [comment]
Check this Tutorial for Laravel
http://www.laravelinterviewquestions.com/2017/12/cross-origin-request-blocked-error-laravel.html

**Comment by gregorskii** [comment]
Can this ticket be closed out? :) Been open a LOOONNGGG time.

This library works, it just needs to be configured correctly, and the user has to understand that any error in the backend will stop the middleware from responding with a CORS token, which will cause the browser to indicate that there is an error with CORS, when there is actually not.

There are two things that can be done to mitigate this:

* Documentation
* Returning a CORS token even on 500 errors from the API, which the user could technically do in a error middleware, or as a PR to this package

😸

**Comment by barryvdh** [comment]
Well, the readme does say that, on the 'known problems' part..
