### ISSUE TITLE
Laravel 5.3 Preflight works but not the second request

### ISSUE THREAD

**Issue by asivaneswaran** [barryvdh/laravel-cors#150]
I installed the package and I am running into an issue. I am using angularJs that sends a Post method with application/json Content-type which generates a CORS preflight. The preflight works fine and returns true. The actual request is sent and that's when I get 'XMLHttpRequest cannot load' error.

This is my cors.php settings file:

    'supportsCredentials' => false,
    'allowedOrigins' => [env('UI_URL')],
    'allowedHeaders' => ['Origin', 'Content-Type', 'Accept', 'Authorization'],
    'allowedMethods' => ['GET', 'POST', 'PUT', 'DELETE', 'OPTIONS'],
    'exposedHeaders' => [],
    'maxAge' => 0,
    'hosts' => [],

And in my Kernel:
'api' => [
            'throttle:60,1',
            'bindings',
            \Barryvdh\Cors\HandleCors::class,
        ],

Thanks,
Ara

**Comment by barryvdh** [comment]
What was the problem?

**Comment by asivaneswaran** [comment]
I was accessing the wrong routes -.-
