### ISSUE TITLE
Laravel-cors not working in laravel 5.2

### ISSUE THREAD

**Issue by jision** [barryvdh/laravel-cors#155]
I have tried every possible answer i can find on google but No hope.I get the error  Request header field Access-Control-Allow-Origin is not allowed by Access-Control-Allow-Headers in preflight response.

I created my own Cors middleware use the library of yours but still no luck .I have a angular frontend that calls up a laravel controller which echoes out data in json what am is missing ??

**Comment by llab-studio** [comment]
I have the same problem.

**Comment by toocool** [comment]
me too

**Comment by iolson** [comment]
Same here, need help. It works randomly on some of my API endpoints, but not all of them. They are all under the same route group.

**Comment by sevmardi** [comment]
+1 me too the same problem!

**Comment by jision** [comment]
The only way i solved it was to edit the .htacess in public folder
Header always set Access-Control-Allow-Origin "*"
Header always set Access-Control-Allow-Methods "POST, GET, OPTIONS, DELETE, PUT"
Header always set Access-Control-Allow-Headers "x-requested-with, Content-Type, origin, authorization, accept, client-security-token , Access-Control-Allow-Headers"

Its working 
perfectly

**Comment by sevmardi** [comment]
@jision Can you show a sample of you .htaccess. 

If I put what you said in my .htaccess the app knocks itself out. I receive Internal server error 500. 

Thanks for your time.

**Comment by jision** [comment]
<IfModule mod_rewrite.c>
    <IfModule mod_negotiation.c>
        Options -MultiViews
    </IfModule>

    RewriteEngine On

    # Redirect Trailing Slashes...
    RewriteRule ^(.*)/$ /$1 [L,R=301]

    # Handle Front Controller...
    RewriteCond %{REQUEST_FILENAME} !-d
    RewriteCond %{REQUEST_FILENAME} !-f
    RewriteRule ^ index.php [L]
</IfModule>
php_value upload_max_filesize 40M
php_value post_max_size 40M
Header always set Access-Control-Allow-Origin "*"
Header always set Access-Control-Allow-Methods "POST, GET, OPTIONS, DELETE, PUT"
Header always set Access-Control-Allow-Headers "x-requested-with, Content-Type, origin, authorization, accept, client-security-token , Access-Control-Allow-Headers"




this is my .htaccess  file feel free to ask anything if required

**Comment by sevmardi** [comment]
@jision  Thanks! I will give this another try and get back to you.

**Comment by apoca** [comment]
Do you have solution for nginx ?

**Comment by jision** [comment]
location / {
     if ($request_method = 'OPTIONS') {
        add_header 'Access-Control-Allow-Origin' '*';
        #
        # Om nom nom cookies
        #
        add_header 'Access-Control-Allow-Credentials' 'true';
        add_header 'Access-Control-Allow-Methods' 'GET, POST, OPTIONS';
        #
        # Custom headers and headers various browsers *should* be OK with but aren't
        #
        add_header 'Access-Control-Allow-Headers' 'DNT,X-CustomHeader,Keep-Alive,User-Agent,X-Requested-With,If-Modified-Since,Cache-Control,Content-Type';
        #
        # Tell client that this pre-flight info is valid for 20 days
        #
        add_header 'Access-Control-Max-Age' 1728000;
        add_header 'Content-Type' 'text/plain charset=UTF-8';
        add_header 'Content-Length' 0;
        return 204;
     }
     if ($request_method = 'POST') {
        add_header 'Access-Control-Allow-Origin' '*';
        add_header 'Access-Control-Allow-Credentials' 'true';
        add_header 'Access-Control-Allow-Methods' 'GET, POST, OPTIONS';
        add_header 'Access-Control-Allow-Headers' 'DNT,X-CustomHeader,Keep-Alive,User-Agent,X-Requested-With,If-Modified-Since,Cache-Control,Content-Type';
     }
     if ($request_method = 'GET') {
        add_header 'Access-Control-Allow-Origin' '*';
        add_header 'Access-Control-Allow-Credentials' 'true';
        add_header 'Access-Control-Allow-Methods' 'GET, POST, OPTIONS';
        add_header 'Access-Control-Allow-Headers' 'DNT,X-CustomHeader,Keep-Alive,User-Agent,X-Requested-With,If-Modified-Since,Cache-Control,Content-Type';
     }
}

source https://michielkalkman.com/snippets/nginx-cors-open-configuration.html

**Comment by barryvdh** [comment]
Closing this as part of an issue-cleanup. Please re-open if this is still an issue on the latest version.
