### ISSUE TITLE
CORS headers not set on DELETE pre-flight

### ISSUE THREAD

**Issue by asivaneswaran** [barryvdh/laravel-cors#156]
Hi,

I have setup the package and it worked fine so far with GET, POST and PUT requests but it doesn't seem to work with DELETE method.

Here is my cors config file:

```
return [
    /*
     |--------------------------------------------------------------------------
     | Laravel CORS
     |--------------------------------------------------------------------------
     |

     | allowedOrigins, allowedHeaders and allowedMethods can be set to array('*')
     | to accept any value.
     |
     */
    'supportsCredentials' => false,
    'allowedOrigins' => [env('UI_URL')],
    'allowedHeaders' => ['Origin', 'Content-Type', 'Accept', 'Authorization'],
    'allowedMethods' => ['GET', 'POST', 'PUT', 'DELETE', 'OPTIONS'],
    'exposedHeaders' => [],
    'maxAge' => 0,
    'hosts' => [],
];
```

I put this in my Kernel:

```
'api' => [
			'throttle:60,1',
			'bindings',
			\Barryvdh\Cors\HandleCors::class,
		],
```

Like I said, the other requests work. Actually, even the pre-flight gets a 200 status but I don't see the allowed origins header in the response tho.

Thanks,

**Comment by barryvdh** [comment]
So you fixed this by allowing more headers, right? Did you notice any other headers being sent?

**Comment by asivaneswaran** [comment]
If I am right, when I am sending $http.delete() the Access-Control-Request-Headers is empty. So I am guessing, might have to allow that?

**Comment by barryvdh** [comment]
Closing this as part of an issue-cleanup. Please re-open if this is still an issue on the latest version.
