### ISSUE TITLE
Requests to Lumen come back 200 but with 'No 'Access-Control-Allow-Origin' header'

### ISSUE THREAD

**Issue by rohitsodhia** [barryvdh/laravel-cors#160]
I'm not sure if I just don't understand CORS well enough, but I'm trying to build an API with Lumen, and while I was able to get this package working in Laravel, I can't tell if it's the package or me for this:

I make a request (GET or POST) to an endpoint on Lumen and I always get back a response as expected, but I also get a console error saying `No 'Access-Control-Allow-Origin' header is present on the requested resource.`. I've tried debugging, and it's hitting the LumenServiceProvider, so I'm a bit baffled.

Is this expected behavior? I'm on Lumen 5.3.3, laravel-cors latest version. I've tried both * for allowedOrigin, putting in my domain without http and with http. I'm not sure if it matters, but to test, I'm just making jQuery POST/GET calls in the console, and I'm only seeing the POST/GET requests, no preflight OPTIONS.

**Comment by catalinux** [comment]
How did you add this middleware to lumen?

**Comment by barryvdh** [comment]
Closing this as part of an issue-cleanup. Please re-open if this is still an issue on the latest version.
