### ISSUE TITLE
What is the use of the 'hosts' key in the cors config?

### ISSUE THREAD

**Issue by steffex** [barryvdh/laravel-cors#161]
What is the use of the 'hosts' key in the cors config? I can't find anything in the code.

**Comment by geekcom** [comment]
@steffex it's right, I did not find any reference either.

**Comment by barryvdh** [comment]
I think that's not used anymore since we're using middleware now

**Comment by renanpro03** [comment]
I would like to know that too!

**Comment by barryvdh** [comment]
Not used indeed.
