### ISSUE TITLE
Using CORS for /public/ folder

### ISSUE THREAD

**Issue by simplenotezy** [barryvdh/laravel-cors#163]
How do you handle CORS for files that resides within the `public` directory?

I find that if I load a static file, e.g. a font file, even though the route has cors applied, the headers are not added.

On the server I can simply apply some nginx configurations to apply the headers when loading a font file, but locally this causes some extra work that becomes unhandy when you are several developers.

Any ideas?

**Comment by barryvdh** [comment]
Htacces?

**Comment by simplenotezy** [comment]
@barryvdh I've tried. Could you provide an example?

**Comment by simplenotezy** [comment]
Also, could be cool if the package had a way to accomplish this without htaccess :)

**Comment by barryvdh** [comment]
See here: https://github.com/h5bp/html5-boilerplate/blob/4ded8b5ce09d2b665e5893945b29d8d626691086/dist/.htaccess#L10-L75

You can't do that with this package, because static aren't going through the Laravel router. You could intercept them, but that would increase your load, because you parse every static file request.

**Comment by simplenotezy** [comment]
Thanks for your promt reply @barryvdh. This is my `.htaccess` but I still see the CORS issue:

    <IfModule mod_rewrite.c>
        <IfModule mod_negotiation.c>
            Options -MultiViews
        </IfModule>

        RewriteEngine On

        # Redirect Trailing Slashes...
        RewriteRule ^(.*)/$ /$1 [L,R=301]

        # Handle Front Controller...
        RewriteCond %{REQUEST_FILENAME} !-d
        RewriteCond %{REQUEST_FILENAME} !-f
        RewriteRule ^ index.php [L]
    </IfModule>

    # ----------------------------------------------------------------------
    # | Cross-origin web fonts                                             |
    # ----------------------------------------------------------------------

    # Allow cross-origin access to web fonts.

    <IfModule mod_headers.c>
        <FilesMatch "\.(eot|otf|tt[cf]|woff2?)$">
            Header set Access-Control-Allow-Origin "*"
        </FilesMatch>
    </IfModule>

Error:

    Access to Font at 'https://assets.project.app/build/fonts/fontawesome-webfont.woff2?v=4.7.0' from origin 'https://mikenta.project.app' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'https://sub.project.app' is therefore not allowed access.

**Comment by barryvdh** [comment]
And you are using Apache? Not nginx (laravel valet?)?

**Comment by barryvdh** [comment]
For nginx, try this: https://github.com/h5bp/server-configs-nginx/blob/master/h5bp/location/cross-domain-fonts.conf with https://github.com/h5bp/server-configs-nginx/blob/master/h5bp/directive-only/cross-domain-insecure.conf

**Comment by barryvdh** [comment]
Closing as this is not an issue with the library, but a support question.

**Comment by gpressutto5** [comment]
Both links are broken now 😕

**Comment by wannfq** [comment]
For nginx:
https://www.phusionpassenger.com/library/config/nginx/cors_headers/

**Comment by frank505** [comment]
any help on this with apache?

**Comment by sohel1999** [comment]
> And you are using Apache? Not nginx (laravel valet?)?

Not working for Apache.have  Any solution for  apache ?

**Comment by alwinaugustin** [comment]
Any help with Apache ? The link to a file in public storage is not working for me.

**Comment by Deizadave** [comment]
Any help with this?
My api routes work fine, I can access the stored files with normal GET (via postman and browser) but it gives a CORS error when accessed the different origin app.

**Comment by thalesbarbosab** [comment]
Using that code in /public/.htaccess, has fix that problem. 

<IfModule mod_headers.c>
    <FilesMatch "\.(eot|otf|tt[cf]|woff2?)$">
        Header set Access-Control-Allow-Origin "*"
    </FilesMatch>
</IfModule>

**Comment by ormanfaghihi** [comment]
> Thanks for your promt reply @barryvdh. This is my `.htaccess` but I still see the CORS issue:
> 
> ```
> <IfModule mod_rewrite.c>
>     <IfModule mod_negotiation.c>
>         Options -MultiViews
>     </IfModule>
> 
>     RewriteEngine On
> 
>     # Redirect Trailing Slashes...
>     RewriteRule ^(.*)/$ /$1 [L,R=301]
> 
>     # Handle Front Controller...
>     RewriteCond %{REQUEST_FILENAME} !-d
>     RewriteCond %{REQUEST_FILENAME} !-f
>     RewriteRule ^ index.php [L]
> </IfModule>
> 
> # ----------------------------------------------------------------------
> # | Cross-origin web fonts                                             |
> # ----------------------------------------------------------------------
> 
> # Allow cross-origin access to web fonts.
> 
> <IfModule mod_headers.c>
>     <FilesMatch "\.(eot|otf|tt[cf]|woff2?)$">
>         Header set Access-Control-Allow-Origin "*"
>     </FilesMatch>
> </IfModule>
> ```
> 
> Error:
> 
> ```
> Access to Font at 'https://assets.project.app/build/fonts/fontawesome-webfont.woff2?v=4.7.0' from origin 'https://sub.project.app' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'https://sub.project.app' is therefore not allowed access.
> ```

This worked for me, Thanks a lot
