### ISSUE TITLE
Laravel 5.4 Support

### ISSUE THREAD

**Issue by affektde** [barryvdh/laravel-cors#166]

**Comment by barryvdh** [comment]
Tagged 0.8.3 with L5.4 support. Let me know if you have any problems!

**Comment by vijaythecoder** [comment]
after I update, I have this error, not sure if I miss something. 

`Class cors does not exist` 

use `0.8.4`

**Comment by vijaythecoder** [comment]
adding this `'cors'       => \Barryvdh\Cors\HandleCors::class`  in kernal.php to $routeMiddleware solved it. not sure how it worked before
