### ISSUE TITLE
Error in CorService

### ISSUE THREAD

**Issue by danielslcdevshop** [barryvdh/laravel-cors#168]
After vendor:publish I got an error here with the default configuration:

![image](https://cloud.githubusercontent.com/assets/23129061/22271090/1c79d5ce-e250-11e6-9903-64b923e6a0d0.png)

And this is probably caused by normalizeOptions function that is replacing the array for a boolean value

![image](https://cloud.githubusercontent.com/assets/23129061/22271373/722ebfd8-e251-11e6-9b9b-e99fc39d3dcd.png)

**Comment by danielslcdevshop** [comment]
And this is how I solved it

![image](https://cloud.githubusercontent.com/assets/23129061/22271621/b5e14466-e252-11e6-8221-315417044ad6.png)

**Comment by abey-alex** [comment]
This might be causing #169 issue lately.

**Comment by barryvdh** [comment]
Should be fixed with #165
