### ISSUE TITLE
implode(): Invalid arguments passed

### ISSUE THREAD

**Issue by ssuhat** [barryvdh/laravel-cors#169]
After update to v0.8.3 I got an error on CORS:

    ErrorException in CorsService.php line 93:
    implode(): Invalid arguments passed

I don't change my setup before any update:

    'supportsCredentials' => false,
    'allowedOrigins' => ['*'],
    'allowedHeaders' => ['*'],
    'allowedMethods' => ['*'],
    'exposedHeaders' => [],
    'maxAge' => 0,
    'hosts' => [],

Thanks

**Comment by andangr** [comment]
same issue, :(

**Comment by hskrasek** [comment]
Running into the same thing, glad someone reported this, means I'm not going crazy :P.

**Comment by barryvdh** [comment]
Is this happening on the latest dev version also?

**Comment by barryvdh** [comment]
Tagged 0.8.5 with #265, did that fix it?

**Comment by abey-alex** [comment]
Thanks @barryvdh, the latest version works!

**Comment by ssuhat** [comment]
0.8.4 fixed it. thanks!

**Comment by abinvp** [comment]
Confirming that the latest version fixed the issue. Thanks 👍
