### ISSUE TITLE
Laravel 5.4 Class cors does not exist

### ISSUE THREAD

**Issue by christophrumpel** [barryvdh/laravel-cors#172]
Hey, since I upgraded Laravel to 5.4 the cors middleware is not found anymore. I get this error `Class cors does not exist`.
Using the middleware as a route parameter:

```php
Route::group([ 'middleware' => 'cors'], function () {
...
});
```

**Comment by barryvdh** [comment]
Does #171 fix it for you?

**Comment by christophrumpel** [comment]
yes it does! thx @barryvdh

**Comment by aneeskodappana** [comment]
how did you solve the issue?

**Comment by christophrumpel** [comment]
Not sure but guess I just updated the version. Are you on the latest one?

**Comment by barryvdh** [comment]
Try with 0.9.0 and use the full classname, not just `cors`. See the updated readme.

**Comment by rbrisita** [comment]
Adding for anyone looking for the fix:

`app/Http/Kernel.php`

add `'cors' => \Barryvdh\Cors\HandleCors::class,` to the `protected $routeMiddleware` array.

**Comment by ismailplus** [comment]
thanks, @rbrisita your information do the job for me.

**Comment by besmartness** [comment]
works so beautifull!!!

**Comment by Tse-ChiKit** [comment]
Thanks, @rbrisita that works for me for the laravel 5.4.

**Comment by digihiveorg** [comment]
> 
> 
> Adding for anyone looking for the fix:
> 
> `app/Http/Kernel.php`
> 
> add `'cors' => \Barryvdh\Cors\HandleCors::class,` to the `protected $routeMiddleware` array.

It doesn't work for me.

**Comment by digihiveorg** [comment]
> 
> 
> > Adding for anyone looking for the fix:
> > `app/Http/Kernel.php`
> > add `'cors' => \Barryvdh\Cors\HandleCors::class,` to the `protected $routeMiddleware` array.
> 
> It doesn't work for me.

Getting this error -> ReflectionException: Class App\Http\Barryvdh\Cors\HandleCors does not exist

**Comment by rbrisita** [comment]
Have you checked that the file actually exists? Also adding the version of Laravel helps others determine what might be wrong. A good way to approach solving the issue is looking at the release notes of each Laravel version since configuration can change in newer versions.

**Comment by d0utone** [comment]
I changed the class reference to `'cors' => \Fruitcake\Cors\HandleCors::class`. That made it work
