### ISSUE TITLE
cors middlware do not exitse

### ISSUE THREAD

**Issue by siempay** [barryvdh/laravel-cors#177]
I just installed this package and I'm having problem using it; 

- I added `config/cors.php`,
- I typed `$ php artisan vendor:publish --provider="Barryvdh\Cors\ServiceProvider"` I got `Publishing complete for tag []!`
- I added things to `config/app` as said, I added the middlware to `app/http/kernel.php` but I got error `Class Barryvdh\Cors\Middleware\HandleCors` does not exist

**Comment by barryvdh** [comment]
Did you add the service provider?

**Comment by siempay** [comment]
I added this `Barryvdh\Cors\ServiceProvider::class,` to `config/app.php` 
Is there a file that I have to copy or what ?

**Comment by barryvdh** [comment]
The middleware should be: `\Barryvdh\Cors\HandleCors::class`

**Comment by siempay** [comment]
Nice, it worked, Now I have a question even if its not the right place to ask but pleasse : I m working now on a mobile app in cordova apache and laravel 5.2 as an api so what should I put as confeguration in `config/cors.php ` as allowed origin because its just an app running on android or ios device

**Comment by siempay** [comment]
this is my Config/cors.php

`<?php

return [
 /*
     |--------------------------------------------------------------------------
     | Laravel CORS
     |--------------------------------------------------------------------------
     |
     | allowedOrigins, allowedHeaders and allowedMethods can be set to array('*')
     | to accept any value.
     |
     */`

    'supportsCredentials' => false,
    'allowedOrigins' => ['*'],
    'allowedHeaders' => ['accept, content-type,x-xsrf-token, x-csrf-token'],
    'allowedMethods' => ['POST, GET, OPTIONS, PUT, DELETE'],
    'exposedHeaders' => [],
    'maxAge' => 0,
    'hosts' => [],
];`

but Im getting `Method OPTIONS is not allowed by Access-Control-Allow-Methods in preflight response.` in my chrome dev tool and response header is
`Access-Control-Allow-Headers:accept, content-type,x-xsrf-token, x-csrf-token
Access-Control-Allow-Origin:http://localhost:8001
Cache-Control:no-cache, private
Connection:Keep-Alive
Content-Type:text/html; charset=UTF-8
Date:Tue, 14 Feb 2017 10:41:43 GMT
Keep-Alive:timeout=5, max=100
Server:Apache` 

notice that there is no allow method header

**Comment by barryvdh** [comment]
Can you try with the develop branch? `composer require barryvdh/laravel-cors:"1.x@dev"` and follow instructions from readme here: https://github.com/barryvdh/laravel-cors/tree/develop

**Comment by barryvdh** [comment]
And perhaps start with allowing all values (`['*']`) for the allow options.

**Comment by pkitatta** [comment]
Wow thanks for this (\Barryvdh\Cors\HandleCors::class). I been all over the internet without a solution. I guess the author is always the best doctor.

**Comment by andreszam24** [comment]
I'm using Laravel 5.4.3 and besides ot the above, I have added 
'cors' => \Barryvdh\Cors\HandleCors::class, to  /app/Http/Kernel.php   in $routeMiddleware method. It was the solve for me.
