### ISSUE TITLE
issue with the allowedHeaders

### ISSUE THREAD

**Issue by jgardezi** [barryvdh/laravel-cors#178]
Hi All,

I am using it Laravel 5.1.x and its bit strange that I am having issues with the `allowedHeaders` after the update from v0.8.2 => v0.8.5. 

My `cors.php` file looked like and it was working fine with v0.8.2.
`
return [
    'supportsCredentials' => false,
    'allowedOrigins' => ['*'],
    'allowedHeaders' => ['*'],
    'allowedMethods' => ['GET', 'POST', 'PUT',  'DELETE', 'OPTIONS'],
    'exposedHeaders' => [],
    'maxAge' => 0,
    'hosts' => [],
];
`

As soon as I have update to v0.8.5. I was getting issues about the allowed `allowedHeaders`.

`
XMLHttpRequest cannot load http://myapi.com/api/auth/login. Request header field Content-Type is not allowed by Access-Control-Allow-Headers in preflight response.

XMLHttpRequest cannot load http://myapi.com/api/collections?page=1. Request header field Authorization is not allowed by Access-Control-Allow-Headers in preflight response.
`

So I have changed `allowedHeaders` in `cors.php` file like this and it worked fine.

`
'allowedHeaders' => ['Origin', 'X-Requested-With', 'Content-Type', 'Accept', 'Authorization'],
`

I think in Laravel 5.1.x version v0.8.5 is breaking on **`*`**.

Kind regards,
Javed Gardezi

**Comment by barryvdh** [comment]
Will check it out. Could you try the develop branch?

**Comment by neomerx** [comment]
@jgardezi You should list headers one by one. Browsers do not have to understand `*` in `Access-Control-Allow-Headers` because it's not in the CORS spec.

**Comment by barryvdh** [comment]
Ok, in 0.8.2 we did this when instead of `*`: https://github.com/barryvdh/laravel-cors/blob/bc7f40a71221b46d24971da7f0230ed4a75a18c6/src/Stack/CorsService.php#L123-L126
`strtoupper($request->headers->get('Access-Control-Request-Headers'))`

Not really sure where this was introduced. Will see what is correct here.

**Comment by barryvdh** [comment]
Wait, that is not actually changed. We just return it also on the actual request now since https://github.com/barryvdh/laravel-cors/pull/164

Not really if it's needed to return the allow headers there, but added the same logic now; https://github.com/barryvdh/laravel-cors/commit/2ae501a202acfeb210e60e40b1244781519c09a5

Does that fix it for you?

**Comment by barryvdh** [comment]
Nope, that is wrong. I don't think it needs to be sent at all.

Removed them there; https://github.com/barryvdh/laravel-cors/commit/9bf14c1d5ebe46738e8c535e56e621f98779197d

**Comment by barryvdh** [comment]
@neomerx The wildcard does seem to be supported in the 'living standard' here: https://fetch.spec.whatwg.org/#http-new-header-syntax
But not sure what the support of that is.

**Comment by neomerx** [comment]
@barryvdh from their goals
> To unify fetching across the web platform this specification supplants a number of algorithms and specifications:
> - HTML Standard’s fetch and potentially CORS-enabled fetch algorithms [HTML]
> - CORS [CORS]
> - HTTP `Origin` header semantics [ORIGIN]

Last updated 14 Feb 2017.

It seems those guys want to replace a number of specs. Though they have to get to the end and then we might see it in browsers.

For now `*` is  not supported. I had similar issue with FF or Chrome not sure which one. Sorry [it](https://github.com/neomerx/cors-psr7/issues/23) was many months ago. You already know, I think `*` should be removed or emulated with `Access-Control-Request-Headers` data with big bold red blinking security notice.

**Comment by barryvdh** [comment]
Tagged v0.8.6 with this, which should fix it.

I'm think you might be right. It is easier to debug/test, but it could lead to bruteforcing of Authorization or Cookie headers, as suggested in the issue from whatwg.

I think I'm going to allow it, but set a sensible default and put a warning on it. Thanks for your feedback!

(Btw, I looked at your repo as alternative for my CorsService, but but concerned with alle the conversions from symfony -> psr7 -> symfony and other overhead. And it's working now so no real need..)

**Comment by barryvdh** [comment]
FYI, on `1.x@dev` it's now just Content-Type and X-Requested-With as default; https://github.com/barryvdh/laravel-cors/blob/38f0d685634b01d93d473a1fbe80569ae4869b83/config/cors.php#L15

**Comment by neomerx** [comment]
@barryvdh This 'conversion' is really [3 methods of exactly 1 line each](https://github.com/neomerx/cors-illuminate/blob/master/src/Adapters/IlluminateRequestToPsr7.php#L54-L73) As far as I remember I proposed to use my lib long time ago. The proposal is still open :wink: and I would be happy if you accept it.
