### ISSUE TITLE
config option 'exposedHeaders' ignored.

### ISSUE THREAD

**Issue by boonstoppel** [barryvdh/laravel-cors#181]
The config option 'exposedHeaders' => ['authorization'] is ignored.  The only headers I see on the client are: "cache-control" and "content-type".

I'm using Lumen version ^5.4.1 and barryvdh/laravel-cors version ^0.9.2. This worked in the previous version.

**Comment by boonstoppel** [comment]
I found this line:
https://github.com/barryvdh/laravel-cors/blob/master/src/CorsService.php#L23

See pull request:
https://github.com/barryvdh/laravel-cors/pull/182

**Comment by barryvdh** [comment]
I did it a bit different, did that fix it for you? https://github.com/barryvdh/laravel-cors/commit/0b758188dadda20f4a17f1f4fe03c22ea92ce8e4

The config should always be loaded via the ServiceProvider already.

**Comment by boonstoppel** [comment]
Pulling latest version breaks the preflight request again. No 'Access-Control-Allow-Origin' header is present on the requested resource.

**Comment by barryvdh** [comment]
Did you add the service provider?

Op 22 mrt. 2017 1:22 p.m. schreef "Tobias Boonstoppel" <
notifications@github.com>:

**Comment by boonstoppel** [comment]
I see, I have to add the service provider now. In Lumen this is done like so:
$app->register(Barryvdh\Cors\ServiceProvider::class);

**Comment by barryvdh** [comment]
Okay, updated the readme to make it more clear it's also needed on Lumen.
https://github.com/barryvdh/laravel-cors/commit/df395a0ad5a66131822eb3134d4f3d2728137613

**Comment by boonstoppel** [comment]
This version still doesn't work for me tho. Not sure what's going on and if it's maybe related to another library. Will update when I have more info.

**Comment by barryvdh** [comment]
Can you check if the config is correct after normalizing?

**Comment by boonstoppel** [comment]
yes, that seems to work now. Is that the only change you submitted tho?

**Comment by barryvdh** [comment]
Yeah

**Comment by boonstoppel** [comment]
Was bug in another lib. All works fine now. Muchos gracias.
