### ISSUE TITLE
Not compatible with laravel 5.4.15?

### ISSUE THREAD

**Issue by MohammedSabbah** [barryvdh/laravel-cors#183]
Hi, I am trying to use this Middleware in my laravel 5.4 project, but the installation process stop with this error
`Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Conclusion: remove laravel/framework v5.4.15
    - Conclusion: don't install laravel/framework v5.4.15
    - laravelcollective/html v5.2 requires illuminate/view 5.2.* -> satisfiable by illuminate/view[v5.2.0, v5.2.19, v5.2.21, v5.2.24, v5.2.25, v5.2.26, v5.2.27, v5.2.28, v5.2.31, v5.2.
32, v5.2.37, v5.2.43, v5.2.45, v5.2.6, v5.2.7].
    - laravelcollective/html v5.2.1 requires illuminate/view 5.2.* -> satisfiable by illuminate/view[v5.2.0, v5.2.19, v5.2.21, v5.2.24, v5.2.25, v5.2.26, v5.2.27, v5.2.28, v5.2.31, v5.
2.32, v5.2.37, v5.2.43, v5.2.45, v5.2.6, v5.2.7].
    - laravelcollective/html v5.2.2 requires illuminate/view 5.2.* -> satisfiable by illuminate/view[v5.2.0, v5.2.19, v5.2.21, v5.2.24, v5.2.25, v5.2.26, v5.2.27, v5.2.28, v5.2.31, v5.
2.32, v5.2.37, v5.2.43, v5.2.45, v5.2.6, v5.2.7].
    - laravelcollective/html v5.2.3 requires illuminate/view 5.2.* -> satisfiable by illuminate/view[v5.2.0, v5.2.19, v5.2.21, v5.2.24, v5.2.25, v5.2.26, v5.2.27, v5.2.28, v5.2.31, v5.
2.32, v5.2.37, v5.2.43, v5.2.45, v5.2.6, v5.2.7].
    - laravelcollective/html v5.2.4 requires illuminate/view 5.2.* -> satisfiable by illuminate/view[v5.2.0, v5.2.19, v5.2.21, v5.2.24, v5.2.25, v5.2.26, v5.2.27, v5.2.28, v5.2.31, v5.
2.32, v5.2.37, v5.2.43, v5.2.45, v5.2.6, v5.2.7].
    - laravelcollective/html v5.2.5 requires illuminate/view 5.2.* -> satisfiable by illuminate/view[v5.2.0, v5.2.19, v5.2.21, v5.2.24, v5.2.25, v5.2.26, v5.2.27, v5.2.28, v5.2.31, v5.
2.32, v5.2.37, v5.2.43, v5.2.45, v5.2.6, v5.2.7].
    - don't install illuminate/view v5.2.0|don't install laravel/framework v5.4.15
    - don't install illuminate/view v5.2.19|don't install laravel/framework v5.4.15
    - don't install illuminate/view v5.2.21|don't install laravel/framework v5.4.15
    - don't install illuminate/view v5.2.24|don't install laravel/framework v5.4.15
    - don't install illuminate/view v5.2.25|don't install laravel/framework v5.4.15
    - don't install illuminate/view v5.2.26|don't install laravel/framework v5.4.15
    - don't install illuminate/view v5.2.27|don't install laravel/framework v5.4.15
    - don't install illuminate/view v5.2.28|don't install laravel/framework v5.4.15
    - don't install illuminate/view v5.2.31|don't install laravel/framework v5.4.15
    - don't install illuminate/view v5.2.32|don't install laravel/framework v5.4.15
    - don't install illuminate/view v5.2.37|don't install laravel/framework v5.4.15
    - don't install illuminate/view v5.2.43|don't install laravel/framework v5.4.15
    - don't install illuminate/view v5.2.45|don't install laravel/framework v5.4.15
    - don't install illuminate/view v5.2.6|don't install laravel/framework v5.4.15
    - don't install illuminate/view v5.2.7|don't install laravel/framework v5.4.15
    - Installation request for laravel/framework (locked at v5.4.15, required as 5.4.*) -> satisfiable by laravel/framework[v5.4.15].
    - Installation request for laravelcollective/html 5.2.* -> satisfiable by laravelcollective/html[v5.2, v5.2.1, v5.2.2, v5.2.3, v5.2.4, v5.2.5].

Installation failed, reverting ./composer.json to its original content.`

**Comment by barryvdh** [comment]
Not really sure why you think this is an issue with my package? It seems that your require laravelcollective/html 5.2 in your 5.4 project?
