### ISSUE TITLE
[5.4] Not compatible eith 5.4 - see dispatched error

### ISSUE THREAD

**Issue by IgorDePaula** [barryvdh/laravel-cors#184]
I received this error on install on laravel 5.4

```
[Symfony\Component\Debug\Exception\FatalThrowableError]                                                                                                                                                    
  Type error: Argument 1 passed to Barryvdh\Cors\HandleCors::__construct() must be an instance of Barryvdh\Cors\CorsService, instance of Illuminate\Foundation\Application given, called in /home/igor/proj  
  etos/echosuper/vendor/laravel/framework/src/Illuminate/Foundation/ProviderRepository.php on line 201
```

**Comment by barryvdh** [comment]
On Laravel (not Lumen?)
I have no idea why it would pass an Application instance. Is registered here:
https://github.com/barryvdh/laravel-cors/blob/df395a0ad5a66131822eb3134d4f3d2728137613/src/ServiceProvider.php#L24-L26

Did you register the serviceprovider? Are you on the latest version (0.9.2)

**Comment by IgorDePaula** [comment]
Laravel, Oh, sorry, I read the documentation, and copied the wrong class, sorry, very sorry, thank you very much.

**Comment by lukewatts** [comment]
I also read the wrong class for providers. Maybe @barryvdh should update the README to make it very clear it's not the same class being called in Lumen as Laravel.

I simply assumed it was and copied it without paying attention. :/
