### ISSUE TITLE
Laravel 5.1 version is not working properly

### ISSUE THREAD

**Issue by jiangguoliang** [barryvdh/laravel-cors#187]
Laravel 5.1 version is not working properly

`TokenMismatchException in VerifyCsrfToken.php line 53:`

//Kernel.php
`protected $routeMiddleware = [
            'auth' => \App\Http\Middleware\Authenticate::class,
            'auth.basic' => \Illuminate\Auth\Middleware\AuthenticateWithBasicAuth::class,
            'guest' => \App\Http\Middleware\RedirectIfAuthenticated::class,
            'cors' => \Barryvdh\Cors\HandleCors::class,
        ];`
//app.php
`Barryvdh\Cors\ServiceProvider::class,`

**Comment by barryvdh** [comment]
Are you sending csrf token?
