### ISSUE TITLE
Dingo & Laravel-cors 0.9

### ISSUE THREAD

**Issue by Broutard** [barryvdh/laravel-cors#189]
In 0.9, you push the HandlePreflight middleware, insead of preprend.

So with Dingo, the middleware "Dingo\Api\Http\Middleware\Request" is on top of middlewares array, so the HandlePreflight is not handled.

See the old MR : https://github.com/barryvdh/laravel-cors/pull/64

But, even with a prependMiddleware, the HandlePreflight failed because hasMatchingCorsRoute return a notFound Exception with Dingo router.

**Comment by barryvdh** [comment]
Doesn't the route exist?

**Comment by Broutard** [comment]
Sorry i'have found my problem.
With dingo, we must put your HandleCors middleware directly in the dingo config file : 

`'middleware' => [
        'Barryvdh\Cors\HandleCors'
    ],`

**Comment by crossRT** [comment]
Thanks @Broutard ,
Your answer solved my problem as well!
