### ISSUE TITLE
[Question] Sending headers on error

### ISSUE THREAD

**Issue by lucadegasperi** [barryvdh/laravel-cors#192]
When an error occurs inside the app (like a 500), no CORS headers are sent out. is there a way to send the headers anyways?

**Comment by barryvdh** [comment]
Which version are you on? v0.9.3? And wich Laravel version?

**Comment by lucadegasperi** [comment]
Latest version of Laravel V5.4 & 0.9.2 of this package. The issue only appears when debugging is set to true.

**Comment by barryvdh** [comment]
And with the latest? 0.9.3 ?

Do you have custom error handler?

**Comment by lucadegasperi** [comment]
This is the error handler

```
protected function convertExceptionToResponse(Exception $e)
    {
        if (config('app.debug')) {
            $whoops = new \Whoops\Run;
            $whoops->pushHandler(new \Whoops\Handler\PrettyPageHandler);

            return response()->make(
                $whoops->handleException($e),
                method_exists($e, 'getStatusCode') ? $e->getStatusCode() : 500,
                method_exists($e, 'getHeaders') ? $e->getHeaders() : []
            );
        }

        return parent::convertExceptionToResponse($e);
    }
```

**Comment by barryvdh** [comment]
You could try with `0.9.x@dev`? Otherwise, not sure why the handler isn't attached to the Whoops error.

**Comment by barryvdh** [comment]
Simple solution could be to disable the whoops error on ajax (`request()->ajax()`)

**Comment by lucadegasperi** [comment]
I am using the middleware on a route group

With Version 0.9.2 when setting ```'debug' = false``` I get the correct behavior when an exception is thrown.

With 0.9.x@dev whether I set ```debug``` to true or false, nothing changes and I always get the following when throwing an exception:

```
[Error] Failed to load resource: Preflight response is not successful
[Error] XMLHttpRequest cannot load [url]. Preflight response is not successful
```

**Comment by barryvdh** [comment]
Any errors in your log?

**Comment by lucadegasperi** [comment]
No, only the one I am throwing on purpose.

**Comment by lucadegasperi** [comment]
With 0.9.x@dev I've tried to remove the debug error renderer but the same problem as above happens.

**Comment by barryvdh** [comment]
Can you try again with https://github.com/barryvdh/laravel-cors/releases/tag/v0.10.1 ?

Please re-open this issue when the problem still persists.
