### ISSUE TITLE
Still getting "No 'Access-Control-Allow-Origin' header is present on the requested resource."

### ISSUE THREAD

**Issue by toanjo** [barryvdh/laravel-cors#193]
I am currently developing an app using Angular 2 and Laravel.

I installed laravel-cors to fix the CORS issue I was having when doing an http get request to my laravel api, but it doesn't seem to work as this still happens.

![image](https://cloud.githubusercontent.com/assets/16389424/24580973/738cf88e-170a-11e7-8fd3-72d607186054.png)

I have taken the steps listed for installation and usage on the readme, but maybe I'm missing something. I required the latest version of laravel-cors, added it to my providers array and to my middleware. I also got the configuration file cors.php and I did not alter it (as it seems to be correct for what I need).

My api.php routes look like this.

![image](https://cloud.githubusercontent.com/assets/16389424/24580991/d1b97bd0-170a-11e7-8346-dd7fd08e7294.png)

And my HTTP GET request is the following 

![image](https://cloud.githubusercontent.com/assets/16389424/24580997/eac0f568-170a-11e7-980f-74c3c2aa7f60.png)

with the Url being something like `http://localhost:8000/runmysql/database=1/dbms=1/io_capacity=100/io_buffer_pool_size=128M/io_buffer_pool_chunk_size=16M/io_sort_buffer_size=1M/isolation=3/scale_factor=10/terminals=10/run_time=10`

Accessing this URL via the browser returns the requested JSON just fine, but doing so via the angular 2 app returns the  "No 'Access-Control-Allow-Origin' header is present on the requested resource." error.

Can anyone help me fix this? Thank you!

**Comment by barryvdh** [comment]
Did you fix this?

**Comment by toanjo** [comment]
I ended up configuring an apache server for my project so that cross-origin requests would no longer be an issue.

**Comment by abey-alex** [comment]
@barryvdh We're getting this issue on the latest version. Going to use an older version for the time being.

**Comment by barryvdh** [comment]
Which works and which doesn't?

**Comment by abey-alex** [comment]
@barryvdh We're going back to 0.8.4 which had worked for us earlier.
