### ISSUE TITLE
[Question] I should enable CORS for an API ?

### ISSUE THREAD

**Issue by timersys** [barryvdh/laravel-cors#194]
HI Barry / everyone, 
I'm new to CORS and I'm not sure if I should implement this on my project or not. I'm creating an API using laravel 5.4 to deliver some data to different users.
I would like to offer some kind of domain validation. 
Basically I provide an api key (no oAuth or login methods) that they will use to query the API and they should be able to whitelist domains where that license will work.
So if the API call is from a different domain it will return a invalid response.

What I'm not sure is that CORS is the best option for this or if I should be using a simpler method (using server referrer or similar ) and simple leave my API CORS Origin open (*) to everyone.

Any clue will be much appreciated.

**Comment by barryvdh** [comment]
Cors only applies to Javascript from the client side. But if it's client side, I would probably leave Cors open for all, and restrict the domain in the Middleware or something. That way you can provide actual errors.

**Comment by timersys** [comment]
Thanks for the prompt reply, really appreciate it. I will implement client side in a future. 
But then what I should use for regular calls verification ? Does origin header get set when used for example a curl get request?
