### ISSUE TITLE
Error with preflight because of redirect?

### ISSUE THREAD

**Issue by jpmurray** [barryvdh/laravel-cors#196]
Hello there, I was trying to use the package to use with axios, I'm with the package's version 0.9.2 and Laravel 5.4. I just followed the steps to install on the readme, added the middleware to the API middleware group.

What I'm getting is `XMLHttpRequest cannot load (the url). Response for preflight is invalid (redirect)`. Inspecting the request in chrome's dev. tools shows me that the app returns a 301 Moved Permanently.

I probably have overlooked something somewhere, but I honestly just can't figure where... If anyone can enlighten me!

**Comment by barryvdh** [comment]
Is this package generating the 301?

**Comment by jpmurray** [comment]
As far as I could tell, yes, but turns out, it was on me. The redirect was caused because axios was calling to `http` and not `https`. `http` was `301`ing to https and it wasn't followed by axios.

Sorry for that!
