### ISSUE TITLE
No 'Access-Control-Allow-Origin' header - Laravel 5.4

### ISSUE THREAD

**Issue by KerryRitter** [barryvdh/laravel-cors#199]
XMLHttpRequest cannot load http://myapi/api/rating. Response to preflight request doesn't pass access control check: No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'http://localhost:8104' is therefore not allowed access. The response had HTTP status code 403.

I can't figure out why I can't make CORS requests. I've install the middleware here, added it to the global http kernel, but it still doesn't work. Tried to create a custom middleware given stackoverflow suggestions but that also did not work. Also tried adding a Route group. Lastly, I tried setting the response headers manually in the request action. I'm really stuck - help is appreciated!

See for code: https://gist.github.com/KerryRitter/0d7ababb7b9eb8d54f0ae55add9704a1

**Comment by KerryRitter** [comment]
Solved: I didn't add "Barryvdh\Cors\ServiceProvider::class"

**Comment by SEMeesha** [comment]
Try this,
https://www.youtube.com/watch?v=L-hYd2DObTA&t=93s
