### ISSUE TITLE
AllowedOrigins with special url (chrome-extension://)

### ISSUE THREAD

**Issue by atillay** [barryvdh/laravel-cors#200]
When I try to add a url starting with "chrome-extension://xxx" in allowedOrigins it doesn't work.

I was able to make it work by modifying the source code : I disabled OriginMatcher verification (CorsService.php - line 178).

Could you change the OriginMatcher validation rules so it allows "chrome-extension:// ".

Thanks in advance !

**Comment by barryvdh** [comment]
Open for PR's :)
