### ISSUE TITLE
No 'Access-Control-Allow-Origin' header is present on the requested resource.

### ISSUE THREAD

**Issue by alexgaal** [barryvdh/laravel-cors#201]
Hello,

I am using Laravel 5.4.19 and laravel-cors 0.8.4. I get following error since a few days on a specific route.

```
XMLHttpRequest cannot load https://domain.net/users. No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'http://localhost:4200' is therefore not allowed access.
```

Every route is working properly, except `/users`.

`/config/cors.php`
```
<?php

return [
    /*
     |--------------------------------------------------------------------------
     | Laravel CORS
     |--------------------------------------------------------------------------
     |

     | allowedOrigins, allowedHeaders and allowedMethods can be set to array('*')
     | to accept any value.
     |
     */
    'supportsCredentials' => false,
    'allowedOrigins' => ['*'],
    'allowedHeaders' => ['*'],
    'allowedMethods' => ['*'],
    'exposedHeaders' => [],
    'maxAge' => 0,
    'hosts' => ['*'],
];
```

**Comment by Knowlius** [comment]
Hi @alexgaal, some time ago I faced with this problem and solved it thanks to @davidnknight's comment on #15. Search for the comment on 26 Sep 2014. 

Effectively, in my case, the problem was generated by a fatal error on the controller. For the behavior you describe it may be the same issue. Check the the controller of the route `/user` and the PHP error log seeking for any error on that controller.

**Comment by mix5003** [comment]
run this command 
```php artisan config:clear```

and test again

**Comment by alexgaal** [comment]
This CORS errors are caused by fatal php errors, so issue is actually solved.

**Comment by nisarginfirays** [comment]
I have same error. In postman It works perfect. But when calling this api form the angular side then it gives same error as you have mentioned.

**Comment by alexgaal** [comment]
May you have a brief overview of your request headers?

**Comment by tangrianand** [comment]
Hi Guys,

I am facing  similar issue. I am using Amazon AWS and route 53.  I changed my domain name from 'api.temphawk.com' to 'api.temphawk.com/core' and now every api works fine except one 'api.temphawk.com/core/alert/history'. This api works fine when I open it on Postman but gives these errors when called from angular side.
It gives the following error in chrome.
![image](https://user-images.githubusercontent.com/14893415/30579906-49cfe286-9d38-11e7-88c5-d9eea1ff3fa1.png)
 And this error in mozilla. 
![image](https://user-images.githubusercontent.com/14893415/30579940-74742d8a-9d38-11e7-9ab0-c37de66eb7fc.png)

Could anyone please help ?

**Comment by nitdevv** [comment]
hey i am new in angular 2 in getting  this error    XMLHttpRequest cannot load http://localhost/angulardemo/src/app/data/tododata.json. No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'http://localhost:4200' is therefore not allowed access.
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
my service code
...............................
import { Component, OnInit } from '@angular/core'
import { Todo } from '../todo.data/todo';
import { TODOS } from '../todo.data/todo.data';
import { Injectable } from '@angular/core';
import {Http, Response} from '@angular/http';
import {Observable} from 'rxjs/Observable';
import * as _  from 'lodash';

import 'rxjs/add/operator/map';
import 'rxjs/add/observable/of';
import { jsonData } from '../data/datajson';

@Injectable()
export class HeroService {
  _url: string = jsonData.url;
  todos: Todo[] = [];
  todo: Todo;
  Data: any;
  constructor(private http: Http) {
  }
  getHeroes(): Observable<Todo[]> {
    if (this.Data) {
      return Observable.of(this.Data);
    }
    else {
      return this.http.get(this._url)
        .map((response: Response) => {
          this.Data = response.json();
          return response.json();
        })
    }
  }
  getdetail(id: number): Observable<Todo> {
    return this.getHeroes().map(
      todos => todos.find(todo => todo.id === id)[0]
    )
  }
  editData(value: Todo) {
    this.todos = _.map(this.todos, (todo) => {
      return todo;
    });
  }
  addTodo(value:Todo){
      this.Data.push(value);
  }
}

**Comment by tangrianand** [comment]
@nitdevv this has nothing to do with angular 2. The API you are calling doesn't have cors enabled in the backend. This error will vanish once cors is enabled in the API backend.

**Comment by singhsiddh** [comment]
Enable service side for CORS 
in spring use
@CrossOrigin(origins = "http://localhost:4200", maxAge = 3600)
@RestController
public class XYZController {
In case your angular application is running at port 4200
and you spring application is running other port say 8080
hen without enabling CORS it would not be work
