### ISSUE TITLE
Issues with installation

### ISSUE THREAD

**Issue by ronnievisser** [barryvdh/laravel-cors#202]
Hi,

When running the command "composer require barryvdh/laravel-cors" i'm getting the following error

Could not find package barryvdh/laravel-cors at any version for your minimum-stability (dev). Check the package spelling or your minimum-stability

i'm not sure what I can do to solve this. the laravel version is latest of 5.4

**Comment by lloy0076** [comment]
Works for me.

**Comment by TuxxyDOS** [comment]
I have the same error, did you find an issue ?
