### ISSUE TITLE
Error 405 (Method not allowed) with Laravel 5.4 (POST request)

### ISSUE THREAD

**Issue by Rayrayray9151** [barryvdh/laravel-cors#207]
I am still facing an error 405 despite installing the package. Please do take a look at my configurations.

I have added Barryvdh\Cors\ServiceProvider::class, to my 'providers' in config/app.php
![image](https://cloud.githubusercontent.com/assets/28842822/26285149/7e42ea2e-3e7c-11e7-995f-bf3c669ae7a6.png)

In my Kernel.php file:
![image](https://cloud.githubusercontent.com/assets/28842822/26285155/a57dd388-3e7c-11e7-9078-867d2cc5b0c5.png)
![image](https://cloud.githubusercontent.com/assets/28842822/26285160/b846658e-3e7c-11e7-866a-95323eb2b7f1.png)

In my config/cors.php file:
![image](https://cloud.githubusercontent.com/assets/28842822/26285166/f08df146-3e7c-11e7-90e6-c8a878aa2142.png)

I would greatly appreciate the help for this, thank you.

**Comment by savva312** [comment]
I have the same issue. Followed the instructions step-by-step.

GET request works, post requests with payload do not.

Have anyone verify that this work with Laravel 5.4?

**Comment by dericcain** [comment]
I was having that same issue and couldn't figure out what was wrong with it. I had to add `Content-Type: application/json` to my frontent request and remove my request class validation and then I started getting requests coming through.

**Comment by jameskandau** [comment]
How @dericcain did you achieved this?

**Comment by dericcain** [comment]
@jameskandau I ran into quite a few issues. One of the underlying issues, I mentioned in #208, was the fact that I had a `dd()` in my code and that was causing `CORS` to fail even though it was technically `CORS` related.

If you are asking how I achieved adding the `Content-Type` to my front-end, that would be dependent upon what you are using to make HTTP requests. If you have more information, I may be able to help.

**Comment by martinezdelprenois** [comment]
where do i set the content type to json?

**Comment by dericcain** [comment]
@martinezdelprenois It really depends on what utility you are using to make HTTP requests. Are you using Axios, jQuery, fetch, or something else?

**Comment by martinezdelprenois** [comment]
What am trying to do is, make a backend for my android app. I just made a
controller, model and added a post method to my web.php. I am abit new to
php. I really,  havenot understand your question,  sorry.

**Comment by dericcain** [comment]
@martinezdelprenois If you're running into some specific error, post an issue and we'll help you solve it. If you need general help with PHP, you can email me and I'll help you. You can find my email on my Github profile.

**Comment by gettosin4me** [comment]
set the cors in your api middleware like this
'api' => [
            'throttle:60,1',
            'bindings',
            'cors' =>[
                \Barryvdh\Cors\HandleCors::class,
            ]
        ],

**Comment by hussainwali74** [comment]
@gettosin4me  
I get this error by trying your method please help
> Illegal offset type in isset or empty

**Comment by hussainwali74** [comment]
@dericcain I have already added the content type: application/json but I still get the 404 error please help,
m trying to  access laravel backend with angular frontend
here is the code please help
```
 addQuote(content:string)
    {
        const body =  JSON.stringify({content:content});
        const header = new Headers({'Content-Type':'application/json'});
        return this._http.post('http://localhost:8000/api/quote/' + body,{header:header});
    }
```

**Comment by gettosin4me** [comment]
which version of laravel are your using?

**Comment by barryvdh** [comment]
Can you try again with https://github.com/barryvdh/laravel-cors/releases/tag/v0.10.1 ?

Please re-open this issue when the problem still persists.

**Comment by ghasemikasra39** [comment]
@dericcain dericcain I added the header. I get the same error.

**Comment by rahuldas11694** [comment]
Same issue. post calls returning 404 even on postman. please help

**Comment by Fabjooo** [comment]
Laravel 5.8 having the same problem

**Comment by LeLogicien** [comment]
Laravel 5.8 same problem too. I noticed that it my api with method get and post work perfectly in local. However in production only the get method work.  I have 405 method not allowed with the post method (but configuration looks good)
Both api with get and post method have the same middleware.
