### ISSUE TITLE
Yet another No 'Access-Control-Allow-Origin' header is present issue...

### ISSUE THREAD

**Issue by dericcain** [barryvdh/laravel-cors#208]
I thought that i had this cleared up, but apparently not. I cannot get a CORS request to work and this is day 4 battling with it. I am getting a `200` on my `OPTIONS` request and also a `200` on my `POST` request and all of the headers look like it should work, but I am still getting the error. 

Here is a screenshot of my `OPTIONS` request and the following `POST` request:

#### OPTIONS request
![screen shot 2017-05-27 at 6 43 17 pm](https://cloud.githubusercontent.com/assets/9561913/26524940/772a4446-430c-11e7-9952-28aa2ccb6e40.png)

#### POST request
![screen shot 2017-05-27 at 6 43 28 pm](https://cloud.githubusercontent.com/assets/9561913/26524945/873ced52-430c-11e7-8b8b-09cff48e7f8c.png)

Here is my `cors.php` config file:

```php
[
    'supportsCredentials' => false,
    'allowedOrigins' => ['*'],
    'allowedHeaders' => ['Content-Type', 'Origin', 'X-Requested-with', 'Access-Control-Allow-Origin'],
    'allowedMethods' => ['GET', 'POST', 'PUT', 'PATCH', 'DELETE', 'OPTIONS'],
    'exposedHeaders' => ['*'],
    'maxAge' => 0,
]
```

**Comment by dericcain** [comment]
What it ended up being was I had `dd(variable)` which is a dump and die, in my controller. For some reason, this was causing the CORS error.

#15 helped solve this

**Comment by barryvdh** [comment]
Yeah die'ing would prevent the headed being added.
