### ISSUE TITLE
POST json from localhost gives error 500 and cors warning

### ISSUE THREAD

**Issue by MaxInMoon** [barryvdh/laravel-cors#209]
### Behaviour

Hosted app
  - GET -> works
  - POST -> works

Localhost app
  - GET -> works
  - POST -> **doesn't work**

_________

Anyone here did ever succeeded in posting json from localhost?

**Comment by jameskandau** [comment]
man my head is almost bald..post not working at all ..any greenlight

**Comment by MaxInMoon** [comment]
So everybody try client requests after uploading the app by ftp on a hosted environnement?
👂

**Comment by MaxInMoon** [comment]
@jameskandau did you find a solution?

**Comment by daniel-farina** [comment]
Same problem here. When making get request from local host it works but POST request give the:

```
(index):1 Failed to load http://mysite.com/postrequest: No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'http://localhost:8080' is therefore not allowed access. The response had HTTP status code 500.
```

**Comment by alexeycrystal** [comment]
Same here...

**Comment by MaxInMoon** [comment]
I FINALLY found a way!

Instead of using :

```javascript
    return fetch(url, {
      method: 'POST',
      headers: {
        'Accept': 'application/json',
        'Content-Type': 'application/json',
      },
      body: JSON.stringify({
        payload: payload,
      }),
  })
```

Use `'application/x-www-form-urlencoded` and `qs`module (will stringify your payload on multi nested levels: `npm i qs --save` )


```javascript
import qs from 'qs';

...

    return fetch(url, {
      method: 'POST',
      headers: {
        'Content-Type': 'application/x-www-form-urlencoded; charset=UTF-8',
      },
      body: qs.stringify(payload),
    })
    .then((response) => {
      ..
    }
```
