### ISSUE TITLE
CORS middleware is not processing when using "send()" on a response.

### ISSUE THREAD

**Issue by chrislentz** [barryvdh/laravel-cors#211]
My API uses `response()->...->send()` to terminate code execution and immediately return an error response. What I have found is that whenever I use `send()` with the response, the CORS middleware is not running and the CORS headers are not being attached to the response.

Here is an example: `return response()->json($output, 500)->send();`

Does anyone (@barryvdh) know of a way that I can make sure the CORS middleware is being run when calling `send()` on a response? Or a way to trigger the middleware manually when `send()` is needed?

**Comment by barryvdh** [comment]
Why do you send and terminate it directly?

**Comment by chrislentz** [comment]
@barryvdh In our API, we have abstracted some of the more common error checking out into their own methods. When you are inside a child method if you call `return response()->json($output, 500)` it just returns on that child method, not the parent, so the parent method continues to run. You would have to `return false` from the child and then check for the false response form the child on the parent and trigger the `return response()->json($output, 500)` from the parent. This is less than ideal as it bloats the code and in some rare cases, it could be a child of a child of a parent method.

If we call `return response()->json($output, 500)->send();` then it terminates the script at the abstracted child method and returns the error response. Laravel supports the `withHeaders()` when using `send()`, I am just trying to avoid having to had the CORS headers manually.

Also, just and FYI, I am not calling `return response()` directly from the abstracted child, I have another error method that I just to process and format errors. Here is the static error function I call for consistent responses.
```
public static function error(int $http_status, string $message = null, string $code = null)
{
    if (!empty($message)) { $message = ['message' => self::processMessage($message)]; } else { $message = []; }
    if (!empty($code)) { $code = ['code' => $code]; } else { $code = []; }

    $output = array_merge(['status' => 'error'], $message, $code);

    return response()->json($output, $http_status)->send();
}
```

**Comment by barryvdh** [comment]
I suggest you throw an error (eg. ApiResponseException) with the message and code, catch that in your error handler and convert to json.

**Comment by chrislentz** [comment]
Great thinking! I added in the custom exception and trigger the response from there and the CORS headers are added correctly. 👍
