### ISSUE TITLE
not reading any configs

### ISSUE THREAD

**Issue by jacquesfu** [barryvdh/laravel-cors#213]
I've installed as a global middleware and confirm that cors is working across our site. However, I created the file in config/cors.php and changed the allowedMethods value but I'm not seeing this header being updated in responses.

I also changed cors.php in the vendor folder but these are the same methods that continue to be returned. Tested using postman and ran under `php artisan serve` command.

Response always returned:

Allow →GET,HEAD,POST,PUT

**Comment by barryvdh** [comment]
did you clear the cache?
