### ISSUE TITLE
Cannot run phpunit in Laravel anymore

### ISSUE THREAD

**Issue by derkjn** [barryvdh/laravel-cors#214]
After installing this package on a fresh install of Laravel 5.4.25, whenever I try to run my unit tests I get the following error:
```
./vendor/bin/phpunit                  
PHP Fatal error:  Class 'Orchestra\Testbench\TestCase' not found in /Users/user/Sites/website/vendor/barryvdh/laravel-cors/tests/TestCase.php on line 5

Fatal error: Class 'Orchestra\Testbench\TestCase' not found in /Users/user/Sites/website/vendor/barryvdh/laravel-cors/tests/TestCase.php on line 5
```
Not sure what to do to fix this!

**Comment by barryvdh** [comment]
Hmm, not sure why it would run the tests in my folder. Are you sure you configured phpunit correctly to look for tests in your tests folder only?

**Comment by derkjn** [comment]
Thank you so much for the quick response!
I haven't changed anything in the initial Laravel configuration for the tests.
My phpunix.xml is as follows:
```
<?xml version="1.0" encoding="UTF-8"?>
<phpunit backupGlobals="false"
         backupStaticAttributes="false"
         bootstrap="bootstrap/autoload.php"
         colors="true"
         convertErrorsToExceptions="true"
         convertNoticesToExceptions="true"
         convertWarningsToExceptions="true"
         processIsolation="false"
         stopOnFailure="false">
    <testsuites>
        <testsuite name="Application Test Suite">
            <directory suffix="Test.php">./tests</directory>
        </testsuite>
    </testsuites>
    <filter>
        <whitelist processUncoveredFilesFromWhitelist="true">
            <directory suffix=".php">./app</directory>
        </whitelist>
    </filter>
    <php>
        <env name="APP_ENV" value="testing"/>
        <env name="CACHE_DRIVER" value="array"/>
        <env name="SESSION_DRIVER" value="array"/>
        <env name="QUEUE_DRIVER" value="sync"/>
    </php>
</phpunit>
```
and I simply run `./vendor/bin/phpunit` from my project root folder.
Any help on this is greatly appreciated! 😄

**Comment by derkjn** [comment]
For some reason I had a wrong structure in my tests folder, I re-created the project from scratch and it's all working well now! Sorry for the false alarm! 😄

**Comment by rvanbaalen** [comment]
@derkjn What kind of wrong structure? I'm experiencing the same issue here. Curious to know how you resolved it.

**Comment by derkjn** [comment]
@rvanbaalen My laravel installation was not at the latest version for some reason (can't tell you exactly why!) I just restarted the project with a fresh install and it all worked out. I noticed that the structure of the files within the test folder has changed between last few versions of laravel. If that's the case, you can just overwrite your test folder with the latest one from Laravel and you should be good to go! Hope it helps 😄

**Comment by EM-LilianaIturribarria** [comment]
I also have this issue.
I've read your comments, so i've changed my tests folder structure and still nothing.
I'm not extending directly from that old TestCase Class.
I'm using the abstract class with the Create Application trait

However i still have this issue, and the weird part is that i'm also trying running a single suite and it's the same...
