### ISSUE TITLE
Error (No 'Access-Control-Allow-Origin' header is present on the requested resource.)

### ISSUE THREAD

**Issue by marinabgarcia** [barryvdh/laravel-cors#216]
I'm using laravel-cors as a middleware for my request.
When the browser makes the request type OPTIONS, the middleware put the correct headers to the response: 
![image](https://user-images.githubusercontent.com/8139301/27228178-e5cc55f4-527c-11e7-91ab-7fe6733d3134.png)
But when the browser makes the request type POST, the middleware doesnt add any headers to the response.
Debugging the code I noticed that when the handler code reaches the line: $response = $next($request) it continues with my method (define in the api.php).

```
public function handle($request, Closure $next)
	{
		if (! $this->cors->isCorsRequest($request)) {
			return $next($request);
		}
		if ( ! $this->cors->isActualRequestAllowed($request)) {
			abort(403);
		}
		/** @var \Illuminate\Http\Response $response */
		$response = $next($request);
		return $this->cors->addActualRequestHeaders($response, $request);
	}
```

Any clue of this? Im using laravel 5.4.
Thank you.

**Comment by DemianD** [comment]
Have the same problem

**Comment by marinabgarcia** [comment]
I finally found a workaround for this.
I made my own middleware for the CORS request and I added the headers.

`
     header('Access-Control-Allow-Origin: '+$request->headers->get('Origin'));
     header('Access-Control-Allow-Methods: GET, POST, PATCH, PUT, DELETE, OPTIONS');
     header('Access-Control-Allow-Headers: Content-Type, Accept, Authorization, X-Requested-With, Application');
`
