### ISSUE TITLE
[Question] Change cors.php config during request lifecycle

### ISSUE THREAD

**Issue by pppwwwa** [barryvdh/laravel-cors#222]
Hello, first I want to thank you for developing package, it is very useful for me. I have a question, that is I set   `allowedOrigins` array to `['*']` in config file for all my routes, and I assign a short key name 'cors' to middleware instead of setting it as a global middleware. But now for some specific routes, I just want to allow few origins. So I write a custom middleware and change config like `config(['cors.allowedOrigins'=>['http://localhost:10000']])` in the middleware, and assign it to some routes. But it not work, at the very beginning I think it might be caused by the order of middlewares. Like 

```
Route::get('test',function(){
    return 'OK';
})->middleware(['change-cors','cors']);
```

or

```
Route::get('test',function(){
    return 'OK';
})->middleware(['cors','change-cors']);
```

still not working. So could you please tell me how can I change cors config in request life cycle? Thanks.

**Comment by barryvdh** [comment]
Probably similar to https://github.com/barryvdh/laravel-cors/issues/267

Should perhaps add a callback option.
