### ISSUE TITLE
OPTIONS request is executing POST route, not simply returning 200

### ISSUE THREAD

**Issue by lofye** [barryvdh/laravel-cors#223]
The preflight OPTIONS request is actually running the code in the post route.
Expected behaviour is that it would immediately return 200 if the requested route & method exist, not that it would execute that route & method.

**Comment by barryvdh** [comment]
Is this with the latest `0.9.3` version? Can you also try with the new `0.10.x@dev` version?

**Comment by mrajabtech** [comment]
@lofye @barryvdh am having the same problem with Laravel 5.5. Options request is working and the POST request is returning 200 without executing the right method.

Any help would be greatly appreciated.

**Comment by hussainwali74** [comment]
@barryvdh   please please help I am stuck with this for a week it is really pissing me off now.. I have searched the whole internet,, whole of github no solution found..
My get and delete requests work fine but put and post methods `give method not allowed  Error: 404` 
please helpp

**Comment by barryvdh** [comment]
Can you try with `v0.10.1`? Please re-open if the issue this persists.

**Comment by x5c** [comment]
I think still proces i use v0.11.0,,, the api process twice.. and data duplicate..

plz help

**Comment by andreaschrist27** [comment]
please help, same problem here. v0.11.0
