### ISSUE TITLE
how can I use postman to send a request ?

### ISSUE THREAD

**Issue by greedying** [barryvdh/laravel-cors#225]
when I want to send a normal request  not  cors request，I get a 403 Forbidden。

That is because Postman have  a  default  origin just like `chrome-extension://fhbjgbiflinjbdggehcddcbncdddomop`

Is there any method to remove it ?

THanks

**Comment by marcelo2605** [comment]
Use [Postman Interceptor].(https://www.getpostman.com/docs/postman/sending_api_requests/interceptor_extension)
