### ISSUE TITLE
Not working with Laravel 5.2.*

### ISSUE THREAD

**Issue by digitalrep** [barryvdh/laravel-cors#226]
When I make a request from remote origin I get 

XMLHttpRequest cannot load website. No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin is therefore not allowed access. The response had HTTP status code 403.

When I use an asterisk to allow all origins it works. When I try to put the specific URL in it doesn't. 
I put it in providers array in app.php
Have this in Kernel.php

    protected $middleware = [
        \Illuminate\Foundation\Http\Middleware\CheckForMaintenanceMode::class,
	\Barryvdh\Cors\HandleCors::class,
    ];

    protected $middlewareGroups = [
        ...
        'api' => [
            'throttle:60,1',
	    \Barryvdh\Cors\HandleCors::class,
        ],
    ];

... So yeah it doesn't work. Am I missing something?

**Comment by digitalrep** [comment]
I just updated my cors.php

    'supportsCredentials' => false,
    'allowedOrigins' => ['https://first.url.com', 'https://second.url.com'],
    'allowedHeaders' => ['Origin', 'Content-Type', 'X-Auth-Token', 'Authorization'],
    'allowedMethods' => ['GET', 'POST', 'PUT',  'DELETE'],
    'exposedHeaders' => [],
    'maxAge' => 0,
    'hosts' => [],

Now second.url.com works, but not first.url.com

**Comment by digitalrep** [comment]
I added a wildcard in the first url and now it works. So now it is:
'supportsCredentials' => false,
'allowedOrigins' => ['https://*.url.com', 'https://second.url.com'],
'allowedHeaders' => ['Origin', 'Content-Type', 'X-Auth-Token', 'Authorization'],
'allowedMethods' => ['GET', 'POST', 'PUT',  'DELETE'],
'exposedHeaders' => [],
'maxAge' => 0,
'hosts' => [],

Hope this helps someone else...

**Comment by ngonguyentan** [comment]
I have the same issue as above. I did try the solution of digitalrep but no help

**Comment by barryvdh** [comment]
Can you try again with https://github.com/barryvdh/laravel-cors/releases/tag/v0.10.1 ?

Please re-open this issue when the problem still persists.
