### ISSUE TITLE
Works in local machine but not on production

### ISSUE THREAD

**Issue by webcrazy** [barryvdh/laravel-cors#228]
Cors works well in my pc but not on production when file upload.

**Comment by mmlaraveldeveloper** [comment]
In server, some folders  need to give proper permissions. and PHP GD is required but I keep getting cors warning and nothing else. After I fixed above things, it works very well. 

Great package.

**Comment by webcrazy** [comment]
In server, some folders need to give proper permissions. and PHP GD is required but I keep getting cors warning and nothing else. After I fixed above things, it works very well.

Great package.

**Comment by oberoivarun** [comment]
I'm also facing the same issue. Cors is not working in production but all routes are not working. Even a simple login post request. Can you explain what you did to fix the issue?

However, the error changes when i comment out the `handlecors` middleware from

```
Response to preflight request doesn't pass access control check: No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'https://www.mydomain.com' is therefore not allowed access. If an opaque response serves your needs, set the request's mode to 'no-cors' to fetch the resource with CORS disabled.
```

to

```
No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'https://www.mydomain.com' is therefore not allowed access. The response had HTTP status code 500. If an opaque response serves your needs, set the request's mode to 'no-cors' to fetch the resource with CORS disabled.
```

It works in my local machine.

**Comment by webcrazy** [comment]
If you think you set up cors correctly, may be your sever has some issue. Please test with postman first without enabling the cors.

**Comment by oberoivarun** [comment]
Yup. Found the issue in my nginx conf file. Silly mistake.

**Comment by BlackBo6** [comment]
@oberoivarun can u please tell what u did in nginx config file, because I have the same error, it's working properly in localhost but not in production server and I'm also using nginx
