### ISSUE TITLE
[0.9.2] Invalid origin pattern file://  from cordova app

### ISSUE THREAD

**Issue by dmason30** [barryvdh/laravel-cors#229]
We have a frontend webapp that is used as a website and is ported to `cordova` (using `crosswalk`), the issue is that in the cordova app when it makes a request it sends the origin as `file://`. 

I have tried:
 'file://' 
 'file://*' 

In the accepted origins list in the config file. I cannot set the config option to '*' as we have other origins that are in there for when the requests are being made from a non app browser. 

```
[2017-08-18 14:40:15] local.ERROR: exception 'InvalidArgumentException' with message 'Invalid origin pattern file://' in /var/www/dev2/api/site/vendor/barryvdh/laravel-cors/src/Util/OriginMatcher.php:79
```

Is this being blocked intentionally? I am bodging it with some `middleware` as a (hopefully) temporary solution.

**Comment by barryvdh** [comment]
Cordova doesn't use CORS. You shouldn't need it.

**Comment by dmason30** [comment]
@barryvdh But there is no way to prevent it when I am using the same frontend for website/app (making requests via `axios`) and using the same backend with your `middleware`. Using cordova doesn't control the way requests are made?

**Comment by barryvdh** [comment]
Not really sure, I've never had to worry about Cors when using Cordova.
