### ISSUE TITLE
403 when using group middleware

### ISSUE THREAD

**Issue by edmandiesamonte** [barryvdh/laravel-cors#231]
Using Laravel 5.5 pre-release and I keep on getting 403 even though I already allowed all. Upon tracing it was caused by HandlePreflight class.

Here's a snippet of my HttpKernel:
```
'api' => [
            \Barryvdh\Cors\HandleCors::class,
            'throttle:60,1',
            'bindings',
            \Aurora\Cloud\Http\Middleware\MixPanelIdentify::class,
        ],
```

Here's a snippet of my `RouteServiceProvider`
```
protected function mapApiRoutes()
    {
        Route::domain(config('app.subdomains.api'))
            ->prefix('v1')
            ->name('api.')
            ->middleware('api')
            ->namespace($this->namespace . '\Api')
            ->group(base_path('routes/api.php'));
    }
```

On this line, inside `HandlePreflight.php`
```
    protected function hasMatchingCorsRoute($route)
    {
        return in_array(HandleCors::class, $route->middleware());
    }
```
`$route->middleware()` only outputs `['api']`, which makes the condition always false.

Can you verify?

**Comment by barryvdh** [comment]
Can you try with the latest release? Looks like #230 perhaps?
You can otherwise try the new `0.10.x@dev` version.

**Comment by edmandiesamonte** [comment]
@barryvdh confirming that it's fixed with that PR. Closing this issue.
