### ISSUE TITLE
Not working with laravel 5.5

### ISSUE THREAD

**Issue by punkpette** [barryvdh/laravel-cors#232]
I'm trying to upgrade to laravel 5.5 but have this issue:

    - barryvdh/laravel-cors v0.8.6 requires illuminate/support 5.1.x|5.2.x|5.3.x|5.4.x -> satisfiable by laravel/framework[v5.4.28], illuminate/support[v5.1.1, v5.1.13, v5.1.16, v5.1.2, v5.1.20, v5.1.22, v5.1.25, v5.1.28, v5.1.30, v5.1.31, v5.1.41, v5.1.6, v5.1.8, v5.2.0, v5.2.19, v5.2.21, v5.2.24, v5.2.25, v5.2.26, v5.2.27, v5.2.28, v5.2.31, v5.2.32, v5.2.37, v5.2.43, v5.2.45, v5.2.6, v5.2.7, v5.3.0, v5.3.16, v5.3.23, v5.3.4, v5.4.0, v5.4.13, v5.4.17, v5.4.19, v5.4.27, v5.4.36, v5.4.9].

any plans on updating the package to enable support for 5.5?

**Comment by barryvdh** [comment]
Sure, try the latest version

**Comment by EM-LilianaIturribarria** [comment]
thanks that worked!
