### ISSUE TITLE
Update the config/cors.php

### ISSUE THREAD

**Issue by marcospaegle** [barryvdh/laravel-cors#233]
Hi, I try to use this package but when I run 

> php artisan vendor:publish --provider="Barryvdh\Cors\ServiceProvider"

 the config/cors.php was wrong.

`    return ['supportsCredentials' => false,
    'allowedOrigins' => ['*'],
    'allowedHeaders' => ['*'],
    'allowedMethods' => ['*'],
    'exposedHeaders' => [],
    'maxAge' => 0,]`

and the right is something like this:

`return ['defaults' => array(
        'supportsCredentials' => false,
        'allowedOrigins' => array('*'),
        'allowedHeaders' => array('*'),
        'allowedMethods' => array('POST', 'PUT', 'GET', 'DELETE'),
        'exposedHeaders' => array('*'),
        'maxAge' => 0,
        'hosts' => array(),
    )]`

Plz, fix that.

**Comment by barryvdh** [comment]
?

**Comment by mludi** [comment]
`[]` is only the modern syntax for `array()`

**Comment by Lauriy** [comment]
Stop using PHP 5.3.
