### ISSUE TITLE
PUT, PATCH, DELETE requests are not working

### ISSUE THREAD

**Issue by binishprabhakar** [barryvdh/laravel-cors#235]
I have tried with Lumen (5.4.7) and angular 4.  Issues i have faced are listed below

1.  route middleware is not working. Its only working with global middleware.
2.  if am trying with middleware in group route (auth and cors), its returning fatal error
3. POST request is working perfectly
4. After preflight request for PUT,PATCH and DELETE are converting to GET request.

Please help me to resolve this.

Note: I have double checked the configuration and installations. cant found any issue in those..

**Comment by barryvdh** [comment]
With real methods or faking with_method?

**Comment by binishprabhakar** [comment]
With real methods

**Comment by binishprabhakar** [comment]
Hey , Its working fine.. Its an issue related to angular HTTP header parameters

**Comment by hussainwali74** [comment]
@binishprabhakar what was the issue?? please help I am stuck with this method for a week now. In my case get and delete methods work just fine but put and post give me errors. Thanks in advance

**Comment by pbvarsok** [comment]
Im with the same problem. What was the issue??
