### ISSUE TITLE
Error: v0.9.3 and Laravel 5.5

### ISSUE THREAD

**Issue by tjgazel** [barryvdh/laravel-cors#236]
[Symfony\Component\Debug\Exception\FatalThrowableError]                      
  Type error: Argument 1 passed to Barryvdh\Cors\HandleCors::__construct() mu  
  st be an instance of Barryvdh\Cors\CorsService, instance of Illuminate\Foun  
  dation\Application given, called in ~/vendor/laravel/framework/src/Illuminate/Foundation/ProviderRepository.php   
  on line 208

**Comment by barryvdh** [comment]
Make sure you add the ServiceProvider
