### ISSUE TITLE
Can't install on L5.2

### ISSUE THREAD

**Issue by tomadmiraal** [barryvdh/laravel-cors#237]
Hi,

I'm trying to install this package on L5.2 but it wont install:"

  Problem 1
    - illuminate/support v5.5.2 requires php >=7.0 -> your PHP version (5.6.31) does not satisfy that requirement.
    - illuminate/support v5.5.0 requires php >=7.0 -> your PHP version (5.6.31) does not satisfy that requirement.
    - Installation request for barryvdh/laravel-cors ^0.9.3 -> satisfiable by barryvdh/laravel-cors[v0.9.3].
    - Conclusion: remove laravel/framework v5.2.45
    - Conclusion: don't install laravel/framework v5.2.45
    - barryvdh/laravel-cors v0.9.3 requires illuminate/support 5.3.x|5.4.x|5.5.x -> satisfiable by illuminate/support[v5.3.0, v5.3.16, v5.3.23, v5.3.4, v5.4.0, v5.4.13, v5.4.17, v5.4.19, v5.4.27
, v5.4.36, v5.4.9, v5.5.0, v5.5.2].
    - don't install illuminate/support v5.3.0|don't install laravel/framework v5.2.45
    - don't install illuminate/support v5.3.16|don't install laravel/framework v5.2.45
    - don't install illuminate/support v5.3.23|don't install laravel/framework v5.2.45
    - don't install illuminate/support v5.3.4|don't install laravel/framework v5.2.45
    - don't install illuminate/support v5.4.0|don't install laravel/framework v5.2.45
    - don't install illuminate/support v5.4.13|don't install laravel/framework v5.2.45
    - don't install illuminate/support v5.4.17|don't install laravel/framework v5.2.45
    - don't install illuminate/support v5.4.19|don't install laravel/framework v5.2.45
    - don't install illuminate/support v5.4.27|don't install laravel/framework v5.2.45
    - don't install illuminate/support v5.4.36|don't install laravel/framework v5.2.45
    - don't install illuminate/support v5.4.9|don't install laravel/framework v5.2.45
    - Installation request for laravel/framework (locked at v5.2.45, required as 5.2.*) -> satisfiable by laravel/framework[v5.2.45].

Why is it not installing? Do I need L5.3?

**Comment by liquid36** [comment]
I've a similar problem too.

>   Problem 1
>     - Installation request for barryvdh/laravel-cors ^0.9.3 -> satisfiable by barryvdh/laravel-cors[v0.9.3].
>     - Conclusion: remove laravel/framework v5.2.45
>     - Conclusion: don't install laravel/framework v5.2.45
>     - barryvdh/laravel-cors v0.9.3 requires illuminate/support 5.3.x|5.4.x|5.5.x -> satisfiable by illuminate/support[v5.3.0, v5.3.16, v5.3.23, v5.3.4, v5.4.0, v5.4.13, v5.4.17, v5.4.19, v5.4.27, v5.4.36, v5.4.9, v5.5.0, v5.5.2].
>     - don't install illuminate/support v5.3.0|don't install laravel/framework v5.2.45
>     - don't install illuminate/support v5.3.16|don't install laravel/framework v5.2.45
>     - don't install illuminate/support v5.3.23|don't install laravel/framework v5.2.45
>     - don't install illuminate/support v5.3.4|don't install laravel/framework v5.2.45
>     - don't install illuminate/support v5.4.0|don't install laravel/framework v5.2.45
>     - don't install illuminate/support v5.4.13|don't install laravel/framework v5.2.45
>     - don't install illuminate/support v5.4.17|don't install laravel/framework v5.2.45
>     - don't install illuminate/support v5.4.19|don't install laravel/framework v5.2.45
>     - don't install illuminate/support v5.4.27|don't install laravel/framework v5.2.45
>     - don't install illuminate/support v5.4.36|don't install laravel/framework v5.2.45
>     - don't install illuminate/support v5.4.9|don't install laravel/framework v5.2.45
>     - don't install illuminate/support v5.5.0|don't install laravel/framework v5.2.45
>     - don't install illuminate/support v5.5.2|don't install laravel/framework v5.2.45
>     - Installation request for laravel/framework (locked at v5.2.45, required as 5.2.*) -> satisfiable by laravel/framework[v5.2.45].

**Comment by niilante** [comment]
Try this and it will work just fine
add ` "barryvdh/laravel-cors": "0.8.x@dev" ` to your composer.json file
run  ` composer update ` in command line and you're good to go.

**Comment by liquid36** [comment]
it's work! Thanks.
:+1:
