### ISSUE TITLE
Lowercase Headers Causing ‘Access-Control-Allow-Origin’ Missing Error

### ISSUE THREAD

**Issue by envision** [barryvdh/laravel-cors#238]
Am getting this error on Firefox Developer Edition:

_Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at https://localproject.dev/...../ . (Reason: CORS header ‘Access-Control-Allow-Origin’ missing)._

My Laravel project is in fact responding with 'access-control-allow-origin'! **But these headers are meant to be case sensitive, and I'm pretty sure this is the problem!**

There are several issues raised by missing ‘Access-Control-Allow-Origin’ and this might be cause for it.

Using v0.9.3. on Laravel v5.4.36.

**Comment by envision** [comment]
https://github.com/CachetHQ/Cachet/issues/1391

**Comment by abelkbil** [comment]
How is it fixed.

**Comment by barryvdh** [comment]
Can you try again with https://github.com/barryvdh/laravel-cors/releases/tag/v0.10.1 ?

Please re-open this issue when the problem still persists.
