### ISSUE TITLE
Error when making PUT, PATCH, DELETE requests

### ISSUE THREAD

**Issue by GeorgeHanson** [barryvdh/laravel-cors#240]
There appears to be an error with making PUT, PATCH and DELETE requests in Laravel 5.5. When making a request, the preflight check appears to fail. This is because it is looking to match the route, getting the request method from the `Access-Control-Request-Method` header. However when this is faked, this is a POST request and so does not work.

I will make a PR for this.

**Comment by GeorgeHanson** [comment]
Sorry, when I went to fork the repository it appears the current master branch is different to the last released tag. What is on the master branch appears to fix it. For now I am currently pulling down dev-master but will keep a look out for when you tag it 👍

**Comment by marciodiasdev** [comment]
waiting ...

**Comment by kuroshio** [comment]
Can confirm preflight check is still failing in latest tag v0.10.0. Downgrading package to v0.9.3 fixes the issue on my PUT requests
