### ISSUE TITLE
Laravel 5.4 not work.

### ISSUE THREAD

**Issue by Lunberg88** [barryvdh/laravel-cors#242]
I run composer require barryvdh/laravel-cors and composer installed the latest version^
"barryvdh/laravel-cors": "^0.9.3"
Then configure like in docs, but it dosn't work...
Still showing:

> XMLHttpRequest cannot load https://docs.google.com/gview?url=http://somedomain.ua/uploads/t.pdf&embedded=true. No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'http://ajax_lv' is therefore not allowed access.

**Comment by LeandritGo** [comment]
Same!!! I hope this issue gets fixed.

**Comment by bcdbuddy** [comment]
I was so exiting about this package (because I know the debugbar stuff from the same author) but not working with 5.5
  :(

**Comment by Xinil** [comment]
Working in my company's Laravel 5.4 app.

**Comment by barryvdh** [comment]
Please check again with `0.10.1` and re-open this if you're still having the problem.
