### ISSUE TITLE
Fix for 'Access-Control-Allow-Origin' using Passport (4.0) and Laravel 5.5 (possibly 5.4 too)

### ISSUE THREAD

**Issue by asamarcos** [barryvdh/laravel-cors#243]
You have to register HandleCors on Kernel.php as requested in laravel-cors manual. This will add cors in all routes under the 'api' middleware.

```
        'api' => [
            'throttle:60,1',
            'bindings',
            \Barryvdh\Cors\HandleCors::class,
        ],

```
Problem is Passport has it's own routes, outside of the API middleware.
So you have to set your passport routes on AuthServiceProvider explicitly giving HandleCors as a middleware:

```
    public function boot()
    {
        $this->registerPolicies();

        Passport::routes(null, ['middleware' => [ \Barryvdh\Cors\HandleCors::class ]]);
    }

```

Problem was caused by HandlePreflight.php class, method hasMatchingCorsRoute(). It did not detect HandleCors between passport middlewares.

**Comment by se1exin** [comment]
@asamarcos Thanks man! Worked for me.

**Comment by barryvdh** [comment]
Can you try again with https://github.com/barryvdh/laravel-cors/releases/tag/v0.10.1 ?

Please re-open this issue when the problem still persists.

**Comment by CrixuAMG** [comment]
Experiencing the same issue on v0.11.0, is there an information on how to fix it?

**Comment by anglyeds** [comment]
@barryvdh I downloaded the newest version in v0.11.0, and also experiencing the same issue .

**Comment by CrixuAMG** [comment]
@barryvdh ping

**Comment by barryvdh** [comment]
Did the workaround not work for you?

**Comment by CrixuAMG** [comment]
Nope, I've tried removing the dependency, installing it again, running `composer dumpautoload && php artisan config:clear`, then trying it, but no luck.
I'm getting the exact same error as @asamarcos did.

My API is running on the latest version of Laravel 5.5, running on the latest version of homestead.
The dashboard I'm working on is being developed using VueJS and axios (for the API-calls) using a local development server.

@barryvdh if you require any specific information, please let me know!

**Comment by phfilly** [comment]
@CrixuAMG have you managed to fix this?

**Comment by yangjianhua** [comment]
@barryvdh I downloaded the newest version in v0.11.0, and also experiencing the same issue .
Laravel 5.6.*

Using in Electron, when running in client, it works; when running in web, it doesn't work.

(The old version, which is 0.9.2, works fine)

**Comment by hofit93** [comment]
@yangjianhua I have the same issue, did you solve that ??

**Comment by juanhuerta** [comment]
Adding Passport::routes(null, ['middleware' => [ \Barryvdh\Cors\HandleCors::class ]]) in Laravel 5.5 worked for me!

**Comment by StupidKido** [comment]
Just in case you miss this: If your route is '/some-route' and you add additional / on the end, cors will return error. At least that how it does on laravel 5.7-6 for me

**Comment by yannskee** [comment]
Omg ! Many thx ! @asamarcos
