### ISSUE TITLE
Laravel 5.5 Package Discovery Not Working

### ISSUE THREAD

**Issue by dashawk** [barryvdh/laravel-cors#244]
I tried to install a fresh Laravel 5.5 and install this package, but it doesn't seem to be able to use this package. It can discover the package but it cannot use it unless you do the standard thing like, add `Barryvdh\Cors\ServiceProvider::class,` in the `config/app.pp` then put it in the `middleware`.

So this means that Laravel 5.5 doesn't actually discovering packages, it's just saying that it discovered a package and that is it, or maybe I am missing something.

**Comment by Sowed** [comment]
Laravel 5.5 does, to be best of my knowledge. I think the creators of the package have to implement the auto discovery feature in their packages. And from the looks of it, `laravel-cors` has not implemented it yet as you still need to add the providers manually.

**Comment by barryvdh** [comment]
Can you try again with https://github.com/barryvdh/laravel-cors/releases/tag/v0.10.1 ?

Please re-open this issue when the problem still persists.

**Comment by dashawk** [comment]
Thanks @barryvdh it is working fine now. 👍

**Comment by leelijin** [comment]
same issue, but my version is v0.11.0.
so why the question happen again?
