### ISSUE TITLE
When can I support HTTPS?

### ISSUE THREAD

**Issue by jiangguoliang** [barryvdh/laravel-cors#245]
The site is HTTPS protocol, use the editor and found that the "map module" does not support the HTTPS protocol

Mixed Content: The page at 'https://www.xxx.com/sys/ConfigManager/1/edit' was loaded over HTTPS, but requested an insecure script 'http://api.map.baidu.com/?qt=cur&wd=%E5%8C%97%E4%BA%AC&key=&ie=utf-8&oue=1&res=api&callback=BMap.DataMgr.RawDispatcher._cbk97864'. This request has been blocked; the content must be served over HTTPS.

**Comment by barryvdh** [comment]
This has nothing to do with CORS, just make sure you only include HTTPS when using https yourself
