### ISSUE TITLE
If app is in maintenance mode laravel cors fails

### ISSUE THREAD

**Issue by Sjerd** [barryvdh/laravel-cors#246]
If the app is in maintenance mode ```php artisan down``` the preflight response is: ```Response to preflight request doesn't pass access control check: No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin '***' is therefore not allowed access. The response had HTTP status code 503.``` 

I expected the middleware to just disable if the app would be in maintenance mode so you could actually check the status code. But since it doesn't pass preflight the actual response returns empty: ```{
  "_body": {
    "isTrusted": true
  },
  "status": 0,
  "ok": false,
  "statusText": "",
  "headers": {},
  "type": 3,
  "url": null
}``` 

Is there a workaround or a known solution for this?

**Comment by Stolz** [comment]
Try listing `\Barryvdh\Cors\HandleCors` before `\Barryvdh\Cors\HandleCors`.

    // File app/Http/Kernel.php
    protected $middleware = [
        \Barryvdh\Cors\HandleCors::class,
        \Illuminate\Foundation\Http\Middleware\CheckForMaintenanceMode::class,
        ...
    ];

You can also specify the order at which middlewares are run, with the `$middlewarePriority` property. Take a look at the base class `Illuminate\Foundation\Http\Kernel`

**Comment by ZR87** [comment]
Hey @Stolz ,  do you mean listing the `HandleCors` middleware before `\Illuminate\Foundation\Http\Middleware\CheckForMaintenanceMode::class`
