### ISSUE TITLE
not work in Laravel 5.5

### ISSUE THREAD

**Issue by mostafamiri65** [barryvdh/laravel-cors#249]
this package does not work in Laravel 5.5

**Comment by WalissonRodrigo** [comment]
I have this same problem my Laravel is 5.5 and my PHP is 7.1 but not work with  package

**Comment by WalissonRodrigo** [comment]
I try update my composer in project and before updated this package install normaly in my project

**Comment by mostafamiri65** [comment]
i uses `HTTP_REFERER` instead of cors method.
i wanna reject any request from anonymous servers just.

```
$referDomain = parse_url(request()->headers->get('referer'), PHP_URL_HOST);

$allow = ['mysite.local'];
return in_array($referDomain,$allow)? $next($request):response('Invalid Request!',400);
```
of course it's not safe way, because i can put `refer` in postman headers.

**Comment by Sowed** [comment]
@mostafamiri65 and @WalissonRodrigo, `Laravle 5.5` supports [Package Discover](https://laravel.com/docs/5.5/packages#package-discovery). More on that [here](https://medium.com/@taylorotwell/package-auto-discovery-in-laravel-5-5-ea9e3ab20518). However much as it's implemented with `laravel-cors` already, I still had to add the necessary [provider](https://github.com/barryvdh/laravel-cors#installation) and [middleware](https://github.com/barryvdh/laravel-cors#group-middleware) manually to get it working. 
Am running Laravel 5.5 and Php 7, and it's working fine.

**Comment by barryvdh** [comment]
Can you try again with https://github.com/barryvdh/laravel-cors/releases/tag/v0.10.1 ?

Please re-open this issue when the problem still persists.
