### ISSUE TITLE
CORS not working only on a handful of routes

### ISSUE THREAD

**Issue by vjrngn** [barryvdh/laravel-cors#251]
I've been using this package for a while now and haven't faced any issues. I recently updated to Laravel 5.3 and noticed I'm getting the infamous `Response to preflight request doesn't pass access control check: No 'Access-Control-Allow-Origin' header is present on the requested resource`.

The weird part is that this happens only on a handful of routes in my application and not all of them. I've tried a number of things and still came up empty handed as to what the problem might be.

Hope someone can help me here!

**Comment by lilian21** [comment]
Still the same here, Laravel 5.4. The only routes working are the public ones, but login is not working. This started to happen when added SSL to both frontend  / API projects.

**Comment by vjrngn** [comment]
Hmm odd. I have protected routes .. most of which are working, some aren't. That's the odd part about this issue.

**Comment by ortegamediatasoft** [comment]
Same issue, but on 0.2x branch, two routes with the same structure are responding with different results, is anyone able to give a workarround?

**Comment by barryvdh** [comment]
Can you try again with https://github.com/barryvdh/laravel-cors/releases/tag/v0.10.1 ?

Please re-open this issue when the problem still persists.
