### ISSUE TITLE
Bad response type expectation for laravel

### ISSUE THREAD

**Issue by webmake** [barryvdh/laravel-cors#252]
Hello,

Currently noticed, that at some point my responses listener stopped to working. After debugging of occuring error
`Undefined property: Symfony\Component\HttpFoundation\Response::$exception` noticed, that all preflight responses are using symfony response, which further is not wrapped into laravel responses [`toIlluminateResponse`](https://github.com/laravel/framework/blob/1af9ec33e1a477e01ef43a3008c2ee62382ce8d4/src/Illuminate/Foundation/Exceptions/Handler.php#L412).
My question is, why not throwing an error like other middlewares does in `handle` method, so response then would be in laravel style

https://github.com/barryvdh/laravel-cors/blob/master/src/CorsService.php#L161
https://github.com/barryvdh/laravel-cors/blob/master/src/HandlePreflight.php#L33

**Comment by barryvdh** [comment]
Can you try again with https://github.com/barryvdh/laravel-cors/releases/tag/v0.10.1 ?

Please re-open this issue when the problem still persists.
