### ISSUE TITLE
 Class 'Orchestra\Testbench\TestCase' not found in /var/www/api/vendor/barryvdh/laravel-cors/tests/TestCase.php on line 5

### ISSUE THREAD

**Issue by aconital** [barryvdh/laravel-cors#253]
I cannot run phpunit anymore. It gives me this error:

>  Class 'Orchestra\Testbench\TestCase' not found in /var/www/api/vendor/barryvdh/laravel-cors/tests/TestCase.php on line 5

**Comment by aconital** [comment]
structure issue in test folder

**Comment by dtirer** [comment]
@aconital what was the structure issue exactly?

**Comment by chrisbeaver** [comment]
I came across this issue today. I wanted a subfolder /tests/Api to run tests from, and loaded it into my autoloader via psr4. I missed namespacing one of my tests in the root /tests folder, and it triggered this error in my barryvdh package. Once I namespaced the test in ran without a problem.
