### ISSUE TITLE
Question - Why is the piece of documentation about errors removed since v0.9.0?

### ISSUE THREAD

**Issue by kaphert** [barryvdh/laravel-cors#256]
I had issues with this package not adding the cors headers to the response when an exception was thrown (a 404 for example). When I searched through the issues here I figured out some people had the same problem and I was able to solve it with adding this piece of code to my `Handler.php`

```
public function render($request, Exception $e)
{
    $response = parent::render($request, $e);

    if (! $response->headers->has('Access-Control-Allow-Origin')) {
                $response = app(CorsService::class)->addActualRequestHeaders($response, $request);
    }

    return $response;
}
```

This solution is mentioned in the documentation before v0.9.0 but since v0.9.0 this part is removed. This can mean two things:

1. There is better solution since v0.9.0 which is not working for me (I am running v0.10.0 with L5.5 upgraded from L5.1 a few weeks ago)
2. The documentation of the newer versions is just missing this part

Which of the two is it? 

https://github.com/barryvdh/laravel-cors/tree/v0.8.6
https://github.com/barryvdh/laravel-cors/tree/v0.9.0

**Comment by barryvdh** [comment]
It should be handling errors by itself now.

Can you try with `v0.10.1`? Please re-open if the issue this persists.
