### ISSUE TITLE
404 Not Found response with ARC

### ISSUE THREAD

**Issue by meysammahfouzi** [barryvdh/laravel-cors#261]
I am using Advanced REST client to send OPTIONS to a REST API url I have. But I am getting 404 Not Found error. When I modify the code of `handle($request, Closure $next)` in the `HandleCors` class and change the last two lines of it from:
```
$response = $next($request);
return $this->addHeaders($request, $response);
```
to:
```
$response = response("");
return $this->addHeaders($request, $response);
```
the problem gets fixed. And I think that's because since I have not handled OPTIONS requests in my Laravel routes, when the request is sent to the application by `$next($request)`, error `404` is generated because no route is found for it. But when I don't send the `OPTIONS` request to the application and simply create an empty response by calling `response("")`, everything works fine. Am I missing something here? What's the problem with my request?

**Comment by barryvdh** [comment]
Does it work without CORS? Does the route exist at all?

**Comment by meysammahfouzi** [comment]
@barryvdh Yes it does exist. It works without CORS and as I said, when I change those two lines, the problem gets fixed.

**Comment by barryvdh** [comment]
Can you try again with https://github.com/barryvdh/laravel-cors/releases/tag/v0.10.1 ? 

Please re-open this issue when the problem still persists.
