### ISSUE TITLE
No headers present on OPTIONS request

### ISSUE THREAD

**Issue by blacktrue** [barryvdh/laravel-cors#262]
Hi, I need help with larval + vuejs and CORS

I have a domain http://mydomain.com or http://www.mydomain.com

When I enter this: http://www.mydomain.com is working
But if igo through: http://mydomain.com

Failed to load http://www.mydomain.com/checkCertificates: Response to preflight request doesn't pass access control check: No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'http://mydomain.com ' is therefore not allowed access.

Headers CORS only response When I enter this: http://www.mydomain.com

In Kernel.php

```
protected $routeMiddleware = [
  …
  'cors' => \Barryvdh\Cors\HandleCors::class,
]
```

My config/cors.php default:

```
<?php
return [
    /*
    |--------------------------------------------------------------------------
    | Laravel CORS
    |--------------------------------------------------------------------------
    |
    | allowedOrigins, allowedHeaders and allowedMethods can be set to array('*')
    | to accept any value.
    |
    */
   
    'supportsCredentials' => false,
    'allowedOrigins' => ['*'],
    'allowedHeaders' => ['*'],
    'allowedMethods' => ['*'],
    'exposedHeaders' => [],
    'maxAge' => 0,
];
```

**Comment by barryvdh** [comment]
Can you try with https://github.com/barryvdh/laravel-cors/releases/tag/v0.10.1 ?

**Comment by barryvdh** [comment]
Please re-open this issue when the problem still persists.
