### ISSUE TITLE
ERROR 419 on Laravel 5.5 + ReactJS

### ISSUE THREAD

**Issue by lwidomski** [barryvdh/laravel-cors#263]
Hello,
I am sorry if I am forgetting something banal in my code, but I am only just starting with Laravel. I am following [this tutorial](https://appdividend.com/2017/08/31/laravel-5-5-reactjs-tutorial/) to get me started (I tried it multiple times making sure I follow every single step), but I am getting stuck on the POST request. It is giving me Error 419 (Unknown Status). First I was getting error about not having the CSRF token; this is not covered in the tutorial, but I figured out to add

`<meta name="csrf-token" content="{{ csrf_token() }}">`

into my welcome.blade.php

This is the configuration of my cors.php:

`'supportsCredentials' => false,`
 `'allowedOrigins' => ['http://127.0.0.1:8000'],`
 `'allowedHeaders' => ['content-type', 'x-csrf-token', 'x-requested-with'],`
 `'allowedMethods' => ['*'],`
 `'exposedHeaders' => [],`
 `'maxAge' => 0,`

In network tab of my browser I see two requests being sent. One is of method OPTIONS, which succeeds and the other one is POST and that one fails.
If I comment out VerifyCsrfToken from Kernel.php then it works fine so the issue is definitely with the CSRF verification.

The tutorial even mentions there might be a problem with CSRF and suggests using this package, but where the author seems to succeed I am still getting errors.

Would some laravel magician be kind enough to please try following the tutorial to the point where it this package is being installed and see what might be missing to get the CSRF verification working with this package?
By the way (you would probably figure it out yourselves), the author also is forgetting to update the Master.js' one of the menu items in order to be able to access the POST form with this:

`<li><Link to="add-item">Create Item</Link></li>`

I am going back to the original problem here as I spent countless hours researching this problem on the internet and tried many solutions. I have seen people complaining about Laravel 5.5 in regards to this issue, as well as people commenting the CSRF verification or writing their own middlewares which I have tried as well, but nothing ended with a success. I would be eternally grateful to whomever is going to help me out here.

**Comment by barryvdh** [comment]
Can't you just disable CORS on your API?

**Comment by barryvdh** [comment]
Ehr, CSRF I mean

**Comment by barryvdh** [comment]
Can you try again with https://github.com/barryvdh/laravel-cors/releases/tag/v0.10.1 ? 

Please re-open this issue when the problem still persists.
