### ISSUE TITLE
Determining allowedOrigins programatorically

### ISSUE THREAD

**Issue by freekmurze** [barryvdh/laravel-cors#267]
I'm building an app where multiple parties have api access. 

Each party has it's own domains where it can make requests from.

What is the best way of passing the allowed domains of the logged in party to `allowedOrigins`?

I could swap out the  `CorsService` registered by the service provider with another instance where the domains of a party are passed via the options of the constructor. But this seems a bit nasty.

Is there a better way?

**Comment by barryvdh** [comment]
I think we could perhaps  allow a callback to determine if the origin matches?

```php
$corsService->setOriginCallback(function($request) use ($myApiService) { ... } );
```

I'm open for improvements :)

**Comment by freekmurze** [comment]
`setOriginCallback` could be useful yes. 👍 

Like mentioned on Twitter I'm currently creating my own lightweight cors solution.
