### ISSUE TITLE
Protect API routes from browser with CORS?

### ISSUE THREAD

**Issue by gmask** [barryvdh/laravel-cors#268]
**Edit 2**: After further research it seems I'm going to need to use laravel passport in order to protect my API routes from browsers. Is that right?

**Edit**: So I'm wrong, CORS is blocking requests made from my external Vue.js app, but I can still browse to the resource in the browser and see its content. How can I block this?

**Comment by barryvdh** [comment]
CORS only protects against cross-origin requests in the browser, it's not an actual protection for your content.
