### ISSUE TITLE
i have installed cors but still getting same error

### ISSUE THREAD

**Issue by harshalone** [barryvdh/laravel-cors#27]
hi i hve installed cors but still getting same error:

http://www.scrumy.co.uk/

register 
sign in
create project
create a todo list
then add a task inside it 

you will see the error

```
XMLHttpRequest cannot load http://scrumy.co.uk/projects/addtask. No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'http://www.scrumy.co.uk' is therefore not allowed access. The response had HTTP status code 403.
```

**Comment by rap2hpoutre** [comment]
+1

**Comment by DigitalMediaLoft** [comment]
+1

**Comment by mk-conn** [comment]
+1 

Used default config to allow everything. Allowed these methods: ['POST', 'GET', 'PUT', 'DELETE', 'OPTIONS'] - its working for GET requests but not for PUT 

```
XMLHttpRequest cannot load http://127.0.0.1:8000/api/v1/eventTypes/10. 
No 'Access-Control-Allow-Origin' header is present on the requested resource. 
Origin 'http://127.0.0.1:4200' is therefore not allowed access. 
The response had HTTP status code 500.
```

**Comment by mk-conn** [comment]
Well, I found the problem here on my site: The VerifyCsrfToken middleware caused the problem - switching it off, PUT works.

**Comment by barryvdh** [comment]
In the latest L5 it's possible to catch more errors. I'll have a look soon.

**Comment by xeppen** [comment]
I also commented out the VerifyCsrfToken middleware in Kernel.php and that solved it for me.

**Comment by KlitnyjS** [comment]
like this
```
class VerifyCsrfToken extends BaseVerifier {
    public function handle( $request, Closure $next )
    {
        if ( str_contains( $request->getRequestUri(), '/api/' ) ) {
            return $next( $request );
        }
        return parent::handle( $request, $next );
    }
}
```

**Comment by VickG** [comment]
+1

**Comment by zerojargon** [comment]
I also appear to be having this or a similar issue.

Cors Middleware is global, but if there is an error such as a 401 or 403, CORs fails.

Could this be that the middleware to check authentication / tokens etc is firing and returning a response before CORs middleware gets fired?

**Comment by barryvdh** [comment]
Yes, but that should be fixed in latest dev, which doesn't use middleware.
