### ISSUE TITLE
Exception handler

### ISSUE THREAD

**Issue by arcadas** [barryvdh/laravel-cors#32]
Hello,
How can I use this middleware with Laravel 5 app/Exceptions/Handler.php? Because when exception happen, this middleware does not set the headers.
Thanks!

**Comment by barryvdh** [comment]
I dont think the middleware works for errors anymore so I'll have to see what is best. Probably register an error handler or something.

**Comment by philipbrown** [comment]
Hi @barryvdh, have you had any thoughts on dealing with this? I'm running into the same issue.

**Comment by barryvdh** [comment]
Yeah since L5.0.16 we should be able to catch the final response and add the headers there. Might need some refactoring.

**Comment by paulocoghi** [comment]
Same problem. @barryvdh how can I deal with this with an error handler (temporarily)?

**Comment by philipbrown** [comment]
I just did the following, works a treat :smile:
```
$cors = App::make('Asm89\Stack\CorsService');

return $cors->addActualRequestHeaders($response, $request);
```

**Comment by nloding** [comment]
FWIW, this package doesn't work at all with L5, but if I set the headers at the top of bootstrap/app.php, that gives a solid workaround for now. Perhaps that's a clue about how to fix this package?

**Comment by barryvdh** [comment]
What doesn't work? Are you sure you have your configuration set correctly and that no exceptions are thrown?

**Comment by alioygur** [comment]
+1

**Comment by bernier** [comment]
please help, I have the same issue

**Comment by davidnknight** [comment]
No errors are return when an error 500 occurs, instead you just get `No 'Access-Control-Allow-Origin' header is present on the requested resource...` in the console, which in one way is expected because there headers are not being added, but it makes it extremely difficult to work with, and results in an awkward workflow.

**Comment by barryvdh** [comment]
Can you guys checkout the `0.5.x@dev` version? I removed the middleware (so should you from your Kernel) and added a before/handled filter. The handled filter should kick in, even on errors. (At least, errors after the beforefilter).

**Comment by davidnknight** [comment]
Hey @barryvdh, just updated, removed the middleware and deliberately caused an internal server error 500 to test, unfortunately no change. I'm around all evening and can jump on IRC if you'd like some help getting to the bottom of it, let me know if so.

**Comment by davidnknight** [comment]
So, as a temporary fix whilst you've been working on the package I have been adding the following to the top of `public/index.php`:

    header('Access-Control-Allow-Origin: *');
    header('Access-Control-Allow-Methods: GET, POST, PATCH, PUT, DELETE, OPTIONS');
    header('Access-Control-Allow-Headers: Origin, Content-Type, Authorization');

I commented those out whilst I tested your changes. An XHR request to an endpoint with a deliberate internal server error 500 then results in an error in the console:

> XMLHttpRequest cannot load http://api.domain.dev/something. No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'http://localhost:4200' is therefore not allowed access. The response had HTTP status code 500.

So I uncommented the lines in `public/index.php` again so that errors would once again come through and now I get a different error, which has only happened since updating your package:

> XMLHttpRequest cannot load http://api.domain.dev/something. The 'Access-Control-Allow-Origin' header contains multiple values '*, http://localhost:4200', but only one is allowed. Origin 'http://localhost:4200' is therefore not allowed access.

It's getting `http://localhost:4200` from `config/cors.php`:

    return array(
        'defaults' => array(
            'supportsCredentials' => false,
            'allowedOrigins' => array('http://localhost:4200'),
            'allowedHeaders' => array('*'),
            'allowedMethods' => array('*'),
            'exposedHeaders' => array(),
            'maxAge' => 0,
            'hosts' => array(),
        ),

        'paths' => array(),
    );```

So it is doing something different from before at least, compared to when I was using version `0.4.*@dev`. Perhaps this will help shed some light on the issue for you, but as said previously, let me know if there's anything else I can do to help.

**Comment by barryvdh** [comment]
Can you just put 'localhost' as allowed origin?

**Comment by davidnknight** [comment]
Now shows:
> XMLHttpRequest cannot load http://api.domain.dev/something. No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'http://localhost:4200' is therefore not allowed access. The response had HTTP status code 403.

**Comment by kennonb** [comment]
Version 0.5@dev seems to fix the issues I was having with L5's Exception Handler. :+1:

**Comment by zerojargon** [comment]
I don't suppose there's any update on this? I put the temporary workaround in my public/index.php, but can't seem to find any other fix.

**Comment by barryvdh** [comment]
Did you try the latest dev version?

**Comment by zerojargon** [comment]
I might be being stupid, but couldn't see the 5.0.x version on github.

**Comment by zerojargon** [comment]
Installed 5.0.x@dev through composer, but this causes a completely new error, which appears to happen directly after CorsServiceProvider build

    BindingResolutionException in Container.php line 872: Unresolvable dependency resolving [Parameter #0 [ <required> $app ]] in class Illuminate\Support\ServiceProvider

        in Container.php line 872
        at Container->resolveNonClass(object(ReflectionParameter)) in Container.php line 844
        at Container->getDependencies(array(object(ReflectionParameter)), array()) in Container.php line 813
        at Container->build('Barryvdh\Cors\CorsServiceProvider', array()) in Container.php line 656
        at Container->make('Barryvdh\Cors\CorsServiceProvider', array()) in Application.php line 644
        at Application->make('Barryvdh\Cors\CorsServiceProvider') in Pipeline.php line 124
        at Pipeline->Illuminate\Pipeline\{closure}(object(Request)) in CheckForMaintenanceMode.php line 42
        at CheckForMaintenanceMode->handle(object(Request), object(Closure)) in Pipeline.php line 125
        at Pipeline->Illuminate\Pipeline\{closure}(object(Request))
        at call_user_func(object(Closure), object(Request)) in Pipeline.php line 101
        at Pipeline->then(object(Closure)) in Kernel.php line 115
        at Kernel->sendRequestThroughRouter(object(Request)) in Kernel.php line 84
        at Kernel->handle(object(Request)) in index.php line 53

**Comment by koorb** [comment]
I'm getting `No 'Access-Control-Allow-Origin' header is present on the requested resource` too. I'm using 0.6.x

**Comment by eporral1** [comment]
Hi philipbrown , where did you add those lines?

**Comment by philipbrown** [comment]
@eporral1 https://github.com/laravel/laravel/blob/9b359ba24cccaebbf6b54b1962f01bfc0a57a950/app/Exceptions/Handler.php#L42

**Comment by eporral1** [comment]
Hi @barryvdh this is the issue I'm experiencing:

if my routes have an internal error, I receive:

XMLHttpRequest cannot load http://localhost:8000/signin. No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'http://localhost:8001' is therefore not allowed access. The response had HTTP status code 500.

For instance: If I turn off my MySql DB, I receive that error, instead of "invalid connection to db" or something like that, when trying to login.

I'm using version "0.4.x@dev" and my settings are:

'defaults' => array(
'supportsCredentials' => false,
'allowedOrigins' => array(''),// default ()
'allowedHeaders' => array(''),// default ()
'allowedMethods' => array(''),// default ()
'exposedHeaders' => array(''),// default ()
'maxAge' => 0,
'hosts' => array(),
),

Any Idea?
thanks!

**Comment by barryvdh** [comment]
@eporral1 1 reply with your issue is enough.

What version are you one? v0.7.1?

**Comment by eporral1** [comment]
thank you for answer @philipbrown , btw are you using laravel 4?

**Comment by philipbrown** [comment]
@eporral1 No

**Comment by eporral1** [comment]
@philipbrown  are those  the only changes you did to receive the correct errors instead of  "No 'Access-Control-Allow-Origin' header is present"

**Comment by eporral1** [comment]
@barryvdh no, "0.4.x@dev"

**Comment by eporral1** [comment]
@barryvdh version 0.7.1 requires:

    - barryvdh/laravel-cors v0.7.1 requires illuminate/support ~5.0.14|5.1.x ->
satisfiable by illuminate/support[v5.0.22, v5.0.25, v5.0.26, v5.0.28, v5.0.33, v
5.1.1, v5.1.2, v5.1.6].

which one should I use? I'm a newbie in laravel ;)

**Comment by eporral1** [comment]
@barryvdh I have installed 0.7.1 and now in my console I get

XMLHttpRequest cannot load http://localhost:8000/signin. Invalid HTTP status code 500

this is great, but is it possible to receive the classic "whooops" message in the response?

**Comment by photoart-mtlwebdev** [comment]
Hi,

I'm facing the same issue here on a fresh Laravel 5.1 install:
I can throw an exception just fine but can't use dd(), is that normal ?

```
XMLHttpRequest cannot load. No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin is therefore not allowed access.
```

Any clue ?
Thanks.

**Comment by barryvdh** [comment]
Yes that's normal. You're aborting the request with a `die()` so no way to add any headers anymore.

**Comment by photoart-mtlwebdev** [comment]
Alright, thanks a lot.

**Comment by smithyj** [comment]
@philipbrown  
this is good idea！
Thanks you!
```
$cors = App::make('Asm89\Stack\CorsService');

return $cors->addActualRequestHeaders($response, $request);
```

**Comment by cartewebapp** [comment]
> @philipbrown
> this is good idea！
> Thanks you!
> 
> ```
> $cors = App::make('Asm89\Stack\CorsService');
> 
> return $cors->addActualRequestHeaders($response, $request);
> ```

Where should I want paste these lines? I am confusing please explain

**Comment by timothymarois** [comment]
This is old, and would have thought recent versions would resolve this. But as of today, using the latest version of Laravel, I am seeing this issue.

**Comment by monkeyphysics** [comment]
> This is old, and would have thought recent versions would resolve this. But as of today, using the latest version of Laravel, I am seeing this issue. I'm trying to find a way to catch `PostTooLargeException` and send an error, but because of the handler, it doesn't send in the CORS.

Same here on L8. Did you ever fix this @timothymarois ?

**Comment by vgavrilovikj** [comment]
@barryvdh Please is there any fix for L8?
