### ISSUE TITLE
#ask[Class App\Http\Barryvdh\Cors\HandleCors does not exist] on laravel 5.7

### ISSUE THREAD

**Issue by budineverend** [barryvdh/laravel-cors#337]
hallo, i am just using CORS on laravel 5.7, is it have a problem??

**Comment by littleWanderer** [comment]
I have a problem, too. We're using React Native and can't establish a connection between those two applications. Have you found a solution?

**Comment by jozhetak** [comment]
@budineverend Have you found a solution?

**Comment by Lochanahasith** [comment]
I have the same issue . Any solution ?

**Comment by littleWanderer** [comment]
I used spatie cors instead, it works perfectly

**Comment by budineverend** [comment]
> @budineverend Have you found a solution?

what is problem are you get it?

**Comment by budineverend** [comment]
> I have the same issue with laravel 5.7 .Have you found any solution ?

what is problem are you get it?

**Comment by mdahosan** [comment]
Add it to $middlewareGroups in Kernel.php:
'cors' => [
\Barryvdh\Cors\HandleCors::class,
],
This working for me on 5.7

**Comment by EVNIKHIL** [comment]
I have the issue in Laravel 5.8. Tried

> 'cors' => [
\Barryvdh\Cors\HandleCors::class,
],

**Comment by treiero** [comment]
> I have the issue in Laravel 5.8. Tried
> 
> > 'cors' => [
> > \Barryvdh\Cors\HandleCors::class,
> > ],

Same problem here.

**Comment by Fabjooo** [comment]
> I have the issue in Laravel 5.8. Tried
> 
> > 'cors' => [
> > \Barryvdh\Cors\HandleCors::class,
> > ],

I have the same problem 😩

**Comment by gabva** [comment]
I had this problem and used   \Fruitcake\Cors\HandleCors::class as the namespace

**Comment by kca66y** [comment]
> I had this problem and used \Fruitcake\Cors\HandleCors::class as the namespace

Yeah, I have same problem, did u found solution?

**Comment by gabva** [comment]
You should use Fruitcake\Cors instead of this one
-- 
*G**abriel DESCHILDRE*

*L'ENTREPRISE ADAPTEE DIGITAL, GOODIES, DESIGN GRAPHIQUE*
*Tel :* +33 / (0)3.20.39.32.21
*Mobile :* +33 / (0)6.19.11.62.08
*Web :* www.weezea.com

**Comment by kiranshrote1990** [comment]
I tried both of this i got class did not found

**Comment by pmochine** [comment]
Had the same issue. Fixed it, by just removing the vendor folder and composer.lock and installed all packages fresh

**Comment by Tope19** [comment]
> I had this problem and used \Fruitcake\Cors\HandleCors::class as the namespace

Worked Fine

**Comment by mramireza272** [comment]
> 
> You should use Fruitcake\Cors instead of this one

Worked Fine, from laravel 5.7 to 7.* upgrade

**Comment by imrannazirbhat** [comment]
> Fruitcake\Cors

Is this the way it has to be:

'cors' => [
 Fruitcake\Cors,
],
