### ISSUE TITLE
Using custom response format

### ISSUE THREAD

**Issue by giulioprovasi** [barryvdh/laravel-cors#34]
Is it possible to catch the responses from the middleware (403, 500) and transform the response to a json response ?

I am actually using this module for an API and when the CORS are wrong, I simply get a plain text message instead of the expected json

**Comment by barryvdh** [comment]
Laravel 5? In a recent commit it's possible to catch an error response also, but this isn't in a stable version yet.

**Comment by kitensei** [comment]
sorry I forgot to say I'm using laravel 4.2

**Comment by barryvdh** [comment]
How are you returning the error? You can set your own error handler to show json.

**Comment by kitensei** [comment]
I think I havent explained myself correctly, in the CORS middleware we have this:

```
        if ( ! $this->cors->isActualRequestAllowed($request)) {
            return new Response('Not allowed.', 403);
        }
```

This code doesn't trigger the `App:error` in my case, I have put a simple echo

```
App::error(function(Exception $exception, $code)
{
    echo 'err';
}
```

but nothings is shown, I only get the 403 Not Allowed

**Comment by barryvdh** [comment]
Okay so perhaps we could better throw an exception

    throw new HttpException(403, 'Not allowed.', null, $headers);

But that's only the case for invalid cors requests right, not for errors in the app itself?

**Comment by barryvdh** [comment]
And in the 0.2 version we just use the middleware from a external package so not really easy to change.

**Comment by kitensei** [comment]
Yes that's waht I have seen, the problem is that anything that is raised from the CorsService middleware that laravel-cors use won't be catched by the error handler.

I'm not an expert with laravel, I'm still learning, maybe there is a possibility to catch codes independently from the `App::err` method ? So I could just catch 4xx err and return a json response
