### ISSUE TITLE
Response to preflight request doesn't pass access control check: No 'Access-Control-Allow-Origin' header is present on the requested resource.

### ISSUE THREAD

**Issue by ZondaHTR** [barryvdh/laravel-cors#341]
Hello, 

I am using Angular 6 and laravel 5.7 to create a project. 
Installed the package  `barryvdh/laravel-cors`.

I set the baseURL of my requests from a service of my  angular project  to http://www.mydomain.com/laravel/public/api for production deployment purpose. In my local server heading to www.mydomain.test/api works good, but when i deploy it cause of the preflight request i have this error :  

> `Access to XMLHttpRequest at 'http://mydomain.com/laravel/public/api/sendMessage' from origin 'http://www.mydomain.com' has been blocked by CORS policy: Response to preflight request doesn't pass access control check: No 'Access-Control-Allow-Origin' header is present on the requested resource.`

Any idea how can i fix it ?

**Comment by behroozbc** [comment]
hi 
I check package 
its disabled.
you must add manual to your app

**Comment by amorZhu** [comment]
我也遇到了相同的问题，但是我最终解决了它。
在 Laravel 中不要使用 `public function __construct(){}`，它会导致你的http请求头不会被改变。
把它去掉就可以了。
希望能帮助到你！

**Comment by ZondaHTR** [comment]
the problem was not on the package , the server didn't support the laravel i was using.

**Comment by WeeHong** [comment]
@amorZhu 

谢谢你帮我解决了这几天的困扰！

**Comment by jackbaron** [comment]
@AlexGrabovaj you found any solution?
