### ISSUE TITLE
Cannot Pass Preflight Response. Error 403 and 405

### ISSUE THREAD

**Issue by johnray21216** [barryvdh/laravel-cors#343]
I've been dealing with an issue  of a project that was left by a programmer who I replaced at work for weeks now. I have a websocket running the ws npm and the API backend is Laravel 5.6. The frontend is powered by Angular 1.6.

This has something to do with the CORS requests and response headers. At first, the Cross-Origin configuration was missing but I was able to add it on the server. Now, I am dealing with the issue of preflight requests and the common error codes I get is either a 405 (Method Not Allowed) or 403 (Forbidden). 

Please see the code snippets below

`$.ajaxSetup({
	headers:{
	   'Access-Control-Allow-Origin': "*",
	   'Access-Control-Allow-Headers' : "Origin,Content-Type,Authorization,X-Auth-Token,Accept",
	   'Access-Control-Allow-Methods' : "GET,POST,PUT,PATCH,DELETE,HEAD,OPTIONS",
	   'Content-Type': "application/json",
	}
 });`
I already initialized the AJAX to have the headers I needed for the request. But when I do the following code:

`http.get("https://website.com/gateway/api/gameplay", options, function (err,r) {
	var result;
	console.log("6 - GET PLAY DATA");
	//console.log("r headers", r.headers);
	r.on('data', function (chunk) {
		console.log("Data Received...");
		result += chunk;
	});		
	r.on('end', function () {
		//console.log('res',result);
		rr=JSON.parse(result.split('undefined')[1]);

		for (var x=0;x<rr.data.length;x++) {
			var num=rr.data[x].num.split(',');
			gbit.push({player:rr.data[x].player,id:rr.data[x].id,num:num});	
		}			
	})
	console.log("Initialize Player Data ");
});`

I get the following stack error in my websocket:

> Error: Error: Response for preflight has invalid HTTP status code 403
>     at Object.dispatchError (/home/sp/src/ws/node_modules/jsdom/lib/jsdom/living/xhr-utils.js:60:19)
>     at EventEmitter.client.on.err (/home/sp/src/ws/node_modules/jsdom/lib/jsdom/living/xmlhttprequest.js:677:20)
>     at emitOne (events.js:121:20)
>     at EventEmitter.emit (events.js:211:7)
>     at Request.preflightClient.on.resp (/home/sp/src/ws/node_modules/jsdom/lib/jsdom/living/xhr-utils.js:364:16)
>     at emitOne (events.js:116:13)
>     at Request.emit (events.js:211:7)
>     at Request.onRequestResponse (/home/sp/src/ws/node_modules/request/request.js:1066:10)
>     at emitOne (events.js:116:13)
>     at ClientRequest.emit (events.js:211:7) undefined

The Laravel backend has also the laravel-cors middleware setup and has the following configuration in the config file.

`  'supportsCredentials' => false,
    'allowedOrigins' => ['*'],
    'allowedOriginsPatterns' => [],
    'allowedHeaders' => ['Origin', 'Content-Type', 'Authorization', 'X-Auth-Token', 'Accept'],
    'allowedMethods' => ['GET','POST','PUT','PATCH','DELETE','HEAD','OPTIONS'],
    'exposedHeaders' => [],
    'maxAge' => 0,
`

If you have any further clarifications to my inquiry, don't hesitate to ask me. I've been dying to resolve this hell of a code. I've done coding it from scratch but it failed.

Thanks and hope you can help me.

**Comment by lobastovk** [comment]
Worked for me
```
['supportsCredentials' => false,
    'allowedOrigins' => ['http://localhost:4200'],
    'allowedOriginsPatterns' => [],
    'allowedHeaders' => ['Origin', 'Content-Type', 'Authorization'],
    'allowedMethods' => ['GET', 'POST', 'PUT', 'DELETE', 'OPTIONS'],
    'exposedHeaders' => [],
    'maxAge' => 0,]
```

**Comment by johnray21216** [comment]
Already resolved it by adding a origin in my jsdom instance on my config. Thanks for the response though.

**Comment by abinadave** [comment]
@johnray21216 ,
How did you solve this? Pls reply  Thanks
Pls post the code. im also having an issue .
