### ISSUE TITLE
Laravel 5.7 POST request, response blocked even if 200 ok status

### ISSUE THREAD

**Issue by suicodave** [barryvdh/laravel-cors#345]
cors version: ^0.11.2
laravel : 5.7

I am having trouble with my angular app whenever i use post method, the request is successful but i am not getting response from the server. Thus my http call will fallback to the error block which is not expected.
![cors conf](https://user-images.githubusercontent.com/28585323/47782810-13841680-dd3c-11e8-90e3-1ab74fa82697.PNG)
![actual network tab](https://user-images.githubusercontent.com/28585323/47782812-13841680-dd3c-11e8-8875-00871c1b3245.PNG)
![cors network tab](https://user-images.githubusercontent.com/28585323/47782813-141cad00-dd3c-11e8-8966-1b7d4e84141e.PNG)
![cors error](https://user-images.githubusercontent.com/28585323/47782816-141cad00-dd3c-11e8-91f4-5fe16777ec36.PNG)

**Comment by suicodave** [comment]
After many times of debugging, turns out that the laravel's dump() function is causing the issue, I thought that I am safe using dump() because of laravel's new dump-server but then again I have to remove it somewhere in my controller which is handling a post request

**Comment by briancaldass** [comment]
> After many times of debugging, turns out that the laravel's dump() function is causing the issue, I thought that I am safe using dump() because of laravel's new dump-server but then again I have to remove it somewhere in my controller which is handling a post request

Could you explain this part well? I do not understand the issue of the dump function, I have the same problem

**Comment by suicodave** [comment]
> > After many times of debugging, turns out that the laravel's dump() function is causing the issue, I thought that I am safe using dump() because of laravel's new dump-server but then again I have to remove it somewhere in my controller which is handling a post request
> 
> Could you explain this part well? I do not understand the issue of the dump function, I have the same problem

I do not know what makes the cors throw  an error until i found out in my controller@store I had a single line of dump($dataHere). I removed it and tested out,now the error was resolved, put it back again and the error reproduces so I concluded this was the bug I was looking for.
