### ISSUE TITLE
hi i have problem cors laravel 5.7 with ionic 3 

### ISSUE THREAD

**Issue by alimuhnad** [barryvdh/laravel-cors#350]
ithe problem if i delete the 
    headers.append('Content-Type','application/json');
    headers.append('Access-Control-Allow-Methods', '*');
    headers.append('Access-Control-Allow-Origin' , '*');
    headers.append('Accept','application/json');
form ionic it will send form data not json data 
and if i put it agen its give me cors error as u see
neeed help 

![2018-12-14_2-15-01](https://user-images.githubusercontent.com/29497197/50040611-c0200c00-fffb-11e8-8903-f826a867b67e.png)
![2018-12-14_2-18-25](https://user-images.githubusercontent.com/29497197/50040612-c0200c00-fffb-11e8-81c8-5e977c9cbb0d.png)
![2018-12-14_10-14-02](https://user-images.githubusercontent.com/29497197/50040613-c0200c00-fffb-11e8-9c81-c038f7b09811.png)

**Comment by Overx** [comment]
i have same problem

**Comment by Nata22197** [comment]
Para solucionar esto  debes Habilitar el proxy de Ionic 3 ya que en los navegadores siempre tendras inconvenientes con CORS si quieres ejecutar ionic serve.
**en tu archivo ionic.config.json has esto al final:**
```
"v3": true,
  "proxies": [
    {
      "path": "/api/",
      "proxyUrl": "http://example.com/api"
    }
  ]

```
**luego modifica las URL en tus `providers**`
```
 let url = 'api/';
this.http.post(url, JSON.stringify(info), {headers: headers}).....
```
Saludos!

**Comment by sims34** [comment]
Gracias @Nata22197voy a probar esto,
la próxima vez en inglés si puedes
me salvará de traducir todo a la traducción de google :smile:  :laughing:

**Comment by Nata22197** [comment]
De nada 👌🏼

**Comment by alimuhnad** [comment]
in english plzzzzzz

**Comment by alimuhnad** [comment]
> Para solucionar esto debes Habilitar el proxy de Ionic 3 ya que en los navegadores siempre tendras inconvenientes con CORS si quieres ejecutar ionic serve.
> **en tu archivo ionic.config.json has esto al final:**
> 
> ```
> "v3": true,
>   "proxies": [
>     {
>       "path": "/api/",
>       "proxyUrl": "http://example.com/api"
>     }
>   ]
> ```
> **luego modifica las URL en tus `providers**`
> 
> ```
>  let url = 'api/';
> this.http.post(url, JSON.stringify(info), {headers: headers}).....
> ```
> Saludos!

its works thanks i ll tryit on real device
