### ISSUE TITLE
Request has been blocked by CORS policy if used headers multipart/form-data Vue, Laravel, Axios

### ISSUE THREAD

**Issue by Seeman13** [barryvdh/laravel-cors#356]
Issue resolved

**Comment by Seeman13** [comment]
With multipart/form-data server response:

Request Method: OPTIONS

Status Code: 200 OK
Response headers:
Access-Control-Allow-Headers: AUTHORIZATION
Access-Control-Allow-Methods: POST
Access-Control-Allow-Origin: http://my-site.loc:8080
Cache-Control: no-cache, private
Connection: close
Content-Length: 0
Content-Type: text/html; charset=UTF-8
Date: Tue, 19 Mar 2019 19:05:24 GMT
Server: Apache

Request Method: POST

Status Code: 200 OK
Response headers:
Connection: Keep-Alive
Content-Type: text/html; charset=UTF-8
Date: Tue, 19 Mar 2019 19:05:24 GMT
Keep-Alive: timeout=10, max=100
Server: Apache
Transfer-Encoding: chunked
Vary: Authorization

Request Headers:

Accept: application/json
Accept-Encoding: gzip, deflate
Accept-Language: ru-RU,ru;q=0.9,en-US;q=0.8,en;q=0.7
Authorization: Bearer .........
Connection: keep-alive
Content-Length: 763
Content-Type: multipart/form-data
Host: my-site.loc
Origin: http://my-site.loc:8080
Referer: http://my-site.loc:8080/profile/add-card
User-Agent: Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/70.0.3538.77 Safari/537.36


What am I doing wrong???? Help me! Please!

**Comment by perez0711** [comment]
Post your code pls.

**Comment by Seeman13** [comment]
As I expected, the solution was simple and lay on the surface.
When sending files to the server, you cannot use the object, but you need to use the special data format of the object, or use the solution with XMLHttpRequest.

Before:

`this.$http.post('api/my-action', {formData}, {
headers: { 'Content-Type': 'multipart/form-data' }
})
.then(response => {
    console.log(response)
}).catch(error => {
    throw error
})`

After (without {} ):

`this.$http.post('api/my-action', formData, {
headers: { 'Content-Type': 'multipart/form-data' }
})
.then(response => {
    console.log(response)
}).catch(error => {
    throw error
})`

Example working solution:

in Kernel.php:
protected $middlewareGroups = [
	.......
	'api' => [
		'throttle:60,1',
		'bindings',
	   .....
		\Barryvdh\Cors\HandleCors::class
	]
];
	
// In action Vue
.....
const formData = new FormData()
formData.append('someDataFromForm', JSON.stringify(someDataFromForm)) // object
formData.append('otherDataFromForm', JSON.stringify(otherDataFromForm)) // object

// many images from form
for (let i = 0; i < this.card.images.length; i++) {
  formData.append('images[' + i + ']', this.card.images[i])
}

// one image from form
formData.append('image', this.card.image)

this.$http.post('api/my-action', formData, {// without {}
headers: { 'Content-Type': 'multipart/form-data' }
})
.then(response => {
   console.log(response)
}).catch(error => {
   throw error
})


In action Laravel

// data for table
$someDataFromForm = json_decode($request->input('someDataFromForm'), true);
Validator::make($someDataFromForm, Model::$rules)->validate();

// data for join table
$otherDataFromForm = json_decode($request->input('otherDataFromForm'), true);
Validator::make($cardPriceRequest, OtherJoinTable::$rules)->validate();


// images
if($images = $request->file('images')) {
	$validator = Validator::make (\Input::all(), [
		'images.*' => 'mimes:jpeg,jpg|max:5000'
		/*dimensions:max_width=,max_height=*/
	]);
	$validator->setAttributeNames(Model::$attributeLabels);
	$validator->validate();

	foreach($images as $image) {
		// there upload images
	}
}

// image
if ($request->hasFile('image')) {
	$validator = Validator::make (\Input::all(), ['image' => 'mimes:jpeg,jpg|max:5000']);
	$validator->setAttributeNames(Card::$attributeLabels);
	$validator->validate();
	
	// .....
}

something like this :-)

**Comment by azonedev** [comment]
> Issue resolved

how you fixed the issue?
