### ISSUE TITLE
Error In Service Provider

### ISSUE THREAD

**Issue by djdivesh007** [barryvdh/laravel-cors#375]
Symfony\Component\Debug\Exception\FatalThrowableError
Argument 1 passed to Asm89\Stack\CorsService::__construct() must be of the type array, null given, called in /vendor/barryvdh/laravel-cors/src/ServiceProvider.php on line 37
![Screenshot at Oct 03 00-40-04](https://user-images.githubusercontent.com/42273410/66074253-68489680-e576-11e9-9427-e9839bfdfa08.png)

**Comment by nemixe** [comment]
why this was closed ?, how to solve this ?

**Comment by nemixe** [comment]
fixed after run `php artisan optimize`
