### ISSUE TITLE
simply does not work

### ISSUE THREAD

**Issue by VickG** [barryvdh/laravel-cors#44]
I followed the installation procedure. I am getting the same error. 

Please advise.

**Comment by andybeak** [comment]
I can confirm that it does work with my current Laravel 5 installation.  

The problems that I did encounter were as a result of my javascript calls.  

I'm running nginx/hhvm and did not need to make any server configuration changes.

**Comment by esneeringer** [comment]
I have it up and running with Laravel 5 as well.

**Comment by jbrooksuk** [comment]
Duplicate of #39?

**Comment by sicsol** [comment]
I'm getting the following error. I'm using an angular project to make the call. 

I'm using the default cors.php configuration file with L5

`XMLHttpRequest cannot load http://localhost:8000/api/auth/staff. No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'http://localhost:8100' is therefore not allowed access. The response had HTTP status code 500.`

**Comment by sicsol** [comment]
I figures it out. It was because of my CSRF token mismatch

**Comment by jauma** [comment]
@sicsol can you explain what you did?

**Comment by sicsol** [comment]
in kernel.php i did the following

`	protected $middleware = [
		'Illuminate\Foundation\Http\Middleware\CheckForMaintenanceMode',
		'Illuminate\Cookie\Middleware\EncryptCookies',
		'Illuminate\Cookie\Middleware\AddQueuedCookiesToResponse',
		'Illuminate\Session\Middleware\StartSession',
		'Illuminate\View\Middleware\ShareErrorsFromSession',
		// 'App\Http\Middleware\VerifyCsrfToken',
	];

	/**
	 * The application's route middleware.
	 *
	 * @var array
	 */
	protected $routeMiddleware = [
		'auth' => 'App\Http\Middleware\Authenticate',
		'auth.basic' => 'Illuminate\Auth\Middleware\AuthenticateWithBasicAuth',
		'guest' => 'App\Http\Middleware\RedirectIfAuthenticated',
   'jwt.auth' => 'Tymon\JWTAuth\Middleware\GetUserFromToken',
    'jwt.refresh' => 'Tymon\JWTAuth\Middleware\RefreshToken',
    'csrf' => 'App\Http\Middleware\VerifyCsrfToken',
	];
`

**Comment by barryvdh** [comment]
See https://github.com/barryvdh/laravel-cors#disabling-csrf-protection-for-your-api
