### ISSUE TITLE
Can't install for Laravel 5.1

### ISSUE THREAD

**Issue by koorb** [barryvdh/laravel-cors#45]
I realise 5.1 isn't actually released yet. But it's so close I am developing a new project with it. I'm just wondering if laravel-cors requirement for `illuminate/support` needs to be so specific `~5.0.17` as composer won't install it with laravel 5.1. `tymon/jwt-auth` for example requires `~5.0.x` which composer seems happier with.

**Comment by barryvdh** [comment]
Should be fixed.

**Comment by koorb** [comment]
Fantastic thank you
