### ISSUE TITLE
Tag for version 0.7.x missing

### ISSUE THREAD

**Issue by mipaca** [barryvdh/laravel-cors#47]
There doesn't seem to be a tag for version 0.7.0. I tried using the install instructions but couldn't get the 0.7.0 version to install unless I used dev-master in my composer.json
![error-when-using-command-in-readme](https://cloud.githubusercontent.com/assets/4368971/8297981/f4011300-191f-11e5-8263-460c3c91fd54.png)

**Comment by barryvdh** [comment]
Try '0.7.x@dev'

**Comment by mipaca** [comment]
Using this line did work to load the latest:
composer require barryvdh/laravel-cors 0.7.x@dev

Following the read me install instructions exactly causes the error I previously included.

**Comment by barryvdh** [comment]
Yeah I should tag a release. Will do tomorrow if I remember ;)

**Comment by barryvdh** [comment]
Tagged
