### ISSUE TITLE
The 'Access-Control-Allow-Origin' header contains multiple values, but only one is allowed.

### ISSUE THREAD

**Issue by michalsnik** [barryvdh/laravel-cors#48]
I'm running into this issue while requesting api in my ionic application. 

Removing two lines in stack-cors package:
$response->headers->set('Access-Control-Allow-Origin', $request->headers->get('Origin'));
solves my problem, but there has to be a better solution.

I'm using default config/cors.php file

**Comment by barryvdh** [comment]
You probably have `header("Access-Control-Allow-Origin: *");` somewhere, or something similar in your .htaccess file?

**Comment by michalsnik** [comment]
It turned out i was using dev-master version of laravel-cors, beacause there is no 0.7.x as readme says. I installed 0.6.x, added provider in app, middleware and route middleware in kernel, and now it works like a chram.
But going back to this issue, I removed all acces-control-allow-origin in my project and left only those in default config, but problem still occured.

**Comment by Vinlock** [comment]
I found that my nginx config in my docker container had `add_header` lines in it. Removing these fixed my problem.

**Comment by ajithxmedia** [comment]
Access to XMLHttpRequest at 'https://web123.com/Ajith/login2.php' from origin 'http://localhost:8100' has been blocked by CORS policy: Response to preflight request doesn't pass access control check: The 'Access-Control-Allow-Origin' header contains multiple values '*, *', but only one is allowed.



how solve this error.....pls

**Comment by ebobadilla** [comment]
Header always set Access-Control-Allow-Origin: "*"
