### ISSUE TITLE
5.1, middleware doesn't appear to be working?

### ISSUE THREAD

**Issue by JoeDawson** [barryvdh/laravel-cors#49]
Hello,

I've used this package previously in 4.2 and it  worked perfectly.

I'm now trying to use it with 5.1, but the middleware doesn't appear to be doing anything? Is it something still being worked on?

**Comment by jandetlefsen** [comment]
Confirm, same here.
Tried adding it to protected $routeMiddleware in Kernel.php but still have a blank response when requesting the OPTIONS endpoint.

**Comment by joelvanpatten** [comment]
I have the same problem.  I tried adding 'Barryvdh\Cors\HandleCors' to the global $middleware array, but it is not sending any headers.  My config is unchanged from the default install.

**Comment by jandetlefsen** [comment]
beginning to suspect that it was an update from L5.0 to L5.1 that wasn't cleanly executed, trying a clean install of L5.1 now.

**Comment by joelvanpatten** [comment]
I am not sure what changed, but suddenly it is working for me now?!?

**Comment by barryvdh** [comment]
I didn't change anything. But you have to watch out for errors that stop the headers from sending. And that it's an actual CORS request you're testing, otherwise the headers also aren't added.

**Comment by nezaboravi** [comment]
ErrorException in routes.php line 29:
Argument 1 passed to App\Providers\RouteServiceProvider::{closure}() must be an instance of Router, instance of Illuminate\Routing\Router given

**Comment by barryvdh** [comment]
Is that from this lib? Just remove the typehint to Router.
In Lumen, it's an Application instance instead of router.

**Comment by druidajes** [comment]
Route::get('api', ['uses' => 'ApiController@index','middleware'=>'cors']);

**Comment by cmack** [comment]
I just had this issue too. The solution for me was on the AJAX side of things. In short, the queries must supply the 'Origin' header since the middleware checks the request with the following:

https://github.com/asm89/stack-cors/blob/master/src/Asm89/Stack/CorsService.php#L54

In my case, with jQuery, I passed 'crossDomain: true' in the `$.ajax` config and the middleware worked as expected. This may warrant a blurb in the 'Common Problems' section

**Comment by duongtdvn** [comment]
Mine has the same issue, all configuration seem not applied so I have to add these line in bootstrap/app.php
<pre>
header('Access-Control-Allow-Headers: Origin, Content-Type, x-access-token, Authorization');
header('Access-Control-Allow-Methods: GET, POST, PUT, PATCH');
</pre>
and everything get back to normal, but this just for temporary, still need a solution.

**Comment by epicsurf** [comment]
cmack's  solution worked for me as well however I'm using straight javascript (no jquery) so the setting the header to include "Origin" resolved the issue:

 xhr.setRequestHeader('Content-Type', 'application/x-www-form-urlencoded', 'Origin');

**Comment by jonesnc** [comment]
I'm also getting a similar error:   

```
Argument 1 passed to Barryvdh\Cors\HandleCors::__construct() must be an instance of Asm89\Stack\CorsService, instance of Illuminate\Foundation\Application given, called in C:\Users\Nathan\projects\iep-printing-php\vendor\laravel\framework\src\Illuminate\Foundation\ProviderRepository.php on line 150 and defined
```

This is with a plain laravel project with `'Barryvdh\Cors\HandleCors',` added to the providers array in `config/app.php` -- I haven't even added anything to the `routes.php` file that references cors and I still get this error.

**Comment by mikehenken** [comment]
I am having the same issue. @jonesnc you added the middleware to the wrong place. 'Barryvdh\Cors\ServiceProvider' should be added in app.php providers array.
'Barryvdh\Cors\HandleCors' should be added in Kernel.php

**Comment by codingquark** [comment]
If I add 'Barryvdh\Cors\HandleCors' in app/Http/Kernel.php's global middleware array, won't that make the whole app to accept requests from any origin?

Also, when I put it in $routeMiddleware array, it doesn't work. However, everything seems to work fine when added to Global middleware.

**Comment by codingquark** [comment]
Seems like it is fixed. Would have been some issue with cache or class loader.

**Comment by rochapablo** [comment]
+1 #89

**Comment by teufernandesp** [comment]
worked to me  (Route::get('api', ['uses' => 'ApiController@index','middleware'=>'cors']);)

**Comment by prasadmunna** [comment]
Hi guys: i got this error Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at http://portalv1.automationagencydev.com/purchase-priority-pass. (Reason: CORS preflight channel did not succeed).

Colud you please anyone help me?

**Comment by ldco2016** [comment]
I followed:

- Step 1: In terminal for my api, I ran: ```$ composer require barryvdh/laravel-cors```
- Step 2: I went to ```config/app.php``` and added at the very bottom of this code: 

```
'providers' => [

        /*
         * Laravel Framework Service Providers...
         */
        Illuminate\Auth\AuthServiceProvider::class,
        Illuminate\Broadcasting\BroadcastServiceProvider::class,
        Illuminate\Bus\BusServiceProvider::class,
        Illuminate\Cache\CacheServiceProvider::class,
        Illuminate\Foundation\Providers\ConsoleSupportServiceProvider::class,
        Illuminate\Cookie\CookieServiceProvider::class,
        Illuminate\Database\DatabaseServiceProvider::class,
        Illuminate\Encryption\EncryptionServiceProvider::class,
        Illuminate\Filesystem\FilesystemServiceProvider::class,
        Illuminate\Foundation\Providers\FoundationServiceProvider::class,
        Illuminate\Hashing\HashServiceProvider::class,
        Illuminate\Mail\MailServiceProvider::class,
        Illuminate\Notifications\NotificationServiceProvider::class,
        Illuminate\Pagination\PaginationServiceProvider::class,
        Illuminate\Pipeline\PipelineServiceProvider::class,
        Illuminate\Queue\QueueServiceProvider::class,
        Illuminate\Redis\RedisServiceProvider::class,
        Illuminate\Auth\Passwords\PasswordResetServiceProvider::class,
        Illuminate\Session\SessionServiceProvider::class,
        Illuminate\Translation\TranslationServiceProvider::class,
        Illuminate\Validation\ValidationServiceProvider::class,
        Illuminate\View\ViewServiceProvider::class,

        /*
         * Package Service Providers...
         */
        Laravel\Tinker\TinkerServiceProvider::class,

        /*
         * Application Service Providers...
         */
        App\Providers\AppServiceProvider::class,
        App\Providers\AuthServiceProvider::class,
        // App\Providers\BroadcastServiceProvider::class,
        App\Providers\EventServiceProvider::class,
        App\Providers\RouteServiceProvider::class,
        Barryvdh\Cors\HandleCors::class,

    ],
```
- Step 3: I went into ```app/Http/Kernel.php``` and added at the very bottom:

```
class Kernel extends HttpKernel
{
    /**
     * The application's global HTTP middleware stack.
     *
     * These middleware are run during every request to your application.
     *
     * @var array
     */
    protected $middleware = [
        \Illuminate\Foundation\Http\Middleware\CheckForMaintenanceMode::class,
        \Illuminate\Foundation\Http\Middleware\ValidatePostSize::class,
        \App\Http\Middleware\TrimStrings::class,
        \Illuminate\Foundation\Http\Middleware\ConvertEmptyStringsToNull::class,
        \Barryvdh\Cors\HandleCors::class,
    ];
```

When I attempt to run ```php artisan serve``` again, I get this error:

```
[ErrorException]
  Argument 1 passed to Barryvdh\Cors\HandleCors::__construct() must be an instance of Barryvdh\Cors\CorsService, instance of Illuminate\Foundation\Application given, called in
   /Users/danale/Projects/itemapi/vendor/laravel/framework/src/Illuminate/Foundation/ProviderRepository.php on line 208 and defined
```
