### ISSUE TITLE
Add Support for Validator

### ISSUE THREAD

**Issue by a4blue** [barryvdh/laravel-cors#52]
Currently there's no CORS when the Validator throws an error. This is annoying if you want to check which fields are missing

**Comment by barryvdh** [comment]
Is this fixed by https://github.com/barryvdh/laravel-cors/commit/8a907402f44362e9d59e90c91d9f4a9992b514dd ?

**Comment by reinink** [comment]
I can confirm that this is still the case. I just installed `0.8.5` and I'm having the same issues. The work around is to simply handle the validation failure manually, like this:

```php
public function endpoint()
{
    $validator = Validator::make(request()->all(), [
        'first_name' => 'required',
        'last_name' => 'required',
    ]);

    if ($validator->fails()) {
        return response()->json($validator->errors()->getMessages(), 422);
    }

    // continue doing stuff
}
```

**Comment by olriko** [comment]
Same issue

**Comment by p4bl1t0** [comment]
This issue remains
