### ISSUE TITLE
Conflict with dingo/api

### ISSUE THREAD

**Issue by jloosli** [barryvdh/laravel-cors#54]
I don't know if this is a bug on dingo/api or laravel-cors side, or if it's just that I messed up with the implementation, but I built up an api using https://github.com/dingo/api and wanted to use this package to handle the CORS. For some reason, I couldn't ever get the OPTIONS requests to return the correct information when going through the dingo/api. For example, my routes file looked somewhat like the following:

```
$api = app( 'Dingo\Api\Routing\Router' );
$api->version( 'v1',['middleware'=>'cors', function ( $api ) {
    $pong = function () {
        return "pong";
    };
    $api->get( '/ping', $pong );
    $api->put( '/ping', $pong );
    $api->post( '/ping', $pong );
    $api->delete( '/ping', $pong );
}
Route::match(['get','put','update','delete','post'], '/test', ['middleware'=>'cors', 'uses' => function () {
    return "Test";
}] );
```

When running cors requests through the standard laravel route, I didn't have any problems. However, when running through the dingo api router (/ping), the OPTIONS preflight wouldn't return the correct information. I then tried adding `\Barryvdh\Cors\HandleCors::class` to the `$middleware` array in the kernel, and still no luck. I finally got it working by adding both HandleCors and `\Barryvdh\Cors\HandlePreflight::class` to the `$middleware` array, even though it looks like the boot process should be dynamically adding that anyway. 

So, to sum things up, the fix for me is to make the middleware look like the following:

```
    protected $middleware = [
        \\ ... All the normal middleware stuff ... \\
        \Barryvdh\Cors\HandleCors::class,
        \Barryvdh\Cors\HandlePreflight::class
    ];
```

Also, the required composer items are as follows:

```
    "require": {
        "php": ">=5.5.9",
        "laravel/framework": "5.1.*",
        "dingo/api": "~0.10",
        "tymon/jwt-auth": "~0.5",
        "doctrine/dbal": "~2.3",
        "watson/validating": "~1.0",
        "guzzlehttp/guzzle": "~5.0",
        "guzzlehttp/oauth-subscriber": "0.2.*",
        "barryvdh/laravel-cors": "0.7.x"
    },
    "require-dev": {
        "fzaninotto/faker": "~1.4",
        "mockery/mockery": "0.9.*",
        "phpunit/phpunit": "~4.0",
        "phpspec/phpspec": "~2.1",
        "barryvdh/laravel-ide-helper": "^2.0"
    },
```

**Comment by eduacostam** [comment]
Just run into this issue as well, also using dingo/api.
Your fix works for me. Thanks!

**Comment by TUNER88** [comment]
I have the same problem.

@eduacostam thx for your fix!
@barryvdh are there any sideeffects on this workaround?

**Comment by jloosli** [comment]
For what it's worth, I opened the same issue up at https://github.com/dingo/api/issues/576

**Comment by nicolas-t** [comment]
worked for me (:

**Comment by kcalliauw** [comment]
This pull request fixes the issue: https://github.com/barryvdh/laravel-cors/pull/64

**Comment by kcalliauw** [comment]
The PR was tagged, so a composer update should do the trick.

**Comment by jloosli** [comment]
Seems to work for me.

**Comment by tralves** [comment]
This problem fixes for Laravel, but not for Lumen. I couldn't find a solution. 

My workaround was to add ``\Barryvdh\Cors\HandlePreflight::class`` to the list of global middlewares.

**Comment by NightravenJames** [comment]
Failed to load http://127.0.0.1/8000/api/auth/login/: Response to preflight request doesn't pass access control check: No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'http://localhost:8012' is therefore not allowed access.
angular.js:12808 {"method":"POST","url":"http://127.0.0.1/8000/api/auth/login/","message":null,"status":-1} critical true

**Comment by NightravenJames** [comment]
Thats from my angular app , am using  the [laravel dingo boiler plate ](https://github.com/francescomalatesta/laravel-api-boilerplate-jwt) none of the above fixes have worked in fixing the preflight issue PLEASE HELP
