### ISSUE TITLE
documentation confusion: allowedMethods can be set to array('*')

### ISSUE THREAD

**Issue by eidng8** [barryvdh/laravel-cors#57]
In the cors.php config file:

> allowedOrigins, allowedHeaders and allowedMethods can be set to array('*')
> to accept any value, the **allowed methods however have to be explicitly listed**.

The latter statement seems to contradict `allowedMethods can be set to array('*')`

So should I set the `allowedMethods` to

``` php
[
  // ......
  'allowedMethods'      => ['*'],
  // ......
]
```

or

``` php
[
  // ......
  'allowedMethods'      => ['DELETE', 'GET', 'OPTION', 'PATCH', 'POST', 'PUT'],
  // ......
]
```

?

**Comment by codingquark** [comment]
I agree. These two statements are contradictory. We can either set '*' or explicitly define methods. Both cannot be held true.

I think, '*' doesn't work though.
