### ISSUE TITLE
Global exception handling should not be part of this middleware

### ISSUE THREAD

**Issue by lookitsatravis** [barryvdh/laravel-cors#62]
I've been banging my head against the wall trying to figure out why my exceptions are not getting caught by the proper middleware and are instead getting rendered. After a few hours, I narrowed it down to this library, and specifically the block starting here: https://github.com/barryvdh/laravel-cors/blob/master/src/HandleCors.php#L50

We are executing this middleware on a route group which means that it runs *first* before any other middleware. Specifically, we are running this on an Oauth2 authorization route (https://github.com/lucadegasperi/oauth2-server-laravel). This Oauth2 library has it's own middleware for catching it's own request errors and handling them gracefully. However, laravel-cors is catching all exceptions and handling them without giving a chance for any other middlewares to operate on the request.

I understand that this change resulted from this issue (https://github.com/barryvdh/laravel-cors/issues/32) where the headers were not set properly when an exception happens. I think a better way to go about this is to create a custom error handler for laravel-cors which would take the place of `App\Exceptions\Handler`. Or, possibly add a method that could be added to the `handle()` method in an existing handler which dealt with adding the proper headers. I am of the opinion that it is not the responsibility of `laravel-cors` to catch errors and render them. All that should happen is laravel-cors takes care of any headers that need to be set for the request. Global exception handling should be out of scope.

**Comment by lookitsatravis** [comment]
Looks like the ability already exists to add the headers to the exception handler (https://github.com/barryvdh/laravel-cors/blob/master/readme.md#debugging-errors). So, ultimately, this is a vote to revert 8a907402f44362e9d59e90c91d9f4a9992b514dd.

**Comment by barryvdh** [comment]
Hmm, it's just really annoying, because most users don't have a clue what's causing the errors. Ideally I would just queue the headers or something. But I can understand the issue.

**Comment by lookitsatravis** [comment]
Yeah, I can certainly see the tough spot. The issue at hand is that the Oauth2 exception handling middleware is returning a JsonResponse on a error. This prevents the possibility of "after" code running which ensures the proper CORS headers. It's really a limitation of Laravel 5 Middleware in place of before/after filters which separated the functionality in L4 and allowed responses, even error responses, to be mutated. I'm going to spend some time thinking about what can be done without being too hacky. If I come up with something, I'll update this thread.

**Comment by lookitsatravis** [comment]
@barryvdh I did come up with a relatively sound solution that should allow headers to be set without requiring laravel-cors to handle errors. As you can see below, I've added an event listener which listens for the "kernel.handled" event. This event is dispatched after the request makes its way through the entire routing pipeline (see here: https://github.com/laravel/framework/blob/5.1/src/Illuminate/Foundation/Http/Kernel.php#L100). We simply add the headers to the response reference in the callback. What do you think? I can submit a PR if this passes scrutiny.

```php
<?php namespace Barryvdh\Cors;

use Closure;
use Asm89\Stack\CorsService;
use Illuminate\Contracts\Debug\ExceptionHandler;
use Illuminate\Contracts\Events\Dispatcher;

class HandleCors
{
    /**
     * The Exception Handler
     *
     * @var ExceptionHandler
     */
    protected $exceptionHandler;

    /**
     * The CORS service
     *
     * @var CorsService
     */
    protected $cors;

    /**
     * The Event Dispatcher
     *
     * @var Dispatcher
     */
    protected $dispatcher;

	/**
	 * @param CorsService $cors
	 */
	public function __construct(CorsService $cors, ExceptionHandler $exceptionHandler, Dispatcher $dispatcher)
	{
		$this->cors = $cors;
		$this->exceptionHandler = $exceptionHandler;
		$this->dispatcher = $dispatcher;
	}

	/**
	 * Handle an incoming request. Based on Asm89\Stack\Cors by asm89
	 * @see https://github.com/asm89/stack-cors/blob/master/src/Asm89/Stack/Cors.php
	 *
	 * @param  \Illuminate\Http\Request  $request
	 * @param  \Closure  $next
	 * @return mixed
	 */
	public function handle($request, Closure $next)
	{
		if ($this->isSameDomain($request) || ! $this->cors->isCorsRequest($request)) {
			return $next($request);
		}

		if ( ! $this->cors->isActualRequestAllowed($request)) {
			abort(403);
		}

        $cors = $this->cors;

        $this->dispatcher->listen('kernel.handled', function($request, $response) use ($cors) {
            $cors->addActualRequestHeaders($response, $request);
        });

	    return $next($request);
	}

	/**
	 * @param  \Illuminate\Http\Request  $request
	 * @return bool
	 */
	protected function isSameDomain($request)
	{
		return $request->headers->get('Origin') == $request->getSchemeAndHttpHost();
	}
}
```

**Comment by barryvdh** [comment]
Yeah I used that in a previous version, not sure why I removed it, but I thought it wasn't totally reliable (and doesn't work on Lumen). Will try around a bit.

**Comment by lookitsatravis** [comment]
I wonder if it's worth it to have a separate handler for Lumen? I know it's not ideal from a DRY perspective, but...it could still get the job done.

Hey, I haven't said thanks yet. But, I really appreciate this package and all of your others. Thanks for the work you do. It's often thankless.

**Comment by franciscpd** [comment]
I also appreciate the packages developed by you, but I have this same problem, managed to solve the code that fellow posted above.

**Comment by barryvdh** [comment]
I've removed the error handling, the dispatched didn't seem reliable also..

**Comment by lulzimfazlija** [comment]
I am using Laravel 5.0.35 and laravel-cors 0.7.3 and i have this problem with cors, the cors package does not let laravel throw exception but instead i keep getting that origin not allowed... Did by any chance anyone got to fix that annyoing error.. its been three days i  ant fix.. i also try to remove the whole package and just add to public/index.php cross origin * still no luck :s
