### ISSUE TITLE
Returned HTTP headers are lowercase

### ISSUE THREAD

**Issue by Endlessline** [barryvdh/laravel-cors#66]
Using laravel-cors 0.7.0 , laravel v5.1.17 . My cors config is (I've tried messing with the OPTIONS, doesn't seem to effect anything). :squirrel:

(Response Headers)
access-control-allow-headers:ACCEPT, CONTENT-TYPE
access-control-allow-methods:GET, POST, PUT, DELETE, OPTIONS
access-control-allow-origin:http://lp.dev

``` php
<?php

return [
    /*
     |--------------------------------------------------------------------------
     | Laravel CORS
     |--------------------------------------------------------------------------
     |

     | allowedOrigins, allowedHeaders and allowedMethods can be set to array('*') 
     | to accept any value, the allowed methods however have to be explicitly listed.
     |
     */
    'supportsCredentials' => false,
    'allowedOrigins' => [env('MARKETING_DOMAIN',null)],
    'allowedHeaders' => ['*'],
    'allowedMethods' => ['GET', 'POST', 'PUT','DELETE','OPTIONS'],
    'exposedHeaders' => [],
    'maxAge' => 0,
    'hosts' => [],
];
```

**Comment by alephnot** [comment]
Bump, same issue here on 0.7-dev.

**Comment by jbrooksuk** [comment]
We've also had this reported on Cachet's repo. https://github.com/CachetHQ/Cachet/issues/1391

**Comment by moay** [comment]
Confirm. For me too on 0.7.3.

**Comment by devboxr** [comment]
Was this ever fixed?

**Comment by envision** [comment]
https://github.com/barryvdh/laravel-cors/issues/238
