### ISSUE TITLE
Question: Using laravel-cors in combination with default Laravel 4 controllers

### ISSUE THREAD

**Issue by tristangodfrey** [barryvdh/laravel-cors#68]
Hi guys, can anyone confirm that laravel-cors doesn't actually apply anything to default Laravel controllers? I'm using the generated RemindersController for resetting passwords etc., but for some reason chrome is giving me CORS errors on these specific routes. Everything else on other routes works fine without CORS errors, any ideas? I'm using Laravel 4.

Thanks in advance.

**Comment by aleciten** [comment]
It's kind of strange because the documentation would have you think differently. But on every request in which the browser sends the "Origin" header, the middleware will be active. Even though your paths configuration doesn't have the path specified.
