### ISSUE TITLE
Response headers are not set on error pages

### ISSUE THREAD

**Issue by guilhermecvm** [barryvdh/laravel-cors#69]
Whenever laravel returns an error response, for example

``` php
abort(404);
```

the response headers (Access-Control-Allow-Origin...) won't set, resulting in cors error. How to turn response headers on error pages too?

**Comment by webkenny** [comment]
I am fairly sure this is an error we are running into as well. I just noticed it.

**Comment by webkenny** [comment]
Ah, of course. Checking the bottom of the docs gives us the solution...

```
public function render($request, Exception $e)
{
    $response = parent::render($request, $e);

    if ($request->is('api/*')) {
        app('Asm89\Stack\CorsService')->addActualRequestHeaders($response, $request);
    }

    return $response;
}
```

Modify for your use case. Theoretically you could change the is clause to `*` so it runs for everything if you're building a straight API.

**Comment by guilhermecvm** [comment]
@webkenny thanks a lot didn't read the docs 'til the bottom
