### ISSUE TITLE
Error 500 with oauth2-server-laravel

### ISSUE THREAD

**Issue by guilhermegonzaga** [barryvdh/laravel-cors#70]
Hello,

I'm having some problems while developing my application ionic / angular + laravel.

When making any request to my API with oauth2-server-laravel + laravel-cors, the answer should be a 401 error, it returns a 500 error.

When the request returns the token, the problem does not happen.

Using POSTMAN, the problem also happens.

I realized that when I take "laravel-cors" package from my API, in POSTMAN works perfectly, but in my Ionic application returns "Access-Control-Allow-Origin".

It would be a problem https://github.com/lucadegasperi/oauth2-server-laravel package or laravel-cors?

Can someone help me?

**Comment by xchilenox** [comment]
I'm having the exactly the same problem.

I'm developing an appication with Ionic/AngularJS + Laravel as the back-end API, and when I make one request where the response supposed to be an 401 error the API returns an error 500.

If the origin in header is the same of the API, the problem not happens, that is why I think this package have something causing the error on the laravel-oauth2 exceptions.

**Comment by guilhermegonzaga** [comment]
It worked for me following the instructions in https://github.com/barryvdh/laravel-cors#debugging-errors

modify app/Exceptions/Handler.php: 
 `public function render($request, Exception $e)
{
    $response = parent::render($request, $e);

    if ($request->is('api/*')) {
        app('Asm89\Stack\CorsService')->addActualRequestHeaders($response, $request);
    }

    return $response;
}`

**Comment by xchilenox** [comment]
I solved this with the code below in app/Exceptions/Handler.php

``` php
if($e instanceof \League\OAuth2\Server\Exception\OAuthException) {
    $data = [
        'error' => $e->errorType,
        'error_description' => $e->getMessage(),
    ];
    return \Response::json($data, $e->httpStatusCode, $e->getHttpHeaders());
}
```

Thanks!

**Comment by jonathanlundstrom** [comment]
THANK YOU!

I've had an issue opened at the [oauth2-server-laravel](https://github.com/lucadegasperi/oauth2-server-laravel) repo, and been working with @vinkla to locate the issue. Just found this thread, which solved my problems. So, thank you very much!

I've posted the solution here as well: https://github.com/lucadegasperi/oauth2-server-laravel/issues/614#issuecomment-163945194.

// Jonathan
