### ISSUE TITLE
Response for preflight has invalid HTTP status code 500

### ISSUE THREAD

**Issue by andrepibo** [barryvdh/laravel-cors#72]
I am developing an API that is gonna be used by a website's front-end and an app.
I am trying to do an ajax call to the API:

```
$.ajax({
  url: 'http://myapi.com/call',
  type: 'GET',
  headers: {'Authorization' : 'Bearer token123'},
  crossDomain: true,
  contentType: 'application/x-www-form-urlencoded; charset=UTF-8',
  success   : function(data) { console.log(data);},
  error: function(xhr) {console.log(xhr)}
});
```

However I got this errro:

```
XMLHttpRequest cannot load http://myapi.com/call. Response for preflight has invalid HTTP status code 500
```

However, when I remove the following line from the request works fine.

headers: {'Authorization' : 'Bearer token123'},

My config/cors.php

```
'supportsCredentials' => false,
'allowedOrigins' => ['*'],
'allowedHeaders' => ['*'],
'allowedMethods' => ['GET', 'POST', 'PUT',  'DELETE', 'OPTIONS'],
'exposedHeaders' => [],
'maxAge' => 0,
'hosts' => [],
```

Any idea about how to solve it?

**Comment by csprocket777** [comment]
Did you have any luck with this?

**Comment by andrepibo** [comment]
No. I am using JWTAuth to perform authentication and it provides an option to send the authentication token through query string, so I adopted this option instead of sending an Authorization header.

**Comment by gradosevic** [comment]
andrepibo, could you please give some insights about what you did exactly to make it work with JWTAuth package? Thanks.
.

**Comment by barryvdh** [comment]
Hmm, it does work for me with authentication. Not sure if this helps? https://medium.com/@barryvdh/oauth-in-javascript-apps-with-angular-and-lumen-using-satellizer-and-laravel-socialite-bb05661c0d5c#.9y7l5aq6g

Did you set `supportsCredentials` to true?

**Comment by gradosevic** [comment]
Thanks, I've managed to resolve this issue, it somehow masked the real issue that I have:

> *XMLHttpRequest cannot load http://domain.dev/page1. The request was redirected to 'http://domain.dev/login', which is disallowed for cross-origin requests that require preflight.*

Basically what I'm doing is making 301 redirection on "page1" to the login page if user is not authenticated, and that's not allowed by CORS. I couldn't find elegant solution for this, and my workaround is that I throw 401 Unauthorized exception on the "page1", catch that with my client JavaScript and make another request from JavaScript to "login" page.
