### ISSUE TITLE
Request header field Content-Type is not allowed by Access-Control-Allow-Headers in preflight response.

### ISSUE THREAD

**Issue by sachintaware** [barryvdh/laravel-cors#74]
I checked the issues section and found a few related to this ,but no concrete solution.
I am sending a request from a static angular app hosted on S3 to my laravel app,for triggering a mail after form submit.

```
 return [
'supportsCredentials' => false,
'allowedOrigins' => ['testsite.example.com'],
'allowedHeaders' => ['Content-Type', 'Accept'],
'allowedMethods' => ['GET', 'POST', 'PUT', 'DELETE', 'OPTIONS'],
'exposedHeaders' => [],
'maxAge' => 0,
'hosts' => [],
```

];

If I keep the default config I get multiple headers error,so I added my domain name explicitly and added the `Options` type. I am getting the error preflight. Added a screenshot of headers below, I get a `laravel-session` cookie but not sure if that is the problem. Can someone throw light on this? using the latest build for the package

![cors](https://cloud.githubusercontent.com/assets/1187801/10906987/39c036b0-824c-11e5-9b12-d5d5981d3443.png)

**Comment by loren138** [comment]
No idea what the issue was, but I swapped my allowedHeaders from what was posted above to `'allowedHeaders' => ['Origin', 'X-Requested-With', 'Content-Type', 'Accept'],` and it started working in Safari.  Safari was complaining about a lack of the content-type header (which it already had in the list), but adding the others made it feel better...

**Comment by sureshbala** [comment]
Facing the same issue. Tried almost all the options other than this package throughout the day but the problem is not resolved. It works absolutely fine with GET methods but when its comes POST, I get the following error. 

`XMLHttpRequest cannot load http://*************Apis/hr/add-employee. Response to preflight request doesn't pass access control check: No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'http://******.com' is therefore not allowed access.`

**Comment by loren138** [comment]
You tried the options in this package or you haven't tried this package yet?  If you are using the package, can you post your config file.  `config/cors.php`

**Comment by sureshbala** [comment]
Hey @loren138 , got this fixed. Your guess was right. I had misconfigured config/cors.php. It is perfect now. Sorry for that & Thanks

**Comment by rdgutierrez** [comment]
@sachintaware can you post you config/cors.php ? because i'm hitting my head with the wall with this problem

**Comment by joaoprado** [comment]
`'supportsCredentials' => false,
    'allowedOrigins' => ['*'],
    'allowedHeaders' => ['Origin', 'X-Requested-With', 'Content-Type', 'Accept', 'X-CSRF-TOKEN'],
    'allowedMethods' => ['*'],
    'exposedHeaders' => [],
    'maxAge' => 0,
    'hosts' => [],`

this is the content of my cors.php and I keep getting the error for anything but GET requests.

Anyone was able to fix this?

**Comment by aliasdoc** [comment]
Hi,

Sorry but I have the same problem, my config file:
```

<?php

return [
    /*
     |--------------------------------------------------------------------------
     | Laravel CORS
     |--------------------------------------------------------------------------
     |

     | allowedOrigins, allowedHeaders and allowedMethods can be set to array('*') 
     | to accept any value, the allowed methods however have to be explicitly listed.
     |
     */
    'allowedOrigins' => ['*'],
    'allowedMethods' => ['GET, POST, PATCH, PUT, DELETE, OPTIONS'],
    //'allowedHeaders' => ['Origin, Content-Type, X-Auth-Token'],
    'allowedHeaders' => ['Origin', 'X-Requested-With', 'Content-Type', 'Accept'],
];


```

My Kernel.php

```

class Kernel extends HttpKernel
{
    /**
     * The application's global HTTP middleware stack.
     *
     * These middleware are run during every request to your application.
     *
     * @var array
     */
    protected $middleware = [
        \Illuminate\Foundation\Http\Middleware\CheckForMaintenanceMode::class,
        \Barryvdh\Cors\HandleCors::class,
    ];

    /**
     * The application's route middleware groups.
     *
     * @var array
     */
    protected $middlewareGroups = [
        'web' => [
            \App\Http\Middleware\EncryptCookies::class,
            \Illuminate\Cookie\Middleware\AddQueuedCookiesToResponse::class,
            \Illuminate\Session\Middleware\StartSession::class,
            \Illuminate\View\Middleware\ShareErrorsFromSession::class,
            //\App\Http\Middleware\VerifyCsrfToken::class,
        ],

        'api' => [
            'throttle:60,1',
        ],
    ];


```

If I add this lines at the top of my public/index.php, it works.

```

header('Access-Control-Allow-Origin: *');
header('Access-Control-Allow-Methods: GET, POST, PATCH, PUT, DELETE, OPTIONS');
header('Access-Control-Allow-Headers: Origin, Content-Type, X-Auth-Token');


```


An idea ??.

Thanks.

**Comment by yoosuf** [comment]
@aliasdoc, what was the error do you get?

**Comment by apoca** [comment]
After put This in index.php:

header('Access-Control-Allow-Origin: *');
header('Access-Control-Allow-Headers: Origin, Content-Type, X-Auth-Token');

it works... but this is a very bad idea... So someone with ideas!?

**Comment by sunehinz** [comment]
Try adding `X-CSRF-TOKEN` to the Access-Control-Allow-Methods.

My complete array of allowed headers are now the following:
`['Origin', 'X-Requested-With', 'Content-Type', 'Accept', 'X-Auth-Token', 'X-CSRF-TOKEN']`

**Comment by itdeveloper-kasih** [comment]
@aliasdoc ideas still works in 2022 lol,
