### ISSUE TITLE
using laravel 5.1.x, the cors doesn't work together with the jwt.auth package

### ISSUE THREAD

**Issue by jestersimpps** [barryvdh/laravel-cors#75]
I am using this middleware together with the jwt.auth package.
in my kernel.php:

``` php
    protected $routeMiddleware = [
        'auth' => \App\Http\Middleware\Authenticate::class,
        'auth.basic' => \Illuminate\Auth\Middleware\AuthenticateWithBasicAuth::class,
        'guest' => \App\Http\Middleware\RedirectIfAuthenticated::class,

        'jwt.auth' => \Tymon\JWTAuth\Middleware\GetUserFromToken::class,
        'jwt.refresh' => \Tymon\JWTAuth\Middleware\RefreshToken::class,

        'cors'=> \Barryvdh\Cors\HandleCors::class


    ];
```

my cors.php

``` php
    'supportsCredentials' => true,
    'allowedOrigins' => ['*'],
    'allowedHeaders' => ['*'],
    'allowedMethods' => ['GET', 'POST', 'PUT',  'DELETE','OPTIONS'],
    'exposedHeaders' => [],
    'maxAge' => 0,
    'hosts' => [],
```

in my routes:

``` php

// unprotected cors routes
Route::group(['prefix' => 'api/v1', 'middleware' => 'cors'], function () {
    // partner authentication
    Route::post('authenticate', 'partnerAuthController@authenticate');

});

// cors Route group for API versioning
Route::group(['prefix' => 'api/v1', 'middleware' => ['cors','jwt.auth']], function () {
    //get authenticated user
    Route::get('authenticate/user', 'partnerAuthController@getAuthenticatedUser');

    // partner data
    Route::resource('partner', 'partnerController');

});
```

cors works until jwt starts adding Authorization and Cookie headers :( 
commented on a previous SO post:
http://stackoverflow.com/questions/33569567/laravel-cors-middleware-fails-for-post-and-resource-request/33571576#33571576

**Comment by SNBSniper** [comment]
Got the same problem, annoying as hell, had to spend like 3 hours of debugging to get to this page where I found out all the effort was in vein, fix any time soon?

**Comment by SpikeO** [comment]
If you are using Apache: (https://github.com/tymondesigns/jwt-auth/wiki/Authentication)
>Apache seems to discard the Authorization header if it is not a base64 encoded user/pass combo. So to fix this you can add the following to your apache config

>RewriteEngine On
RewriteCond %{HTTP:Authorization} ^(.*)
RewriteRule .* - [e=HTTP_AUTHORIZATION:%1]

I also had problems and this solved it for me.

**Comment by jestersimpps** [comment]
adding the middelware in my controller worked as a temporary fix:
```php
    public function __construct()
    {
        $this->middleware('jwt.auth', ['except' => ['<function to exclude from auth>']]);
        $this->middleware('cors');
    }
```

**Comment by bradbird1990** [comment]
Don't know if you guys got CORS working in the end. But this package works for me https://github.com/neomerx/cors-illuminate.

**Comment by codeaken** [comment]
Same problem, solved it by activating CORS for all routes by adding it in the global middleware stack:

    protected $middleware = [
        \Illuminate\Foundation\Http\Middleware\CheckForMaintenanceMode::class,
        \Barryvdh\Cors\HandleCors::class
    ];

Not ideal, but at least works for now until there is a proper fix.

**Comment by larsboldt** [comment]
+1 @codeaken

**Comment by veronesecoms** [comment]
I'm having this problem. Any solution? Put in the $middleware don't work for me, also receiving cors in jwt auth groups routes.
