### ISSUE TITLE
Not work with some resource

### ISSUE THREAD

**Issue by faizshukri** [barryvdh/laravel-cors#79]
I've already put `Barryvdh\Cors\HandleCors::class` into global middleware, and it works well with JSON response, but not font.

`Font from origin 'http://localhost:8000' has been blocked from loading by Cross-Origin Resource Sharing policy: No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'http://localhost:3000' is therefore not allowed access.`

**Comment by trunda** [comment]
Yea sure, there is no way it can work. Font is served statically (by your Apache or Nginx) so the request will not event touch the laravel app. You have to setup Access-Controll headers in web server configuration for static files. Is it understandable?

**Comment by faizshukri** [comment]
Yeah. I realized that just after this issue was created. Done as you mentioned. But I totally forgot that I was created this.

Thanks btw.

**Comment by faizshukri** [comment]
This issue is not related to `laravel-cors` actually. At first I'm using php built in web server for development (`php artisan serve`). So no Apache and no Nginx. Set up header in Apache/Nginx should be easy.

 The right question for this problem is supposed to be:

**How can we add Access-Control header to Laravel Artisan Serve when accessing static files?**

After some googling, found [this](http://stackoverflow.com/questions/20792134/allowing-cors-in-artisan-serve).
