### ISSUE TITLE
Conflict with middleware that returns new response

### ISSUE THREAD

**Issue by jonathanlundstrom** [barryvdh/laravel-cors#83]
Hello!

I'm using this package in combination with [oauth2-server-laravel](https://github.com/lucadegasperi/oauth2-server-laravel/) and I am experiencing some issues with the response headers. As we are using cross-origin requests it's essential that the server allows the clients to query data, this is what we use this package for in the first place.

In this instance, your handleCors. middleware goes to the next middleware (OAuthExceptionHandlerMiddleware) without any response headers, see here: https://github.com/barryvdh/laravel-cors/blob/master/src/HandleCors.php#L42

```
public function handle($request, Closure $next)
{
    if ($this->isSameDomain($request) || ! $this->cors->isCorsRequest($request)) {
        return $next($request);
    }

    if ( ! $this->cors->isActualRequestAllowed($request)) {
        abort(403);
    }

    /** @var \Illuminate\Http\Response $response */
    $response = $next($request); // SEE THIS LINE

    return $this->cors->addActualRequestHeaders($response, $request);
}
```

Since the next middleware encounters an error, it catches it, and create a new response with the error message and correct status code, but I get CORS errors, since the response does not contain the headers. And since [the middleware](https://github.com/lucadegasperi/oauth2-server-laravel/blob/master/src/Middleware/OAuthExceptionHandlerMiddleware.php#L43) returns a new response, the headers never get passed along:

```
public function handle($request, Closure $next)
{
    try {
        return $next($request);
    } catch (OAuthException $e) {
        $data = [
            'error' => $e->errorType,
            'error_description' => $e->getMessage(),
        ];

        return new JsonResponse($data, $e->httpStatusCode, $e->getHttpHeaders()); // SEE THIS LINE
    }
}
```

This all results in this error:
`XMLHttpRequest cannot load http://project.api:8000/feeds/posts/ids. No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'http://project.dev:8000' is therefore not allowed access. The response had HTTP status code 401.`

I'm not sure how to do it, but I need to get this working as CORS needs to work throughout our oauth service. If we return error 400 or 401 we need the clients to be able to handle them appropriately.

Thank you in advance,
Jonathan Lundström

**Comment by christianbartels** [comment]
Same problem here :-/

**Comment by argentinaluiz** [comment]
I create a code to solve the problem in app/Exceptions/Handler.php:
[https://gist.github.com/argentinaluiz/2cc374e74a958798fb46]
Needs comments `\LucaDegasperi\OAuth2Server\Middleware\OAuthExceptionHandlerMiddleware::class` in Kernel.php

**Comment by agustinsantiago** [comment]
If you're adding both middlewares in your routes file, one possible solution is adding the cors middleware first. For example:

Route::group(['middleware' => ['App\Http\Middleware\Authentication', 'cors']], function () {.....}

won't work, whereas

Route::group(['middleware' => ['cors', 'App\Http\Middleware\Authentication']], function () {.....}

will.

Where App\Http\Middleware\Authentication is my custom middleware which handles authentication, creating new Responses.
