### ISSUE TITLE
Caching preflight requests 

### ISSUE THREAD

**Issue by kfirba** [barryvdh/laravel-cors#84]
Hey. 

I've noticed that in my app the preflight requests usually takes more time than the actual request. I did some research and I saw that it's possible to cache the preflight request's response.

We can do so by adding a header (this example is 20 days cache):

`Access-Control-Max-Age: 1728000`

How can I add the header to the request using your package? I'd rather not stack another middleware which will do that.

**Comment by kfirba** [comment]
@barryvdh are you willing to accept PR for that?

**Comment by barryvdh** [comment]
Sure

**Comment by kfirba** [comment]
@barryvdh uhmmm I just went through the source code and saw that you actually already have that implemented. The **maxAge** option is the value for that which defaults to 0.
