### ISSUE TITLE
Not working on IIS 7.5

### ISSUE THREAD

**Issue by mga242** [barryvdh/laravel-cors#86]
Works fine on WAMP but CORS header 'Access-Control-Allow-Origin' missing on IIS 7.5.

**Comment by blakethepatton** [comment]
Were you ever able to figure out why it was not working? I'm having the same issue.

**Comment by mga242** [comment]
No. I ended up getting CORS to work via IIS web.config file. See [https://stackoverflow.com/questions/34748981/laravel-5-2-cors-get-not-working-with-preflight-options](url)

**Comment by blakethepatton** [comment]
Whatever get's the job done :)

**Comment by blakethepatton** [comment]
I was able to fix this. I discovered that IIS by default only enables `get`, `head` and `post` methods. So I was able to fix this by going into IIS->site name->handler mappings->php(if you have multiple versions you'll want to do this for them all)->edit->Request Restrictions->verbs->all verbs. Save, and it should be fixed. At least it fixed my issues.
