### ISSUE TITLE
[fixed] laravel-cors not working

### ISSUE THREAD

**Issue by wembernard** [barryvdh/laravel-cors#87]
We've been spending half a day on this so I thought I could share this with you.
## First thing first

We've installed laravel-cors. When we tried it, we didn't see any change. After reading the code, here's something really important you should know about if you want to test: 

// https://github.com/asm89/stack-cors/blob/master/src/Asm89/Stack/CorsService.php

```
    public function isCorsRequest(Request $request)
    {
        return $request->headers->has('Origin');
    }
```

meaning you need to make sure Header `Origin: http://example.com` is present in your Request.

`laravel-cors` will then check this `Origin` is allowed and Response a `Access-Control-Allow-Origin: http://example.com`
## And it was still not working

Let say you have some Authentication system such as:

```
Route::group(['prefix' => 'api/v1', 'middleware' => ['auth.basic']], function () {
  Route::resource('users', 'Api\UserController');
});
```

If you add the `cors` middleware to the list. You might have:

```
Route::group(['prefix' => 'api/v1', 'middleware' => ['auth.basic', 'cors']], function () {
  Route::resource('users', 'Api\UserController');
});
```

But... `middleware` order is important. You want `cors` used before authentication middleware. Or you might get a `401: Invalid credentials` without any `Access-Control-Allow-Origin: http://example.com`
making your request failing for CORS problems instead of Authentication problems.

The correct solution is:

```
Route::group(['prefix' => 'api/v1', 'middleware' => ['cors', 'auth.basic']], function () {
  Route::resource('users', 'Api\UserController');
});
```
## Final note

I would humbly suggest @barryvdh to add some of this stuff in the README.md since I didn't read anything about Convention on "What is a CORS request?" or any "How it works behind the scene?".

Sincerely yours,

**Comment by jfoliveira** [comment]
:+1: great tips. Thanks a lot!

**Comment by timnolte** [comment]
@wembernard you saved me from insanity. I was missing the `Origin` header on the request and couldn't figure out for the life of me what I was doing wrong. Thanks!

**Comment by barryvdh** [comment]
Feel free to submit a pull request for the docs!

**Comment by kiwina** [comment]
agree should be in the read me just got to that point as well!!

**Comment by madebyryan** [comment]
Following on from the _ordering being importing_. In 5.3, I couldn't get the middleware to work with an unauthenticated (401) response. This was due to the `bindings` middleware inside the group `api`, inside `Kernel.php`. So make sure `cors` is first in that group.
