### ISSUE TITLE
returning error response without Access-Control-Allow-Origin header

### ISSUE THREAD

**Issue by saqueib** [barryvdh/laravel-cors#89]
I am using "dingo/api": "1.0.*@dev". with L 5.1

All below returns are giving only status code with not content in response

```
// returning 401 without origin header
return $this->response->error($user->msg, 401);  

// returning 422 without origin header
return $this->response->error('This email id has been taken.', 422); 
```

and by looking into console I can see below when I miss type the password in login form.

```
XMLHttpRequest cannot load http://domain.com/api/auth/login. 
No 'Access-Control-Allow-Origin' header is present on the requested resource. 
Origin 'http://localhost:3000' is therefore not allowed access. 
The response had HTTP status code 401.
```

All 200 responses are working, OPTIONS request is giving 200 on above `/auth/login` route as well, but when there is error response, no `Access-Control-Allow-Origin` headers were returned.

It was working before, I have moved app to forge, but I don't think that was the issue. sine it works with `Postman`. Do i have to set something for nginx

**Comment by saqueib** [comment]
@barryvdh please have a look, here is my config file

```php
return [
    /*
    |--------------------------------------------------------------------------
    | Laravel CORS
    |--------------------------------------------------------------------------
    |
    | AllowedOrigins, allowedHeaders and allowedMethods can be set to array('*')
    | to accept any value, the allowed methods however have to be explicitly listed.
    |
    */
    'supportsCredentials' => true,
    'allowedOrigins' => ['*'],
    'allowedHeaders' => ['*'],
    'allowedMethods' => ['GET', 'POST', 'PUT',  'DELETE'],
    'exposedHeaders' => [],
    'maxAge' => 0,
    'hosts' => [],
];
```

I also updated my `/app/Exceptions/Handler.php` as suggested in docs, but no luck 

```php
/**
     * Render an exception into an HTTP response.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \Exception  $e
     * @return \Illuminate\Http\Response
     */
    public function render($request, Exception $e)
    {
        if ($e instanceof ModelNotFoundException) {
            $e = new NotFoundHttpException($e->getMessage(), $e);
        }

        $response = parent::render($request, $e);

        if ($request->is('api/*')) {
            app('Asm89\Stack\CorsService')->addActualRequestHeaders($response, $request);
        }

        return $response;
    }
```

**Comment by odranoelBR** [comment]
I have the same problem...

**Comment by saqueib** [comment]
Thanks to @LeBlaaanc https://github.com/dingo/api/issues/576 I have added middleware as global and removed one on `api_routes.php` route group `, 'middleware' => 'cors'` and its started working 

```php
/**
     * The application's global HTTP middleware stack.
     *
     * @var array
     */
    protected $middleware = [
        \Illuminate\Foundation\Http\Middleware\CheckForMaintenanceMode::class,
        \Barryvdh\Cors\HandleCors::class,
        ...
    ];
```

**Comment by Brave-Cheng** [comment]
Thanks @saqueib , I have same problem with this, nice to here

Kernel.php
```php
<?php

namespace App\Http;

use Illuminate\Foundation\Http\Kernel as HttpKernel;

class Kernel extends HttpKernel
{
    /**
     * The application's global HTTP middleware stack.
     *
     * @var array
     */
    protected $middleware = [
        \Illuminate\Foundation\Http\Middleware\CheckForMaintenanceMode::class,
        \App\Http\Middleware\EncryptCookies::class,
        \Illuminate\Cookie\Middleware\AddQueuedCookiesToResponse::class,
        \Illuminate\Session\Middleware\StartSession::class,
        \Illuminate\View\Middleware\ShareErrorsFromSession::class,
        // \App\Http\Middleware\VerifyCsrfToken::class,
        \Illuminate\Foundation\Http\Middleware\CheckForMaintenanceMode::class,
        \Barryvdh\Cors\HandleCors::class,
    ];
```

routes.php
```php
$api = app('Dingo\Api\Routing\Router');

$api->version('v1', function ($api) {
    $api->group(['namespace' => 'App\Http\Controllers'], function($api) {

        // $api->group(['middleware' => 'cors'], function($api) {
            /**
             * Need to close VerifyCsrfToken middleware in Kernel.php
             */
```

**Comment by saqueib** [comment]
@Brave-Cheng I hope its working for you, here is my `Kernel.php` for your reference, your `routes.php` file looks good

`/**
     * The application's global HTTP middleware stack.
     *
     * @var array
     */
    protected $middleware = [
        \Illuminate\Foundation\Http\Middleware\CheckForMaintenanceMode::class,
        \Lexxplain\Http\Middleware\EncryptCookies::class,
        \Barryvdh\Cors\HandleCors::class,
        \Illuminate\Cookie\Middleware\AddQueuedCookiesToResponse::class,
        \Illuminate\Session\Middleware\StartSession::class,
        \Illuminate\View\Middleware\ShareErrorsFromSession::class,
        \Lexxplain\Http\Middleware\VerifyCsrfToken::class
    ];`

**Comment by Brave-Cheng** [comment]
@saqueib thanks a lot

**Comment by rochapablo** [comment]
I'm having the same problem using Laravel 5.1.

I've tried set as the doc said also as @saqueib. None seems have worked.

Normal ajax requests that return 200, worked as well. Been possible see the data that was returned (using debug).

But, when I have any exception (200/400) both return:

```
XMLHttpRequest cannot load http://dev.mysite/playlist/all. No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'http://localhost:3000' is therefore not allowed access.
```

Here's what I have:

cors.php

```
'supportsCredentials' => false,
'allowedOrigins' => ['*'],
'allowedHeaders' => ['*'],
'allowedMethods' => ['*'],
'exposedHeaders' => [],
'maxAge' => 0,
'hosts' => []
```

Kernel

```
protected $middleware = [
    \Illuminate\Foundation\Http\Middleware\CheckForMaintenanceMode::class,
    \Barryvdh\Cors\HandleCors::class
];
```

VerifyCsrfToken

```
protected $except = [
        'localhost:3000/*',
        'http://localhost:3000/*'
    ];
```

Handler

```
public function render($request, Exception $e)
{
  $response = [
    'errors' => 'Sorry, something went wrong.'
  ];

  if (config('app.debug'))
  {
    // Add the exception class name, message and stack trace to response
    $response['exception'] = get_class($e); // Reflection might be better here
    $response['message'] = $e->getMessage();
    $response['trace'] = $e->getTrace();
  }

  // Default response of 400
  $status = 200;

  return response()->json($response, $status);
}
```

So, I don't know what elso to look because every search seems to have same answers.

**Comment by rochapablo** [comment]
I did something pretty dumb, that change the response. Still not working but made the Laravel return twice in one request.

```
Route::group(['middleware' => ''], function() {
    Route::get('/playlist/all', 'Playlist\PlaylistController@all');
});
```

```
{"errors":"Sorry, something went wrong.","exception":"ReflectionException","message":"Class  does not exist"}
{"errors":"Sorry, something went wrong.","exception":"ReflectionException","message":"Class  does not exist"} // junk
```

Anyway... I'll keep looking.

**Comment by mumapu** [comment]
Same here :( do you have any idea to resolve this problem?

**Comment by rochapablo** [comment]
@mumapu unfortunately I did not resolve the problem. I  stop using "Barryvdh\Cors\HandleCors::class" and decided create my own Cors. Well I'm not satisfied but for now it's what I have and it's working.

**Comment by juniorb2ss** [comment]
Same problem.

Need register `\Barryvdh\Cors\HandleCors::class` in global middleware

**Comment by robinwo** [comment]
Same problem here.

Added provider in config/app.php:
`Barryvdh\Cors\ServiceProvider::class`

Config in place & published:
`return [
    'supportsCredentials' => false,
    'allowedOrigins' => ['*'],
    'allowedHeaders' => ['Origin', 'X-Requested-With', 'Content-Type', 'Accept', 'Authorization'],
    'allowedMethods' => ['GET', 'POST', 'PUT',  'DELETE', 'OPTIONS'],
    'exposedHeaders' => [],
    'maxAge' => 0,
    'hosts' => [],
];`

Added as global middleware:
`protected $middleware = [
		\Illuminate\Foundation\Http\Middleware\CheckForMaintenanceMode::class,
		\Illuminate\Cookie\Middleware\EncryptCookies::class,
		\Barryvdh\Cors\HandleCors::class, // Here is CORS
		\Illuminate\Cookie\Middleware\AddQueuedCookiesToResponse::class,
		\Illuminate\Session\Middleware\StartSession::class,
		\Illuminate\View\Middleware\ShareErrorsFromSession::class,
		\App\Http\Middleware\VerifyCsrfToken::class,
];`

OPTIONS returns 200 OK **with headers set** (according to cors settings)
POST returns "No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin is therefore not allowed access." **without headers set**

Am I missing something?

**Comment by ShelterYa** [comment]
I have the same problem
and do as the doc say,but it don`t work anyway.

this is my kernel
```
/**
     * The application's global HTTP middleware stack.
     *
     * @var array
     */
    protected $middleware = [
        \Illuminate\Foundation\Http\Middleware\CheckForMaintenanceMode::class,
        \App\Http\Middleware\EncryptCookies::class,
        \Barryvdh\Cors\HandleCors::class,
        \Illuminate\Cookie\Middleware\AddQueuedCookiesToResponse::class,
        \Illuminate\Session\Middleware\StartSession::class,
        \Illuminate\View\Middleware\ShareErrorsFromSession::class,
    ];
```
and my config\cors.php
```
    'supportsCredentials' => true,
    'allowedOrigins' => [
        'http://localhost',
        'http://localhost:3000',
        'http://localhost:8000',
        'http://localhost:8080',
    ],
    'allowedHeaders' => ['*'],
    'allowedMethods' => ['*'],
    'exposedHeaders' => [],
    'maxAge' => 0,
    'hosts' => [],
```

and I have try to type my own Cors, it don`t work so.

**Comment by ShelterYa** [comment]
After change my own cors, it works!
```
/**
     * Handle an incoming request.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \Closure  $next
     * @return mixed
     */
    public function handle($request, Closure $next)
    {
        //$response= $next($request);  
        $allow_origin = [
            'http://localhost',
            'http://localhost:3000',
            'http://localhost:8000',
            'http://localhost:8080',
        ];

        if(isset($_SERVER['HTTP_ORIGIN']) &&
            in_array($_SERVER['HTTP_ORIGIN'], $allow_origin)) {

            //配置信任的跨域来源
            header('Access-Control-Allow-Origin: ' . $_SERVER['HTTP_ORIGIN']);
            //配置允许发送认证信息 比如cookies（会话机制的前提）
            header('Access-Control-Allow-Credentials: true');
            //允许的自定义请求头
            header('Access-Control-Allow-Headers: X-Requested-With, Content-Type, Secret');
            //信任跨域有效期，秒为单位
            header('Access-Control-Max-Age: 120');
        }
        
        //return $response;
        return $next($request); 
    }
```

**Comment by bealbrown** [comment]
https://stackoverflow.com/questions/46074394/response-with-422-status-code-from-nginx-lacks-access-control-allow-origin-hea
