### ISSUE TITLE
Routes outside of the `cors` group are still accessible cross origin

### ISSUE THREAD

**Issue by adamwathan** [barryvdh/laravel-cors#91]
I'm trying to figure out how this package actually only allows CORS for routes that use the `cors` middleware.

From what I can tell, the flow is something like:

- Incoming OPTIONS  request comes in for some route
- `HandlePreflight` adds the CORS headers _regardless of what the route is_
- The browser then makes the actual request, a POST request say
- If the `cors` middleware is present on that route, it checks to make sure it's coming from an allowed domain otherwise is 403s

What I don't understand, is what happens if the route is _not_ using the `cors` middleware? The allowed origins, methods, and headers were already returned based on the OPTIONS request, so the browser just makes the POST request to whatever URL and it just seems to go through?

The behavior I'm seeing in the network tab of various browsers is super confusing to be honest. If I have my route _outside_ of the CORS middleware, Chrome returns a 200 for the OPTIONS request, then a red response with no status code for the POST request, _but_ the code in that route is 100% executing, the browser is definitely making the request. Sometimes though Chrome returns a 204 instead of a red response, _but_ my AJAX success callbacks don't fire. Safari always returns a red response with no status code, and if memory serves correctly Firefox was doing the same thing.

What am I misunderstanding? How can I actually allow a CORS request to only work on a certain route with this package? It seems like the preflight response allows CORS for the _whole site_, but just doesn't add the right headers for the actual response _following_ the preflight, even though the code in that route still executes.

Brain is turning into goo trying to really get a grip on all this, hah...

**Comment by barryvdh** [comment]
You're probably right, it always gets added for options. It would probably better to check if the route exists with that middleware, bit not sure if it's possible.
Is this a security concern, or what is the actual problem? Cord should still prevent reading output, so combined with csrf tokens, you cannot perform any actions, right?

If this is an issue, we should find a way to fix it.

**Comment by barryvdh** [comment]
Right now, for OPTIONS requests, the Preflight middleware is added in the [ServiceProvider](https://github.com/barryvdh/laravel-cors/blob/e4c4545879f5f00b8595a13fcf8e648b9bfdb40a/src/ServiceProvider.php#L43)
[That middleware](https://github.com/barryvdh/laravel-cors/blob/e4c4545879f5f00b8595a13fcf8e648b9bfdb40a/src/HandlePreflight.php) just adds the headers for the OPTIONS response. created by Laravel; 
That should check if the method actually exists, but doesn't chechk wether that route had cors enabled or not.

If we want to add that, I guess we would do something like:
1. Get route collection ([Router->getRoutes()](https://github.com/laravel/framework/blob/5.1/src/Illuminate/Routing/Router.php#L1390-L1398)
2. Clone the request, modify the METHOD based on the OPTIONS request.
3. Call the [match method](https://github.com/laravel/framework/blob/5.1/src/Illuminate/Routing/RouteCollection.php#L131-L162) on the collection to find a match.
4. Check the middleware for that controller.

But that would complicate it a bit.

Perhaps it would be better to just have a global middleware, where we define a prefix/path/regex to define wether we add CORS or not..

**Comment by adamwathan** [comment]
Thanks for checking this out Barry, much appreciated!

Re: security, I honestly don't know, I think you're right that combined with CSRF you'd be fine.

What you've proposed sounds like how I would've expected it to work (having the global middleware make sure the current request matches a CORS-enabled route). Do you think it would be an expensive thing to have to do on every request?

I don't think I would make use of a prefix/path/regex based solution personally, would prefer to do it with middleware because it feels a lot more idiomatic.

I suppose another solution for my particular case would be to explicitly define the OPTIONS route for the one endpoint I need to expose cross origin, but this wouldn't scale well if you were building something with lots of endpoints that needed to be accessible from another domain.
