### ISSUE TITLE
Just stopped working all together?

### ISSUE THREAD

**Issue by mcblum** [barryvdh/laravel-cors#94]
Hi!

I have the strangest problem and I'm not sure how to figure out what's going on. I wasn't able to get to an exposed header in our front-end app, so I was messing with the config. Turns out I have forgotten to add the new URL to our hosts array, but everything was still working (except for the exposed headers).

So I removed all of the hosts, and everything is still able to connect, which I assume is wrong. How can I see if it's doing anything? Also, any idea what I can do to be able to expose the headers?

Laravel 5.2
Cors 'dev-master'

Thank you!
Matt

**Comment by DSpeichert** [comment]
I believe that empty hosts array == all hosts allowed.
