### ISSUE TITLE
Conclusion: remove symfony/http-foundation v3.0.1

### ISSUE THREAD

**Issue by canfiax** [barryvdh/laravel-cors#95]
Laravel 5.2:

  Problem 1
    - Installation request for barryvdh/laravel-cors ^0.7.3 -> satisfiable by barryvdh/laravel-cors[v0.7.3].
    - Conclusion: remove symfony/http-foundation v3.0.1
    - Conclusion: don't install symfony/http-foundation v3.0.1
    - barryvdh/laravel-cors v0.7.3 requires asm89/stack-cors 0.2.x -> satisfiable by asm89/stack-cors[0.2.0, 0.2.1].

**Comment by canfiax** [comment]
Pulling in dev-master works

**Comment by crwh05** [comment]
I have the same issue and when I try 
$ composer require barryvdh/laravel-cors dev-master
or
$ composer require barryvdh/laravel-cors 0.8.x-dev
or
$ composer require barryvdh/laravel-cors 0.8.x@dev

Here is an example of the error output for dev-master
`$ composer require barryvdh/laravel-cors dev-master
./composer.json has been updated
> php artisan clear-compiled
Loading composer repositories with package information
Updating dependencies (including require-dev)
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Installation request for barryvdh/laravel-cors dev-master -> satisfiable by barryvdh/laravel-cors[dev-master].
    - Conclusion: remove symfony/http-foundation v3.0.1
    - Conclusion: don't install symfony/http-foundation v3.0.1
    - barryvdh/laravel-cors dev-master requires asm89/stack-cors 0.2.x|dev-master -> satisfiable by asm89/stack-cors[0.2.0, 0.2.1].
    - asm89/stack-cors 0.2.0 requires symfony/http-foundation ~2.1 -> satisfiable by`

Any advice on what to try?

**Comment by crwh05** [comment]
I solved it using this https://github.com/barryvdh/laravel-cors/issues/81, The comment by @ssuhat referring to this https://github.com/cachethq/Cachet/blob/master/composer.json#L27-L28

**Comment by barryvdh** [comment]
I removed the dependacy, can you check with `0.8.x@dev`?
