### ISSUE TITLE
Dependency problem. Lumen 5.2.

### ISSUE THREAD

**Issue by glaucomorais** [barryvdh/laravel-cors#96]
Everytime that I try to require the package I got this Composer exit:

> Using version ^0.7.3 for barryvdh/laravel-cors
> ./composer.json has been updated
> Loading composer repositories with package information
> Updating dependencies (including require-dev)
> Your requirements could not be resolved to an installable set of packages.
> 
>   Problem 1
>     - Installation request for barryvdh/laravel-cors ^0.7.3 -> satisfiable by barryvdh/laravel-cors[v0.7.3].
>     - Conclusion: remove symfony/http-foundation v3.0.1
>     - Conclusion: don't install symfony/http-foundation v3.0.1
>     - barryvdh/laravel-cors v0.7.3 requires asm89/stack-cors 0.2.x -> satisfiable by asm89/stack-cors[0.2.0, 0.2.1].
>     - asm89/stack-cors 0.2.0 requires symfony/http-foundation ~2.1 -> satisfiable by symfony/http-foundation[v2.1.0, v2.1.1, v2.1.10, v2.1.11, v2.1.12, v2.1.13, v2.1.2, v2.1.3, v2.1.4, v2.1.5, v2.1.6, v2.1.7, v2.1.8, v2.1.9, v2.2.0, v2.2.1, v2.2.10, v2.2.11, v2.2.2, v2.2.3, v2.2.4, v2.2.5, v2.2.6, v2.2.7, v2.2.8, v2.2.9, v2.3.0, v2.3.1, v2.3.10, v2.3.11, v2.3.12, v2.3.13, v2.3.14, v2.3.15, v2.3.16, v2.3.17, v2.3.18, v2.3.19, v2.3.2, v2.3.20, v2.3.21, v2.3.22, v2.3.23, v2.3.24, v2.3.25, v2.3.26, v2.3.27, v2.3.28, v2.3.29, v2.3.3, v2.3.30, v2.3.31, v2.3.32, v2.3.33, v2.3.34, v2.3.35, v2.3.36, v2.3.37, v2.3.4, v2.3.5, v2.3.6, v2.3.7, v2.3.8, v2.3.9, v2.4.0, v2.4.1, v2.4.10, v2.4.2, v2.4.3, v2.4.4, v2.4.5, v2.4.6, v2.4.7, v2.4.8, v2.4.9, v2.5.0, v2.5.1, v2.5.10, v2.5.11, v2.5.12, v2.5.2, v2.5.3, v2.5.4, v2.5.5, v2.5.6, v2.5.7, v2.5.8, v2.5.9, v2.6.0, v2.6.1, v2.6.10, v2.6.11, v2.6.12, v2.6.13, v2.6.2, v2.6.3, v2.6.4, v2.6.5, v2.6.6, v2.6.7, v2.6.8, v2.6.9, v2.7.0, v2.7.1, v2.7.2, v2.7.3, v2.7.4, v2.7.5, v2.7.6, v2.7.7, v2.7.8, v2.7.9, v2.8.0, v2.8.1, v2.8.2].
>     - asm89/stack-cors 0.2.1 requires symfony/http-foundation ~2.1 -> satisfiable by symfony/http-foundation[v2.1.0, v2.1.1, v2.1.10, v2.1.11, v2.1.12, v2.1.13, v2.1.2, v2.1.3, v2.1.4, v2.1.5, v2.1.6, v2.1.7, v2.1.8, v2.1.9, v2.2.0, v2.2.1, v2.2.10, v2.2.11, v2.2.2, v2.2.3, v2.2.4, v2.2.5, v2.2.6, v2.2.7, v2.2.8, v2.2.9, v2.3.0, v2.3.1, v2.3.10, v2.3.11, v2.3.12, v2.3.13, v2.3.14, v2.3.15, v2.3.16, v2.3.17, v2.3.18, v2.3.19, v2.3.2, v2.3.20, v2.3.21, v2.3.22, v2.3.23, v2.3.24, v2.3.25, v2.3.26, v2.3.27, v2.3.28, v2.3.29, v2.3.3, v2.3.30, v2.3.31, v2.3.32, v2.3.33, v2.3.34, v2.3.35, v2.3.36, v2.3.37, v2.3.4, v2.3.5, v2.3.6, v2.3.7, v2.3.8, v2.3.9, v2.4.0, v2.4.1, v2.4.10, v2.4.2, v2.4.3, v2.4.4, v2.4.5, v2.4.6, v2.4.7, v2.4.8, v2.4.9, v2.5.0, v2.5.1, v2.5.10, v2.5.11, v2.5.12, v2.5.2, v2.5.3, v2.5.4, v2.5.5, v2.5.6, v2.5.7, v2.5.8, v2.5.9, v2.6.0, v2.6.1, v2.6.10, v2.6.11, v2.6.12, v2.6.13, v2.6.2, v2.6.3, v2.6.4, v2.6.5, v2.6.6, v2.6.7, v2.6.8, v2.6.9, v2.7.0, v2.7.1, v2.7.2, v2.7.3, v2.7.4, v2.7.5, v2.7.6, v2.7.7, v2.7.8, v2.7.9, v2.8.0, v2.8.1, v2.8.2].
>     - Can only install one of: symfony/http-foundation[v2.8.0, v3.0.1].
>     - Can only install one of: symfony/http-foundation[v2.8.1, v3.0.1].
>     - Can only install one of: symfony/http-foundation[v2.8.2, v3.0.1].
>     - Can only install one of: symfony/http-foundation[v2.1.0, v3.0.1].
>     - Can only install one of: symfony/http-foundation[v2.1.1, v3.0.1].
>     - Can only install one of: symfony/http-foundation[v2.1.10, v3.0.1].
>     - Can only install one of: symfony/http-foundation[v2.1.11, v3.0.1].
>     - Can only install one of: symfony/http-foundation[v2.1.12, v3.0.1].
>     - Can only install one of: symfony/http-foundation[v2.1.13, v3.0.1].
>     - Can only install one of: symfony/http-foundation[v2.1.2, v3.0.1].
>     - Can only install one of: symfony/http-foundation[v2.1.3, v3.0.1].
>     - Can only install one of: symfony/http-foundation[v2.1.4, v3.0.1].
>     - Can only install one of: symfony/http-foundation[v2.1.5, v3.0.1].
>     - Can only install one of: symfony/http-foundation[v2.1.6, v3.0.1].
>     - Can only install one of: symfony/http-foundation[v2.1.7, v3.0.1].
>     - Can only install one of: symfony/http-foundation[v2.1.8, v3.0.1].
>     - Can only install one of: symfony/http-foundation[v2.1.9, v3.0.1].
>     - Can only install one of: symfony/http-foundation[v2.2.0, v3.0.1].
>     - Can only install one of: symfony/http-foundation[v2.2.1, v3.0.1].
>     - Can only install one of: symfony/http-foundation[v2.2.10, v3.0.1].
>     - Can only install one of: symfony/http-foundation[v2.2.11, v3.0.1].
>     - Can only install one of: symfony/http-foundation[v2.2.2, v3.0.1].
>     - Can only install one of: symfony/http-foundation[v2.2.3, v3.0.1].
>     - Can only install one of: symfony/http-foundation[v2.2.4, v3.0.1].
>     - Can only install one of: symfony/http-foundation[v2.2.5, v3.0.1].
>     - Can only install one of: symfony/http-foundation[v2.2.6, v3.0.1].
>     - Can only install one of: symfony/http-foundation[v2.2.7, v3.0.1].
>     - Can only install one of: symfony/http-foundation[v2.2.8, v3.0.1].
>     - Can only install one of: symfony/http-foundation[v2.2.9, v3.0.1].
>     - Can only install one of: symfony/http-foundation[v2.3.0, v3.0.1].
>     - Can only install one of: symfony/http-foundation[v2.3.1, v3.0.1].
>     - Can only install one of: symfony/http-foundation[v2.3.10, v3.0.1].
>     - Can only install one of: symfony/http-foundation[v2.3.11, v3.0.1].
>     - Can only install one of: symfony/http-foundation[v2.3.12, v3.0.1].
>     - Can only install one of: symfony/http-foundation[v2.3.13, v3.0.1].
>     - Can only install one of: symfony/http-foundation[v2.3.14, v3.0.1].
>     - Can only install one of: symfony/http-foundation[v2.3.15, v3.0.1].
>     - Can only install one of: symfony/http-foundation[v2.3.16, v3.0.1].
>     - Can only install one of: symfony/http-foundation[v2.3.17, v3.0.1].
>     - Can only install one of: symfony/http-foundation[v2.3.18, v3.0.1].
>     - Can only install one of: symfony/http-foundation[v2.3.19, v3.0.1].
>     - Can only install one of: symfony/http-foundation[v2.3.2, v3.0.1].
>     - Can only install one of: symfony/http-foundation[v2.3.20, v3.0.1].
>     - Can only install one of: symfony/http-foundation[v2.3.21, v3.0.1].
>     - Can only install one of: symfony/http-foundation[v2.3.22, v3.0.1].
>     - Can only install one of: symfony/http-foundation[v2.3.23, v3.0.1].
>     - Can only install one of: symfony/http-foundation[v2.3.24, v3.0.1].
>     - Can only install one of: symfony/http-foundation[v2.3.25, v3.0.1].
>     - Can only install one of: symfony/http-foundation[v2.3.26, v3.0.1].
>     - Can only install one of: symfony/http-foundation[v2.3.27, v3.0.1].
>     - Can only install one of: symfony/http-foundation[v2.3.28, v3.0.1].
>     - Can only install one of: symfony/http-foundation[v2.3.29, v3.0.1].
>     - Can only install one of: symfony/http-foundation[v2.3.3, v3.0.1].
>     - Can only install one of: symfony/http-foundation[v2.3.30, v3.0.1].
>     - Can only install one of: symfony/http-foundation[v2.3.31, v3.0.1].
>     - Can only install one of: symfony/http-foundation[v2.3.32, v3.0.1].
>     - Can only install one of: symfony/http-foundation[v2.3.33, v3.0.1].
>     - Can only install one of: symfony/http-foundation[v2.3.34, v3.0.1].
>     - Can only install one of: symfony/http-foundation[v2.3.35, v3.0.1].
>     - Can only install one of: symfony/http-foundation[v2.3.36, v3.0.1].
>     - Can only install one of: symfony/http-foundation[v2.3.37, v3.0.1].
>     - Can only install one of: symfony/http-foundation[v2.3.4, v3.0.1].
>     - Can only install one of: symfony/http-foundation[v2.3.5, v3.0.1].
>     - Can only install one of: symfony/http-foundation[v2.3.6, v3.0.1].
>     - Can only install one of: symfony/http-foundation[v2.3.7, v3.0.1].
>     - Can only install one of: symfony/http-foundation[v2.3.8, v3.0.1].
>     - Can only install one of: symfony/http-foundation[v2.3.9, v3.0.1].
>     - Can only install one of: symfony/http-foundation[v2.4.0, v3.0.1].
>     - Can only install one of: symfony/http-foundation[v2.4.1, v3.0.1].
>     - Can only install one of: symfony/http-foundation[v2.4.10, v3.0.1].
>     - Can only install one of: symfony/http-foundation[v2.4.2, v3.0.1].
>     - Can only install one of: symfony/http-foundation[v2.4.3, v3.0.1].
>     - Can only install one of: symfony/http-foundation[v2.4.4, v3.0.1].
>     - Can only install one of: symfony/http-foundation[v2.4.5, v3.0.1].
>     - Can only install one of: symfony/http-foundation[v2.4.6, v3.0.1].
>     - Can only install one of: symfony/http-foundation[v2.4.7, v3.0.1].
>     - Can only install one of: symfony/http-foundation[v2.4.8, v3.0.1].
>     - Can only install one of: symfony/http-foundation[v2.4.9, v3.0.1].
>     - Can only install one of: symfony/http-foundation[v2.5.0, v3.0.1].
>     - Can only install one of: symfony/http-foundation[v2.5.1, v3.0.1].
>     - Can only install one of: symfony/http-foundation[v2.5.10, v3.0.1].
>     - Can only install one of: symfony/http-foundation[v2.5.11, v3.0.1].
>     - Can only install one of: symfony/http-foundation[v2.5.12, v3.0.1].
>     - Can only install one of: symfony/http-foundation[v2.5.2, v3.0.1].
>     - Can only install one of: symfony/http-foundation[v2.5.3, v3.0.1].
>     - Can only install one of: symfony/http-foundation[v2.5.4, v3.0.1].
>     - Can only install one of: symfony/http-foundation[v2.5.5, v3.0.1].
>     - Can only install one of: symfony/http-foundation[v2.5.6, v3.0.1].
>     - Can only install one of: symfony/http-foundation[v2.5.7, v3.0.1].
>     - Can only install one of: symfony/http-foundation[v2.5.8, v3.0.1].
>     - Can only install one of: symfony/http-foundation[v2.5.9, v3.0.1].
>     - Can only install one of: symfony/http-foundation[v2.6.0, v3.0.1].
>     - Can only install one of: symfony/http-foundation[v2.6.1, v3.0.1].
>     - Can only install one of: symfony/http-foundation[v2.6.10, v3.0.1].
>     - Can only install one of: symfony/http-foundation[v2.6.11, v3.0.1].
>     - Can only install one of: symfony/http-foundation[v2.6.12, v3.0.1].
>     - Can only install one of: symfony/http-foundation[v2.6.13, v3.0.1].
>     - Can only install one of: symfony/http-foundation[v2.6.2, v3.0.1].
>     - Can only install one of: symfony/http-foundation[v2.6.3, v3.0.1].
>     - Can only install one of: symfony/http-foundation[v2.6.4, v3.0.1].
>     - Can only install one of: symfony/http-foundation[v2.6.5, v3.0.1].
>     - Can only install one of: symfony/http-foundation[v2.6.6, v3.0.1].
>     - Can only install one of: symfony/http-foundation[v2.6.7, v3.0.1].
>     - Can only install one of: symfony/http-foundation[v2.6.8, v3.0.1].
>     - Can only install one of: symfony/http-foundation[v2.6.9, v3.0.1].
>     - Can only install one of: symfony/http-foundation[v2.7.0, v3.0.1].
>     - Can only install one of: symfony/http-foundation[v2.7.1, v3.0.1].
>     - Can only install one of: symfony/http-foundation[v2.7.2, v3.0.1].
>     - Can only install one of: symfony/http-foundation[v2.7.3, v3.0.1].
>     - Can only install one of: symfony/http-foundation[v2.7.4, v3.0.1].
>     - Can only install one of: symfony/http-foundation[v2.7.5, v3.0.1].
>     - Can only install one of: symfony/http-foundation[v2.7.6, v3.0.1].
>     - Can only install one of: symfony/http-foundation[v2.7.7, v3.0.1].
>     - Can only install one of: symfony/http-foundation[v2.7.8, v3.0.1].
>     - Can only install one of: symfony/http-foundation[v2.7.9, v3.0.1].
>     - Installation request for symfony/http-foundation == 3.0.1.0 -> satisfiable by symfony/http-foundation[v3.0.1].

How can I resolve that?
Removing the symfony/http-foundation requires a lot of downgrades across the other packages.
Maybe I don't know all of composer commands. ¯\\\_(ツ)_/¯

**Comment by barryvdh** [comment]
You could use the `0.8.x@dev` version for now.

**Comment by barryvdh** [comment]
Can you test with `0.8.x`?

**Comment by glaucomorais** [comment]
Sorry for the delay.
Yeah, 0.8.x works.
