### ISSUE TITLE
Handle 'X-Requested-with' from the Hybrid App

### ISSUE THREAD

**Issue by pavankumarkatakam** [barryvdh/laravel-cors#99]
I have done a mobile app with the cordova, the pai is laravel backend enabled the laravel-cors, from the site i know the host i have given the allowedOrigins=['myhost.com'], and my app has no origin but it is giving the request with 'X-Request-with' header i want to allow this header with value to my android app value. how to do that?

**Comment by barryvdh** [comment]
Does Cordova use CORS checks? I thought it didn't.
Otherwise you could probably add '*' as allowed hosts, and add the X-Request-With header to the list of allowed headers.

**Comment by pavankumarkatakam** [comment]
Hi @barryvdh , up to now I have done as you set, if it so some other person also  create the same UI for my api , i.e., im leaving the api to be public it is not a desired thing for me. I only want to allow my website, my app to communicate with the api in laravel.

**Comment by kamgasimo** [comment]
Has anyone solved this issue ?
